{
  "entries": {
    "tap": {
      "homebrew/core": {
        "revision": "1da63443ca5c540b12cde7e1f12f5b107409ce75"
      },
      "homebrew/bundle": {
        "revision": "a4ce1156648a24ec0edd47d3a9f4cd16af689082"
      },
      "homebrew/cask": {
        "revision": "310084353af3d36d19b1d78026fa00058ecf0740"
      },
      "adoptopenjdk/openjdk": {
        "revision": "f6e8c971c98f5ba48aedf2a5d218ebc914ee2304"
      },
      "johanhaleby/kubetail": {
        "revision": "5673cb11add83338ab4540e36d6e049d5c845616"
      },
      "ladicle/kubectl-bindrole": {
        "revision": "58cab37a5050b7e36cde8017e22c278f615b8063"
      },
      "tektoncd/tools": {
        "revision": "f62f5a4d172632eeb29d656a7b7ef3efd1cdad47"
      },
      "jenkins-x/jx": {
        "revision": "9a76ebeecfde7c6bf75a5791b0126dcd0e0fa875"
      },
      "versent/taps": {
        "revision": "f3a4c99105e3ad517e9eef966b6b41321157bcaa"
      },
      "goreleaser/tap": {
        "revision": "8145139aee54d5bf04061e81875df1f09d6ed50e"
      },
      "warrensbox/tap": {
        "revision": "d4c30a96fff1381e0258a345b6046dab0b9aae74"
      },
      "aws/tap": {
        "revision": "7e63516ef27316bfabf9ff107a8fde2ad0049977"
      },
      "linuxkit/linuxkit": {
        "revision": "5cd37019fae91d1e92643bcc30538cb2b7679bde"
      }
    },
    "cask": {
      "sublime-text": {
        "version": "4126",
        "options": {
          "full_name": "sublime-text"
        }
      },
      "xquartz": {
        "version": "2.8.2",
        "options": {
          "full_name": "xquartz"
        }
      },
      "adoptopenjdk8": {
        "version": "8,292:b10",
        "options": {
          "full_name": "adoptopenjdk8"
        }
      },
      "aws-vault": {
        "version": "6.6.0",
        "options": {
          "full_name": "aws-vault"
        }
      },
      "docker": {
        "version": "4.10.1,82475",
        "options": {
          "full_name": "docker"
        }
      },
      "iterm2": {
        "version": "3.4.16",
        "options": {
          "full_name": "iterm2"
        }
      },
      "licecap": {
        "version": "1.32",
        "options": {
          "full_name": "licecap"
        }
      },
      "minikube": {
        "version": "1.4.0",
        "options": {
          "full_name": "minikube"
        }
      },
      "rubymine": {
        "version": "2022.1.3,221.5921.22",
        "options": {
          "full_name": "rubymine"
        }
      },
      "typora": {
        "version": "1.3.7",
        "options": {
          "full_name": "typora"
        }
      },
      "tunnelblick": {
        "version": "3.8.7a,5770",
        "options": {
          "full_name": "tunnelblick"
        }
      },
      "vagrant": {
        "version": "2.2.19",
        "options": {
          "full_name": "vagrant"
        }
      },
      "virtualbox": {
        "version": "6.1.34,150636",
        "options": {
          "full_name": "virtualbox"
        }
      },
      "virtualbox-extension-pack": {
        "version": "6.1.34",
        "options": {
          "full_name": "virtualbox-extension-pack"
        }
      },
      "zoomus": {
        "version": "5.0.24030.0508",
        "options": {
          "full_name": "zoomus"
        }
      },
      "keybase": {
        "version": "6.0.1,20220609162338,0fc9feea3d",
        "options": {
          "full_name": "keybase"
        }
      },
      "gpg-suite-no-mail": {
        "version": "2022.1",
        "options": {
          "full_name": "gpg-suite-no-mail"
        }
      },
      "whatsapp": {
        "version": "2.2222.12",
        "options": {
          "full_name": "whatsapp"
        }
      },
      "session-manager-plugin": {
        "version": "1.2.339.0",
        "options": {
          "full_name": "session-manager-plugin"
        }
      },
      "fritzing": {
        "version": "0.9.4,a1ffcea08814801903b1a9515b18cf97067968ae:498",
        "options": {
          "full_name": "fritzing"
        }
      },
      "gcc-arm-embedded": {
        "version": "11.2-2022.02",
        "options": {
          "full_name": "gcc-arm-embedded"
        }
      },
      "macspice": {
        "version": "3.1.24,341",
        "options": {
          "full_name": "macspice"
        }
      },
      "google-cloud-sdk": {
        "version": "latest",
        "options": {
          "full_name": "google-cloud-sdk"
        }
      },
      "zoom": {
        "version": "5.11.1.8356",
        "options": {
          "full_name": "zoom"
        }
      },
      "ultimaker-cura": {
        "version": "5.0.0",
        "options": {
          "full_name": "ultimaker-cura"
        }
      },
      "openscad": {
        "version": "2021.01",
        "options": {
          "full_name": "openscad"
        }
      },
      "blackhole-2ch": {
        "version": "0.4.0",
        "options": {
          "full_name": "blackhole-2ch"
        }
      },
      "gimp": {
        "version": "2.10.32",
        "options": {
          "full_name": "gimp"
        }
      },
      "1password-cli": {
        "version": "2.5.1",
        "options": {
          "full_name": "1password-cli"
        }
      }
    },
    "brew": {
      "ansible": {
        "version": "6.0.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:07f888d7b39215764cd49e5e4714d93849877ab7d8f96c5811d45e5316398dee",
              "sha256": "07f888d7b39215764cd49e5e4714d93849877ab7d8f96c5811d45e5316398dee"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:f5b15878e8e4eeeb3394981f18d05d4152479d31e62a1d72ee2f82cbf6cc997d",
              "sha256": "f5b15878e8e4eeeb3394981f18d05d4152479d31e62a1d72ee2f82cbf6cc997d"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:4dde4213451f4eccf447db87eff144bd5376398dae7e160237905eab9328dc55",
              "sha256": "4dde4213451f4eccf447db87eff144bd5376398dae7e160237905eab9328dc55"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:3259be2af84ca6c1c0cf775e65952999511c015f3771c6bbb9529d0cafdc6018",
              "sha256": "3259be2af84ca6c1c0cf775e65952999511c015f3771c6bbb9529d0cafdc6018"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:cae7ddec6391405e8280fb539602888533505f0723f8f44d59177cbdfbeba4fc",
              "sha256": "cae7ddec6391405e8280fb539602888533505f0723f8f44d59177cbdfbeba4fc"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:993ad95038a401698cebcd5bdc0d79a6758c546973924b1bf9b4f360fd82920e",
              "sha256": "993ad95038a401698cebcd5bdc0d79a6758c546973924b1bf9b4f360fd82920e"
            }
          }
        }
      },
      "awscli": {
        "version": "2.7.13",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:d52f9c27c21fb3293051f0b51773a4dda31286d9308f3bc93c51056c09662b3b",
              "sha256": "d52f9c27c21fb3293051f0b51773a4dda31286d9308f3bc93c51056c09662b3b"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:45a922bf552c3598023d4bac7a3489b2e9e99cfb8b6d0071b55824e085f981eb",
              "sha256": "45a922bf552c3598023d4bac7a3489b2e9e99cfb8b6d0071b55824e085f981eb"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:a9a879b4d3b51ecfe1b6ca736859ad719f28a865d38c4f17571d9d32ebfca7c9",
              "sha256": "a9a879b4d3b51ecfe1b6ca736859ad719f28a865d38c4f17571d9d32ebfca7c9"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:7692979748bdd84825f7278f98f1b6195357c0e548bc44d2b28de20634ade911",
              "sha256": "7692979748bdd84825f7278f98f1b6195357c0e548bc44d2b28de20634ade911"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:d89c8de98a96153676570bfe77b35c3e0fe8193ad81874bd2f528cb3f1057587",
              "sha256": "d89c8de98a96153676570bfe77b35c3e0fe8193ad81874bd2f528cb3f1057587"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:0478b05da2db18601261531eccfed99ed83143ec74c57b5d78e801c678be8806",
              "sha256": "0478b05da2db18601261531eccfed99ed83143ec74c57b5d78e801c678be8806"
            }
          }
        }
      },
      "coreutils": {
        "version": "9.1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:6a9a4988eda436fb5bdb5969044579c2e618e21eee8c8bbe32614ad29fe56bd7",
              "sha256": "6a9a4988eda436fb5bdb5969044579c2e618e21eee8c8bbe32614ad29fe56bd7"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:85ef910aa223d48c0e73fc187aba54b86930c86f906e3d079ed0b114762bb24e",
              "sha256": "85ef910aa223d48c0e73fc187aba54b86930c86f906e3d079ed0b114762bb24e"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:7c9f988b4f9207415a5c96efd32376bc8cf2b280a7a36fbebb0b8fc334a14056",
              "sha256": "7c9f988b4f9207415a5c96efd32376bc8cf2b280a7a36fbebb0b8fc334a14056"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:e446ef889d70bc377d67fa2d7f6a1fbc9faaee444a9e9086a1f5bd484069e5c0",
              "sha256": "e446ef889d70bc377d67fa2d7f6a1fbc9faaee444a9e9086a1f5bd484069e5c0"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:0d2117fa63dfcbb678c4e499f9ca0413c2c5bfa0a1bbdefde620434f2ead93a0",
              "sha256": "0d2117fa63dfcbb678c4e499f9ca0413c2c5bfa0a1bbdefde620434f2ead93a0"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:3c2fbec99344b50d620695d16197eb112cb8bee6d3f9e47cb682484755b91f38",
              "sha256": "3c2fbec99344b50d620695d16197eb112cb8bee6d3f9e47cb682484755b91f38"
            }
          }
        }
      },
      "direnv": {
        "version": "2.32.1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/direnv/blobs/sha256:567a8c1ca45ffae17d4901b0aa729be8866b6cb93ee8224da98cacf36f73ed69",
              "sha256": "567a8c1ca45ffae17d4901b0aa729be8866b6cb93ee8224da98cacf36f73ed69"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/direnv/blobs/sha256:b21230f43123e6b1a832f87d30f040d9f4684bb19f62f69f651bb24ae1cfaaab",
              "sha256": "b21230f43123e6b1a832f87d30f040d9f4684bb19f62f69f651bb24ae1cfaaab"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/direnv/blobs/sha256:68f7b9093d44fdef4210ffeaa8f88e8fa27bef356b4c8b2d4fc7749aab1d2614",
              "sha256": "68f7b9093d44fdef4210ffeaa8f88e8fa27bef356b4c8b2d4fc7749aab1d2614"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/direnv/blobs/sha256:f5dc03f040b2638a14e30c9fdeaaed616084539c0360fc916b53c3c8206259c4",
              "sha256": "f5dc03f040b2638a14e30c9fdeaaed616084539c0360fc916b53c3c8206259c4"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/direnv/blobs/sha256:2edc8e221d28db3da039490d4728d3c5ac7ce38d5274418b4d5f0ca31dfc0b28",
              "sha256": "2edc8e221d28db3da039490d4728d3c5ac7ce38d5274418b4d5f0ca31dfc0b28"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/direnv/blobs/sha256:c0356bf7cc43d0a1eb7777e7ed390f47f9dd8fb51cc480c8fb87fcde5fba1b4a",
              "sha256": "c0356bf7cc43d0a1eb7777e7ed390f47f9dd8fb51cc480c8fb87fcde5fba1b4a"
            }
          }
        }
      },
      "git": {
        "version": "2.37.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/git/blobs/sha256:a90bf8025d0b5e9eb153f5cf96a95c0b0bbbb486b2b2fca2833a656ed88c7e8a",
              "sha256": "a90bf8025d0b5e9eb153f5cf96a95c0b0bbbb486b2b2fca2833a656ed88c7e8a"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/git/blobs/sha256:348320ad2c512bfa66e56d8902c917fd982af98e4916fa8b2bd8d8f3eee047f9",
              "sha256": "348320ad2c512bfa66e56d8902c917fd982af98e4916fa8b2bd8d8f3eee047f9"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/git/blobs/sha256:a0b2ede51798b50401a15e169a9fa0c9628d5d4ab049d74924fb2950f9e2cb56",
              "sha256": "a0b2ede51798b50401a15e169a9fa0c9628d5d4ab049d74924fb2950f9e2cb56"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/git/blobs/sha256:147f30f8520d8f74b36557a1491b1a3b61ac4ffa9ac6461f6e00fc044126f0cc",
              "sha256": "147f30f8520d8f74b36557a1491b1a3b61ac4ffa9ac6461f6e00fc044126f0cc"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/git/blobs/sha256:91fc848f4e66e37e1f1bb5c5de9476c3af913f7319f92ee1f777a6f3ac986be0",
              "sha256": "91fc848f4e66e37e1f1bb5c5de9476c3af913f7319f92ee1f777a6f3ac986be0"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/git/blobs/sha256:c026f243cd73ffd292c158c1c6dab47180edd06109072dd04fad7e11a0e3a203",
              "sha256": "c026f243cd73ffd292c158c1c6dab47180edd06109072dd04fad7e11a0e3a203"
            }
          }
        }
      },
      "git-extras": {
        "version": "6.4.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "all": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-extras/blobs/sha256:75cbcd4fe8ad39801a46a6abadc8831aaacdb0bbf6f65eccc190c65c8b220985",
              "sha256": "75cbcd4fe8ad39801a46a6abadc8831aaacdb0bbf6f65eccc190c65c8b220985"
            }
          }
        }
      },
      "git-flow": {
        "version": "0.4.1",
        "bottle": {
          "cellar": ":any_skip_relocation",
          "prefix": "/usr/local",
          "files": {
            "catalina": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.catalina.bottle.tar.gz",
              "sha256": "8ea12cd7e2666fb6fdfaffaeb3a0437037a40cde559a835fc9de038f36a424dc"
            },
            "mojave": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.mojave.bottle.tar.gz",
              "sha256": "ab455769b6b8122e1d345f56d799fe43445bbbeba6265892715167388c737af9"
            },
            "high_sierra": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.high_sierra.bottle.tar.gz",
              "sha256": "ce4b64f4d13f4a5a8e05c9087627b42cd328c8accc8349c4ca256238d1d3fecc"
            },
            "sierra": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.sierra.bottle.tar.gz",
              "sha256": "acb9a2690fa86925600fa6e67e38731ef05f7f5d6ccfceb9c5175286c1081fe0"
            },
            "el_capitan": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.el_capitan.bottle.tar.gz",
              "sha256": "56826b30d91ffb54829f4792f88c673b1c3e748aa662bef5806e4a6f5d0ee015"
            },
            "yosemite": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.yosemite.bottle.tar.gz",
              "sha256": "a5e97d4d5c082194b36c18e7b051c43b2d5b37366b2ac56c5ea9407f6315685b"
            },
            "mavericks": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.mavericks.bottle.tar.gz",
              "sha256": "8e931605a0d12cffa282db7244e0041cc14f8a7692e184a6bc1975800be2dac0"
            }
          }
        }
      },
      "iperf3": {
        "version": "3.11",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/iperf3/blobs/sha256:07f43ee08140b9ed415ef4c84d58f0a0242ca4eb11bd5d9691e55066e341dbfd",
              "sha256": "07f43ee08140b9ed415ef4c84d58f0a0242ca4eb11bd5d9691e55066e341dbfd"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/iperf3/blobs/sha256:516f56b84472047a2ba899046ba1e71863ade4f4fb6cc0838ab863b576bc8157",
              "sha256": "516f56b84472047a2ba899046ba1e71863ade4f4fb6cc0838ab863b576bc8157"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/iperf3/blobs/sha256:3d6733f84c93d152e2ea210b3797a789e056b12f0a67ea8a615eb72c9eedac8e",
              "sha256": "3d6733f84c93d152e2ea210b3797a789e056b12f0a67ea8a615eb72c9eedac8e"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/iperf3/blobs/sha256:b23050ed3f6e8fd6cf43597446fd172b612a2ab539c1b71210ad45182563fb3c",
              "sha256": "b23050ed3f6e8fd6cf43597446fd172b612a2ab539c1b71210ad45182563fb3c"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/iperf3/blobs/sha256:b3d74087ec104d3b95e491257d647a3e665ed3f5ff63ba176fc4d3d27e253f8c",
              "sha256": "b3d74087ec104d3b95e491257d647a3e665ed3f5ff63ba176fc4d3d27e253f8c"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/iperf3/blobs/sha256:b3d05c024cb3e1a062734db9bff61758385b9058aefb896330c9136f37754aff",
              "sha256": "b3d05c024cb3e1a062734db9bff61758385b9058aefb896330c9136f37754aff"
            }
          }
        }
      },
      "libtool": {
        "version": "2.4.7",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:5f92327e52a1196e8742cb5b3a64498c811d51aed658355c205858d2a835fdc9",
              "sha256": "5f92327e52a1196e8742cb5b3a64498c811d51aed658355c205858d2a835fdc9"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:6f676b306c72b04dd0e24cc96f51117e91719a4743743dc5527c16bf03f21320",
              "sha256": "6f676b306c72b04dd0e24cc96f51117e91719a4743743dc5527c16bf03f21320"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:33bf8379256791a8e8752541bf4e182090dcef5f73aa8faa5f6521d16414a6ca",
              "sha256": "33bf8379256791a8e8752541bf4e182090dcef5f73aa8faa5f6521d16414a6ca"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:bae30841faca7f4b91e5388c0db13cd6cc95df0182b6d21a62b4c1ea508ebb69",
              "sha256": "bae30841faca7f4b91e5388c0db13cd6cc95df0182b6d21a62b4c1ea508ebb69"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:624bb469bae686405b26ac05706c5f750bed31cd23995a9fa91cc31646e0eadc",
              "sha256": "624bb469bae686405b26ac05706c5f750bed31cd23995a9fa91cc31646e0eadc"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:1cde2899a36adf5b04d25a9b8b4d6bec8a3099bc59ae68c63e479a4da8ca70b3",
              "sha256": "1cde2899a36adf5b04d25a9b8b4d6bec8a3099bc59ae68c63e479a4da8ca70b3"
            }
          }
        }
      },
      "helm": {
        "version": "3.9.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/blobs/sha256:14fc008242f71fef52a1bcc08e6a27fd4e11d6f41c84aab97b68684fa36955bc",
              "sha256": "14fc008242f71fef52a1bcc08e6a27fd4e11d6f41c84aab97b68684fa36955bc"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/blobs/sha256:8c04aa5293c2a0a7f197e5c68e59b108ed2c4e763212b14fb35c079ef5804bf4",
              "sha256": "8c04aa5293c2a0a7f197e5c68e59b108ed2c4e763212b14fb35c079ef5804bf4"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/blobs/sha256:ee5b2e0a917bac5c1c3af5ccb18520505a84645ba27e60dd1eaa0ae5b543bcd9",
              "sha256": "ee5b2e0a917bac5c1c3af5ccb18520505a84645ba27e60dd1eaa0ae5b543bcd9"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/blobs/sha256:d3c71ebbc844fcc66af53168f547e25ab25f65a3b0f491d92608e3d89ddb2842",
              "sha256": "d3c71ebbc844fcc66af53168f547e25ab25f65a3b0f491d92608e3d89ddb2842"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/blobs/sha256:7a8b3f8995d97418b293f8b4847c74d3314c38bf72e66f1e7eeaf56a832a5f32",
              "sha256": "7a8b3f8995d97418b293f8b4847c74d3314c38bf72e66f1e7eeaf56a832a5f32"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/blobs/sha256:27ff6e13c6e534dab8ab38ca9711f8905fdc93b787d687be48176313bc537f4d",
              "sha256": "27ff6e13c6e534dab8ab38ca9711f8905fdc93b787d687be48176313bc537f4d"
            }
          }
        }
      },
      "jenv": {
        "version": "0.5.5_2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "all": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/jenv/blobs/sha256:e27ff89af1af1cbcbfd3b46d99f1c97f1badbbb9a76cbca22a4400ede1e5acb0",
              "sha256": "e27ff89af1af1cbcbfd3b46d99f1c97f1badbbb9a76cbca22a4400ede1e5acb0"
            }
          }
        }
      },
      "jq": {
        "version": "1.6",
        "bottle": {
          "rebuild": 1,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:f70e1ae8df182b242ca004492cc0a664e2a8195e2e46f30546fe78e265d5eb87",
              "sha256": "f70e1ae8df182b242ca004492cc0a664e2a8195e2e46f30546fe78e265d5eb87"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:674b3ae41c399f1e8e44c271b0e6909babff9fcd2e04a2127d25e2407ea4dd33",
              "sha256": "674b3ae41c399f1e8e44c271b0e6909babff9fcd2e04a2127d25e2407ea4dd33"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:7fee6ea327062b37d34ef5346a84810a1752cc7146fff1223fab76c9b45686e0",
              "sha256": "7fee6ea327062b37d34ef5346a84810a1752cc7146fff1223fab76c9b45686e0"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:bf0f8577632af7b878b6425476f5b1ab9c3bf66d65affb0c455048a173a0b6bf",
              "sha256": "bf0f8577632af7b878b6425476f5b1ab9c3bf66d65affb0c455048a173a0b6bf"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:820a3c85fcbb63088b160c7edf125d7e55fc2c5c1d51569304499c9cc4b89ce8",
              "sha256": "820a3c85fcbb63088b160c7edf125d7e55fc2c5c1d51569304499c9cc4b89ce8"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:71f0e76c5b22e5088426c971d5e795fe67abee7af6c2c4ae0cf4c0eb98ed21ff",
              "sha256": "71f0e76c5b22e5088426c971d5e795fe67abee7af6c2c4ae0cf4c0eb98ed21ff"
            },
            "high_sierra": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:dffcffa4ea13e8f0f2b45c5121e529077e135ae9a47254c32182231662ee9b72",
              "sha256": "dffcffa4ea13e8f0f2b45c5121e529077e135ae9a47254c32182231662ee9b72"
            },
            "sierra": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:bb4d19dc026c2d72c53eed78eaa0ab982e9fcad2cd2acc6d13e7a12ff658e877",
              "sha256": "bb4d19dc026c2d72c53eed78eaa0ab982e9fcad2cd2acc6d13e7a12ff658e877"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:2beea2c2c372ccf1081e9a5233fc3020470803254284aeecc071249d76b62338",
              "sha256": "2beea2c2c372ccf1081e9a5233fc3020470803254284aeecc071249d76b62338"
            }
          }
        }
      },
      "krew": {
        "version": "0.4.3",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/krew/blobs/sha256:93179328dd5beac3e977ab799d596925d927efa4420a6cb0950970386e4e8146",
              "sha256": "93179328dd5beac3e977ab799d596925d927efa4420a6cb0950970386e4e8146"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/krew/blobs/sha256:b9585376236e8f86e158864ff610edeca3eb83ad5566fa4a2a09f3fc35d6fe88",
              "sha256": "b9585376236e8f86e158864ff610edeca3eb83ad5566fa4a2a09f3fc35d6fe88"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/krew/blobs/sha256:d814754adf0a451c529a745b5ddc6587c0057d8050294610f396f97271e23e42",
              "sha256": "d814754adf0a451c529a745b5ddc6587c0057d8050294610f396f97271e23e42"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/krew/blobs/sha256:286bae73781b3ced48cb18133afc6c3224dd15fef262dee1e17a53a8bed2dd6f",
              "sha256": "286bae73781b3ced48cb18133afc6c3224dd15fef262dee1e17a53a8bed2dd6f"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/krew/blobs/sha256:9c95c5f27125a2edcd294310c83d01c5ecbe0e1bb456fa3cc57ba6a632987278",
              "sha256": "9c95c5f27125a2edcd294310c83d01c5ecbe0e1bb456fa3cc57ba6a632987278"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/krew/blobs/sha256:3dbbeefb32e6340c061091a744b4d5e4c7573e96a3512b27064349f286a1976e",
              "sha256": "3dbbeefb32e6340c061091a744b4d5e4c7573e96a3512b27064349f286a1976e"
            }
          }
        }
      },
      "kubernetes-cli": {
        "version": "1.24.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:61abc1468c831b2290aab7c1eaaa88c8a7d7010a438ac65fb9f9b8ea43d69589",
              "sha256": "61abc1468c831b2290aab7c1eaaa88c8a7d7010a438ac65fb9f9b8ea43d69589"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:7edf620cbf977b2bd180b39682b24913bbe0ffa6884e51ee30fb96aa7ae9661c",
              "sha256": "7edf620cbf977b2bd180b39682b24913bbe0ffa6884e51ee30fb96aa7ae9661c"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:b6c15b7ec1524e3a92bf3a60e2628790bf073ef9eba2f5ef70c915a57150834d",
              "sha256": "b6c15b7ec1524e3a92bf3a60e2628790bf073ef9eba2f5ef70c915a57150834d"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:d7ab898925b4b21ad1bcc1af7cb7671b303a5c3ff612a54594df0a3423406691",
              "sha256": "d7ab898925b4b21ad1bcc1af7cb7671b303a5c3ff612a54594df0a3423406691"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:e67e1eb07fb61a7c4aea14738d4d6b54c7e79da6e7499709b835d3d569939695",
              "sha256": "e67e1eb07fb61a7c4aea14738d4d6b54c7e79da6e7499709b835d3d569939695"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:42e2f4fbed12d8e5a55470f3d98e8d0a5f4c72da4377859cd280d67b224ee8e2",
              "sha256": "42e2f4fbed12d8e5a55470f3d98e8d0a5f4c72da4377859cd280d67b224ee8e2"
            }
          }
        }
      },
      "kubectx": {
        "version": "0.9.4",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "all": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubectx/blobs/sha256:56fca18baee3ff65f4e6ca1491b515f46bcb61c3d184bc68c77c1b06e2e32cfb",
              "sha256": "56fca18baee3ff65f4e6ca1491b515f46bcb61c3d184bc68c77c1b06e2e32cfb"
            }
          }
        }
      },
      "kubetail": {
        "version": "1.6.15",
        "bottle": false
      },
      "maven": {
        "version": "3.8.6",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/maven/blobs/sha256:0468fde1ed91dda88ce1be54ca222c23f9436e579e5e45a2ca38c26dda304e7f",
              "sha256": "0468fde1ed91dda88ce1be54ca222c23f9436e579e5e45a2ca38c26dda304e7f"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/maven/blobs/sha256:0468fde1ed91dda88ce1be54ca222c23f9436e579e5e45a2ca38c26dda304e7f",
              "sha256": "0468fde1ed91dda88ce1be54ca222c23f9436e579e5e45a2ca38c26dda304e7f"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/maven/blobs/sha256:016e037ae5ca2e5ec6e3268839bec1dbc2e4af0e30960efd16ef12ed0aa56969",
              "sha256": "016e037ae5ca2e5ec6e3268839bec1dbc2e4af0e30960efd16ef12ed0aa56969"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/maven/blobs/sha256:016e037ae5ca2e5ec6e3268839bec1dbc2e4af0e30960efd16ef12ed0aa56969",
              "sha256": "016e037ae5ca2e5ec6e3268839bec1dbc2e4af0e30960efd16ef12ed0aa56969"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/maven/blobs/sha256:016e037ae5ca2e5ec6e3268839bec1dbc2e4af0e30960efd16ef12ed0aa56969",
              "sha256": "016e037ae5ca2e5ec6e3268839bec1dbc2e4af0e30960efd16ef12ed0aa56969"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/maven/blobs/sha256:0468fde1ed91dda88ce1be54ca222c23f9436e579e5e45a2ca38c26dda304e7f",
              "sha256": "0468fde1ed91dda88ce1be54ca222c23f9436e579e5e45a2ca38c26dda304e7f"
            }
          }
        }
      },
      "mysql": {
        "version": "8.0.29",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:462d849e91bcaed0ea7faf967e50cb13166c9d1f1e7ee72849cd14fde1b41392",
              "sha256": "462d849e91bcaed0ea7faf967e50cb13166c9d1f1e7ee72849cd14fde1b41392"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:041bae356a31fb942e57827c7bcacd327dafaf9ae30f2654c65758d8053c282b",
              "sha256": "041bae356a31fb942e57827c7bcacd327dafaf9ae30f2654c65758d8053c282b"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:b152c47fb301c2200ea6ccc525307910b903879ed8ba2f0912e09934da9a864d",
              "sha256": "b152c47fb301c2200ea6ccc525307910b903879ed8ba2f0912e09934da9a864d"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:39704edeac2cb2fac5494b0f5f313fb40f0336fc425f1a78af29a5ded340525d",
              "sha256": "39704edeac2cb2fac5494b0f5f313fb40f0336fc425f1a78af29a5ded340525d"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:c5ff449dce2bcb26adbf2ec725821df32f4b7e23be1d1d315a5abc94e39bbc01",
              "sha256": "c5ff449dce2bcb26adbf2ec725821df32f4b7e23be1d1d315a5abc94e39bbc01"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:0bef9bedc6ffcec182258d8d2e471821fcecd82058e6a74d96ed5282d00a4001",
              "sha256": "0bef9bedc6ffcec182258d8d2e471821fcecd82058e6a74d96ed5282d00a4001"
            }
          }
        }
      },
      "node": {
        "version": "18.5.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/node/blobs/sha256:9e80d9b5357f5947a95518df1c1c84d300dd3175090c1f31366f91e0f268756b",
              "sha256": "9e80d9b5357f5947a95518df1c1c84d300dd3175090c1f31366f91e0f268756b"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/node/blobs/sha256:9ef2e4502aae9e316bafe61806a44aa98e19e80b734a253a6e11ce73090de29c",
              "sha256": "9ef2e4502aae9e316bafe61806a44aa98e19e80b734a253a6e11ce73090de29c"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/node/blobs/sha256:4fcce9236ed247e4443d482df03375e8f5ba01b6dbd880da1172997d8de3da88",
              "sha256": "4fcce9236ed247e4443d482df03375e8f5ba01b6dbd880da1172997d8de3da88"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/node/blobs/sha256:cbdd2bcbae50d828c4525bb6ab3d39e106c9349359a0ada4fe01dd08030559d7",
              "sha256": "cbdd2bcbae50d828c4525bb6ab3d39e106c9349359a0ada4fe01dd08030559d7"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/node/blobs/sha256:38c8d7047514c669df32f5751c42e027be9c5165e8538208e9806e70daaa0d68",
              "sha256": "38c8d7047514c669df32f5751c42e027be9c5165e8538208e9806e70daaa0d68"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/node/blobs/sha256:1ef1c7a0033a5af788b57c01df26d302248d0cf57f9c3d0ede5e9d91f781c37b",
              "sha256": "1ef1c7a0033a5af788b57c01df26d302248d0cf57f9c3d0ede5e9d91f781c37b"
            }
          }
        }
      },
      "p7zip": {
        "version": "17.04",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:6b411a180788d3702feb447c95a24fba571277c8708db22929ff4a98e269ed5b",
              "sha256": "6b411a180788d3702feb447c95a24fba571277c8708db22929ff4a98e269ed5b"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:d1e2497a5256b9211572534456bb7271c9d04d10fc2e12599b95e0ddf4f1991b",
              "sha256": "d1e2497a5256b9211572534456bb7271c9d04d10fc2e12599b95e0ddf4f1991b"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:63427747e339024f690bdffeac4848e8e46cc17c6189713054b130725a00b43c",
              "sha256": "63427747e339024f690bdffeac4848e8e46cc17c6189713054b130725a00b43c"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:c4d62f05f0cba984aa6b5712debc4f7d3b2c3bece0c503633a588cb209c911c2",
              "sha256": "c4d62f05f0cba984aa6b5712debc4f7d3b2c3bece0c503633a588cb209c911c2"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:bea86999db7dee5f0cb78d3a72d875d822ec73ebb2a6e7d46cf27ae66243c645",
              "sha256": "bea86999db7dee5f0cb78d3a72d875d822ec73ebb2a6e7d46cf27ae66243c645"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:1484f0f3a0a4812dccb5f388c6671a7e524b001872b0df6d7cabc160c2f03989",
              "sha256": "1484f0f3a0a4812dccb5f388c6671a7e524b001872b0df6d7cabc160c2f03989"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:d996780ca46e35a641f5f37284d19490cb5e0a990c9369045e92ba463d99430a",
              "sha256": "d996780ca46e35a641f5f37284d19490cb5e0a990c9369045e92ba463d99430a"
            }
          }
        }
      },
      "packer": {
        "version": "1.8.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:a54982fe5bb4c6d5cf543d425389f83fa318776ed236a399e709b20f319cdf98",
              "sha256": "a54982fe5bb4c6d5cf543d425389f83fa318776ed236a399e709b20f319cdf98"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:bbf39fb83ad1296979d6a11c9bf167d6316e20a6a49316310a5a0157e75ed3a5",
              "sha256": "bbf39fb83ad1296979d6a11c9bf167d6316e20a6a49316310a5a0157e75ed3a5"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:f8a0663aacc5eb8c7c0c0ee755ede4de91249c77049cdefce8765c15241fb4b3",
              "sha256": "f8a0663aacc5eb8c7c0c0ee755ede4de91249c77049cdefce8765c15241fb4b3"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:fd9bf699d687d18eaf5ee7210f367395a2609588af7773ad752f1c6f304cbc5d",
              "sha256": "fd9bf699d687d18eaf5ee7210f367395a2609588af7773ad752f1c6f304cbc5d"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:d58410e68c44b6653cbdea1d1d2525b51401489a941dcd79551615bb2324928e",
              "sha256": "d58410e68c44b6653cbdea1d1d2525b51401489a941dcd79551615bb2324928e"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:cb2e7376f606050ea184dedd2093f9fa64a0eb5a6655531490172e413c173a96",
              "sha256": "cb2e7376f606050ea184dedd2093f9fa64a0eb5a6655531490172e413c173a96"
            }
          }
        }
      },
      "pandoc": {
        "version": "2.18",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:9411a015436638767a62eefe22891228dfc00ee5ab3d1469637f65a83bf07f3b",
              "sha256": "9411a015436638767a62eefe22891228dfc00ee5ab3d1469637f65a83bf07f3b"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:77318c0209980baad255423e1eefbef40d696be949770be3d189554bffab3d64",
              "sha256": "77318c0209980baad255423e1eefbef40d696be949770be3d189554bffab3d64"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:2c975ede0463a4135548342e436d073a724c3643186a1daa6417855261f5407b",
              "sha256": "2c975ede0463a4135548342e436d073a724c3643186a1daa6417855261f5407b"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:87fcbed2bd56b65fd815197048e4926abeed631e35dc4770b9b3a1e3049eb285",
              "sha256": "87fcbed2bd56b65fd815197048e4926abeed631e35dc4770b9b3a1e3049eb285"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:79354a16ef3a9ab20d9911f97cce261a039ad5109bd2f134c96e0febdf5414be",
              "sha256": "79354a16ef3a9ab20d9911f97cce261a039ad5109bd2f134c96e0febdf5414be"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:f5925683a5d57816ea6da9eed054063fa3cba5863282c912162622d56e1c53d6",
              "sha256": "f5925683a5d57816ea6da9eed054063fa3cba5863282c912162622d56e1c53d6"
            }
          }
        }
      },
      "pipenv": {
        "version": "2022.6.7",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pipenv/blobs/sha256:b13deb536e0676b6e40266aa061a78706d2d7be4166a098cd1e7db912ba13778",
              "sha256": "b13deb536e0676b6e40266aa061a78706d2d7be4166a098cd1e7db912ba13778"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pipenv/blobs/sha256:86230b8730d7c14f1c84e57546b42c9d190b385acce8a1918dcc5dac6c974488",
              "sha256": "86230b8730d7c14f1c84e57546b42c9d190b385acce8a1918dcc5dac6c974488"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pipenv/blobs/sha256:65a14e232883fde3c5a6c63f705790a27767950246fbeee06b089423020f86bf",
              "sha256": "65a14e232883fde3c5a6c63f705790a27767950246fbeee06b089423020f86bf"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pipenv/blobs/sha256:dff877347de085ef6b97d10bf561a6c86aad0af8f57d4b34a1c2e5e519858330",
              "sha256": "dff877347de085ef6b97d10bf561a6c86aad0af8f57d4b34a1c2e5e519858330"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pipenv/blobs/sha256:8af57cf76b2d1168da661d18c72d4ffa751c5bbb79eea6f984b40935c648d7e8",
              "sha256": "8af57cf76b2d1168da661d18c72d4ffa751c5bbb79eea6f984b40935c648d7e8"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pipenv/blobs/sha256:a235f21a870624aca0096f44ef4b6b07da80b88e459bd4b8281dccdee6e7b4a8",
              "sha256": "a235f21a870624aca0096f44ef4b6b07da80b88e459bd4b8281dccdee6e7b4a8"
            }
          }
        }
      },
      "python": {
        "version": "3.9.13_1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:2e02d1c12a0baecc8b1af05701c7db8038e6b9a7bf453cc49992eef74c268f7b",
              "sha256": "2e02d1c12a0baecc8b1af05701c7db8038e6b9a7bf453cc49992eef74c268f7b"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:2b26548e5bd01505398539a0a4ba8a891cae2688569d109295e16bc91342d17c",
              "sha256": "2b26548e5bd01505398539a0a4ba8a891cae2688569d109295e16bc91342d17c"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:74a5bc1cb0c57f60a65f63f4c2cd7b10ce9aed3fb0d4e8634be0e7f44b8d02a7",
              "sha256": "74a5bc1cb0c57f60a65f63f4c2cd7b10ce9aed3fb0d4e8634be0e7f44b8d02a7"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:c91826d8daf2835b6b0f4dbc1697e8cb6227e2cc3cb7d9dfd47a73e4da1636f0",
              "sha256": "c91826d8daf2835b6b0f4dbc1697e8cb6227e2cc3cb7d9dfd47a73e4da1636f0"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:4cb2b93b180f1aeacd7a89551c36ff0986c8cf31d66099649f44067755c83866",
              "sha256": "4cb2b93b180f1aeacd7a89551c36ff0986c8cf31d66099649f44067755c83866"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:ba4a42a1bb96ff3abe62e2f622bbe304b42c99b2d6e5381f5fa761d022c4a1d8",
              "sha256": "ba4a42a1bb96ff3abe62e2f622bbe304b42c99b2d6e5381f5fa761d022c4a1d8"
            }
          }
        }
      },
      "ruby@2.5": {
        "version": "2.5.9",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:d88a21825cea4e2e1d1382effb53d640c23472e46e3f8b4c3f63e2571e0b37d1",
              "sha256": "d88a21825cea4e2e1d1382effb53d640c23472e46e3f8b4c3f63e2571e0b37d1"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:deb2ee5e006f4fc7b3829dfcdb377300f3dc5f339562a6a1c1b4dec48ed21ae6",
              "sha256": "deb2ee5e006f4fc7b3829dfcdb377300f3dc5f339562a6a1c1b4dec48ed21ae6"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:67b01aac127e5ffeae54ee90f79aa137f69f2dede97ca3e390a472474ee5e11f",
              "sha256": "67b01aac127e5ffeae54ee90f79aa137f69f2dede97ca3e390a472474ee5e11f"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:fb6b696623fc988abecbf9fb9f5298219c62c69851123b9d9d69c3f127b0ec3c",
              "sha256": "fb6b696623fc988abecbf9fb9f5298219c62c69851123b9d9d69c3f127b0ec3c"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:8fab1468c593b5907e027c175dc19e3273b08cc8b344822ce593dcab645e857d",
              "sha256": "8fab1468c593b5907e027c175dc19e3273b08cc8b344822ce593dcab645e857d"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:ef4974800a4417e6251fb548486150157c2f0ff62275170431381480bac1c3ed",
              "sha256": "ef4974800a4417e6251fb548486150157c2f0ff62275170431381480bac1c3ed"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:8b85cf06b1f139109bae913ade71190a65fb71f7848d846428cf95dbd0658e05",
              "sha256": "8b85cf06b1f139109bae913ade71190a65fb71f7848d846428cf95dbd0658e05"
            }
          }
        },
        "options": {
          "link": true,
          "conflicts_with": [
            "ruby"
          ]
        }
      },
      "terraform": {
        "version": "0.15.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terraform/blobs/sha256:0f7869b857c16b69c8a763f3a3dde378ce354445df03e6b965f60a80763eab2d",
              "sha256": "0f7869b857c16b69c8a763f3a3dde378ce354445df03e6b965f60a80763eab2d"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terraform/blobs/sha256:59046fe843b88927c89b6e1d0008b536fe19bbfb411be98507b8d11e9dc066f0",
              "sha256": "59046fe843b88927c89b6e1d0008b536fe19bbfb411be98507b8d11e9dc066f0"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terraform/blobs/sha256:8fdb8b4cd622bdf4f8503a5f1e53fb3ea3eddb5af5d94b9bb5df716133cda17a",
              "sha256": "8fdb8b4cd622bdf4f8503a5f1e53fb3ea3eddb5af5d94b9bb5df716133cda17a"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terraform/blobs/sha256:46079e3b1ff04a34902d604dcbdb4cf3f37c6679ca2e4b4b756a053a9628b063",
              "sha256": "46079e3b1ff04a34902d604dcbdb4cf3f37c6679ca2e4b4b756a053a9628b063"
            }
          }
        }
      },
      "unrar": {
        "version": "5.9.4",
        "bottle": false
      },
      "vault": {
        "version": "1.11.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/vault/blobs/sha256:152353389c862269a421ea7d5b8529dcbe37228eb7ea6ab39dd1813b03f45852",
              "sha256": "152353389c862269a421ea7d5b8529dcbe37228eb7ea6ab39dd1813b03f45852"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/vault/blobs/sha256:f8bf80a56b92bf7a720baf9e977db5268f6b2f62944445846ac957954feb1f93",
              "sha256": "f8bf80a56b92bf7a720baf9e977db5268f6b2f62944445846ac957954feb1f93"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/vault/blobs/sha256:748162441ee47a1f7e9b4fb79bf6b5e4c61145c0c1bb6688b6930f7f5cb642e6",
              "sha256": "748162441ee47a1f7e9b4fb79bf6b5e4c61145c0c1bb6688b6930f7f5cb642e6"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/vault/blobs/sha256:fa7531271441084ea7dbccc19d76680de3614e71ff3fbac569f4eadcf5be9364",
              "sha256": "fa7531271441084ea7dbccc19d76680de3614e71ff3fbac569f4eadcf5be9364"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/vault/blobs/sha256:191e2418eb1063cad138b1ecbf2696f910582a37c0c721942216e6c7f194dc5d",
              "sha256": "191e2418eb1063cad138b1ecbf2696f910582a37c0c721942216e6c7f194dc5d"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/vault/blobs/sha256:a40b2327ff34d7e76975377c1e91ce1aed6d84cb32ce4708228df57b7404c317",
              "sha256": "a40b2327ff34d7e76975377c1e91ce1aed6d84cb32ce4708228df57b7404c317"
            }
          }
        }
      },
      "watch": {
        "version": "4.0.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/watch/blobs/sha256:99135b41e5c85d6faaeaa3b3f9c74b17eea68d1394b639e3f4824ed4a582e9c4",
              "sha256": "99135b41e5c85d6faaeaa3b3f9c74b17eea68d1394b639e3f4824ed4a582e9c4"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/watch/blobs/sha256:4560b743e716fa5aaff0b809fbf8e0fbcc9c71f4e4f502b77acb2f9130b846e0",
              "sha256": "4560b743e716fa5aaff0b809fbf8e0fbcc9c71f4e4f502b77acb2f9130b846e0"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/watch/blobs/sha256:2133244ca4acb47a37f24fa3930c5ab7d200b98d0d46fb80a7fb459373389e0e",
              "sha256": "2133244ca4acb47a37f24fa3930c5ab7d200b98d0d46fb80a7fb459373389e0e"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/watch/blobs/sha256:77383edb8de69055e0156ac24ba26f9c786b0d40e72d8e72a2c068d36f64c45e",
              "sha256": "77383edb8de69055e0156ac24ba26f9c786b0d40e72d8e72a2c068d36f64c45e"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/watch/blobs/sha256:32271afc05e243444040094864b075f61079a3464197699870b5026d4b3f62a8",
              "sha256": "32271afc05e243444040094864b075f61079a3464197699870b5026d4b3f62a8"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/watch/blobs/sha256:f6b323f891f08beffb572b77b70e371906ec9a263de9176bcf444e5d91c41719",
              "sha256": "f6b323f891f08beffb572b77b70e371906ec9a263de9176bcf444e5d91c41719"
            }
          }
        }
      },
      "wget": {
        "version": "1.21.3",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:fc83eec77acee50d2d7ce3bb0cca08d80acccc148e909921de42e57dd5fc7f3d",
              "sha256": "fc83eec77acee50d2d7ce3bb0cca08d80acccc148e909921de42e57dd5fc7f3d"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:a0c491ae7de2b722320efa94704567e36f3a0bd04bd946b1431ecbd1bcbfb899",
              "sha256": "a0c491ae7de2b722320efa94704567e36f3a0bd04bd946b1431ecbd1bcbfb899"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:aa706c58ae7e97abf91be56e785335aff058c431f9973dffac06aacbea558497",
              "sha256": "aa706c58ae7e97abf91be56e785335aff058c431f9973dffac06aacbea558497"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:b90e0d7a4319ccdb18ee0c2ed097e9cddeeceaaf70dc0a785d96b4ba69dbeb54",
              "sha256": "b90e0d7a4319ccdb18ee0c2ed097e9cddeeceaaf70dc0a785d96b4ba69dbeb54"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:2aadef5aae81ecdd7e28bc9a776adcf0eaa393edae904e0c69740a442b7a3e69",
              "sha256": "2aadef5aae81ecdd7e28bc9a776adcf0eaa393edae904e0c69740a442b7a3e69"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:b6f20b1f4da03b9ee6a42f9305ee015eae7f80afea198e405c0b775eb2333de1",
              "sha256": "b6f20b1f4da03b9ee6a42f9305ee015eae7f80afea198e405c0b775eb2333de1"
            }
          }
        }
      },
      "youtube-dl": {
        "version": "2021.12.17",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:79bc7ca875b43074c1a7097674b900835c5358e80d81a177b1eecf0e69b77a7a",
              "sha256": "79bc7ca875b43074c1a7097674b900835c5358e80d81a177b1eecf0e69b77a7a"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:79bc7ca875b43074c1a7097674b900835c5358e80d81a177b1eecf0e69b77a7a",
              "sha256": "79bc7ca875b43074c1a7097674b900835c5358e80d81a177b1eecf0e69b77a7a"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:a8da6929ac2005f3bf5e004ccd1f860c6368cc49ea4d4846a0b902d21cc0cb7b",
              "sha256": "a8da6929ac2005f3bf5e004ccd1f860c6368cc49ea4d4846a0b902d21cc0cb7b"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:a8da6929ac2005f3bf5e004ccd1f860c6368cc49ea4d4846a0b902d21cc0cb7b",
              "sha256": "a8da6929ac2005f3bf5e004ccd1f860c6368cc49ea4d4846a0b902d21cc0cb7b"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:a8da6929ac2005f3bf5e004ccd1f860c6368cc49ea4d4846a0b902d21cc0cb7b",
              "sha256": "a8da6929ac2005f3bf5e004ccd1f860c6368cc49ea4d4846a0b902d21cc0cb7b"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:1d96e5082a83cd8d333f72f40592ff577a4c4ccf4e654ddf2c3e38fccbb5c1f9",
              "sha256": "1d96e5082a83cd8d333f72f40592ff577a4c4ccf4e654ddf2c3e38fccbb5c1f9"
            }
          }
        }
      },
      "azure-cli": {
        "version": "2.38.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/azure-cli/blobs/sha256:05185c2ea6c7729df85de2a66bda8593a9aea473ce0c2ccc59fd44032a667391",
              "sha256": "05185c2ea6c7729df85de2a66bda8593a9aea473ce0c2ccc59fd44032a667391"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/azure-cli/blobs/sha256:a3c9f576c1c90e96e30bfc5e0eb8f94166dacd339ea63aa4b1c4a033c5e4aeee",
              "sha256": "a3c9f576c1c90e96e30bfc5e0eb8f94166dacd339ea63aa4b1c4a033c5e4aeee"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/azure-cli/blobs/sha256:9d96cf463d9256a408249ba78e5e48cee719fc829e1a2e605358a2087ae8225d",
              "sha256": "9d96cf463d9256a408249ba78e5e48cee719fc829e1a2e605358a2087ae8225d"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/azure-cli/blobs/sha256:29ae6de72e5c3fd2152ddb5af34b5aa27402316b0329382f8b0ba6f36311576b",
              "sha256": "29ae6de72e5c3fd2152ddb5af34b5aa27402316b0329382f8b0ba6f36311576b"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/azure-cli/blobs/sha256:22dd9aa6ac745fed96f082c707d9eedb4bb278febddb32a9f1c474b23582f49c",
              "sha256": "22dd9aa6ac745fed96f082c707d9eedb4bb278febddb32a9f1c474b23582f49c"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/azure-cli/blobs/sha256:f9f6f1e096c3a038ca4953a3cf3575869b760dedd438bcff0320e6c80f6ec0e7",
              "sha256": "f9f6f1e096c3a038ca4953a3cf3575869b760dedd438bcff0320e6c80f6ec0e7"
            }
          }
        }
      },
      "git-flow-avh": {
        "version": "1.12.3",
        "bottle": {
          "rebuild": 1,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:f559b035f16d9f56bb1750bfd441785df1f094a3838b20c1c51503cc75c2f319",
              "sha256": "f559b035f16d9f56bb1750bfd441785df1f094a3838b20c1c51503cc75c2f319"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:f559b035f16d9f56bb1750bfd441785df1f094a3838b20c1c51503cc75c2f319",
              "sha256": "f559b035f16d9f56bb1750bfd441785df1f094a3838b20c1c51503cc75c2f319"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:fe31ea33fecc7177f22fa64b15430512ea2ae728536d3c3d21b9121d97e311e6",
              "sha256": "fe31ea33fecc7177f22fa64b15430512ea2ae728536d3c3d21b9121d97e311e6"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:fe31ea33fecc7177f22fa64b15430512ea2ae728536d3c3d21b9121d97e311e6",
              "sha256": "fe31ea33fecc7177f22fa64b15430512ea2ae728536d3c3d21b9121d97e311e6"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:fe31ea33fecc7177f22fa64b15430512ea2ae728536d3c3d21b9121d97e311e6",
              "sha256": "fe31ea33fecc7177f22fa64b15430512ea2ae728536d3c3d21b9121d97e311e6"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:f559b035f16d9f56bb1750bfd441785df1f094a3838b20c1c51503cc75c2f319",
              "sha256": "f559b035f16d9f56bb1750bfd441785df1f094a3838b20c1c51503cc75c2f319"
            }
          }
        }
      },
      "gnu-getopt": {
        "version": "2.38",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gnu-getopt/blobs/sha256:96d951b721c22830f976066f8704424bb065f1814fbd6d86fcd5f3996679db81",
              "sha256": "96d951b721c22830f976066f8704424bb065f1814fbd6d86fcd5f3996679db81"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gnu-getopt/blobs/sha256:7185fed500da9746d2249185f6fdbb93a7d08dd85661c5699c768004927e010e",
              "sha256": "7185fed500da9746d2249185f6fdbb93a7d08dd85661c5699c768004927e010e"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gnu-getopt/blobs/sha256:eee08bd48c1ad6adb71687db5599fe6d593769351d2cd5f9f1f2d485fc69c9b8",
              "sha256": "eee08bd48c1ad6adb71687db5599fe6d593769351d2cd5f9f1f2d485fc69c9b8"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gnu-getopt/blobs/sha256:4951cfe10db08f60f663b717a03a01be7a774ac717be30d19a2c36fdbb38c7ca",
              "sha256": "4951cfe10db08f60f663b717a03a01be7a774ac717be30d19a2c36fdbb38c7ca"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gnu-getopt/blobs/sha256:858025570517573d8254ee63717256cdfaea66def67cc0a5675a800deb0c674f",
              "sha256": "858025570517573d8254ee63717256cdfaea66def67cc0a5675a800deb0c674f"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gnu-getopt/blobs/sha256:44292ce4da02a035699014bc56f714825399406ab8e3b9b5480a9e293a90af2f",
              "sha256": "44292ce4da02a035699014bc56f714825399406ab8e3b9b5480a9e293a90af2f"
            }
          }
        }
      },
      "helm@2": {
        "version": "2.17.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:5758c325702f7f1e630e10a31075cc1a9a19ca047626fee6f3ad36775dbaca7d",
              "sha256": "5758c325702f7f1e630e10a31075cc1a9a19ca047626fee6f3ad36775dbaca7d"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:7372a593968befdd89f52a079360d4096be38df500199cec1de53b9d9a047502",
              "sha256": "7372a593968befdd89f52a079360d4096be38df500199cec1de53b9d9a047502"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:58b5f2ce65b8c15288e235dd8938e599a4762e1a98d25608dc91282f6761a924",
              "sha256": "58b5f2ce65b8c15288e235dd8938e599a4762e1a98d25608dc91282f6761a924"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:432e81bffefbb026bd50058e920a424b1805b84efc634d78c93dfedb9fec3d5a",
              "sha256": "432e81bffefbb026bd50058e920a424b1805b84efc634d78c93dfedb9fec3d5a"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:831c4f5b7cf7fc1ab53364eeb2eeb6eff8babdbc51817b406b65a948ac6258c2",
              "sha256": "831c4f5b7cf7fc1ab53364eeb2eeb6eff8babdbc51817b406b65a948ac6258c2"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:ab7ef44ce55c8b3597a2cb6dfe0ef93b74b389e6a4d6ab09c9a1ebe8dce5e594",
              "sha256": "ab7ef44ce55c8b3597a2cb6dfe0ef93b74b389e6a4d6ab09c9a1ebe8dce5e594"
            },
            "high_sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:a1c5cb86cce4fe2941c94309c8c75cd00ed9fae2e6edc6ea67aacadcf2f13c9e",
              "sha256": "a1c5cb86cce4fe2941c94309c8c75cd00ed9fae2e6edc6ea67aacadcf2f13c9e"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:718dfe0a0929ae4e4566954651c646ba6bab37dfd0a6ffac64740d0423461922",
              "sha256": "718dfe0a0929ae4e4566954651c646ba6bab37dfd0a6ffac64740d0423461922"
            }
          }
        }
      },
      "kubectl-bindrole": {
        "version": "1.5.1",
        "bottle": false
      },
      "ghc": {
        "version": "8.10.7_1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ghc/blobs/sha256:41e846a0479f930390ae2c65cf7ae0f3ea3755ff26df56822fb999722fb4932e",
              "sha256": "41e846a0479f930390ae2c65cf7ae0f3ea3755ff26df56822fb999722fb4932e"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ghc/blobs/sha256:7ddd8e8dabdb5654f167aa079ef9a1290e20aa151ce3580eed24042d95d47b57",
              "sha256": "7ddd8e8dabdb5654f167aa079ef9a1290e20aa151ce3580eed24042d95d47b57"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghc/blobs/sha256:c50034c3553a0f6099e2dfc3c7c33ca148256fedc8bc9be492cc942284bb473e",
              "sha256": "c50034c3553a0f6099e2dfc3c7c33ca148256fedc8bc9be492cc942284bb473e"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghc/blobs/sha256:68f447996de80ef0aa655b9b0f5cc048503a09366b17edf77b101f9c1a38fe0b",
              "sha256": "68f447996de80ef0aa655b9b0f5cc048503a09366b17edf77b101f9c1a38fe0b"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghc/blobs/sha256:14f6f4c4faa2ef0e4de7b225346c3b084de3356f069ac77eed05768046c70e28",
              "sha256": "14f6f4c4faa2ef0e4de7b225346c3b084de3356f069ac77eed05768046c70e28"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/ghc/blobs/sha256:bea0a8011b453e37e99855a6640642303d60c6611db366cb5f2d02a7546da19b",
              "sha256": "bea0a8011b453e37e99855a6640642303d60c6611db366cb5f2d02a7546da19b"
            }
          }
        }
      },
      "helmfile": {
        "version": "0.145.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helmfile/blobs/sha256:c849f7b5ac58bfec46b3d7d4ae7e563d1bc3438936284a706013863ecf6a5c1a",
              "sha256": "c849f7b5ac58bfec46b3d7d4ae7e563d1bc3438936284a706013863ecf6a5c1a"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helmfile/blobs/sha256:88aea82c5de6c0b52e3435dd36ea626a2ea2e48a594076613a77d2d88218568a",
              "sha256": "88aea82c5de6c0b52e3435dd36ea626a2ea2e48a594076613a77d2d88218568a"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helmfile/blobs/sha256:8fe0099d0269a14d69ae65ec117e271c2be70c1b2cef830f640b26de7f034cb6",
              "sha256": "8fe0099d0269a14d69ae65ec117e271c2be70c1b2cef830f640b26de7f034cb6"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helmfile/blobs/sha256:488f8ff7cfe9e04188227d00420811cb8a27736b5776f6015fb155407e9f4f27",
              "sha256": "488f8ff7cfe9e04188227d00420811cb8a27736b5776f6015fb155407e9f4f27"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helmfile/blobs/sha256:18f9235b703949d978a61c7793ed26af72a5a50558521f8dc468122664dd6699",
              "sha256": "18f9235b703949d978a61c7793ed26af72a5a50558521f8dc468122664dd6699"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helmfile/blobs/sha256:5c810f3faf3d0eaf82159872216775e51382b39436bd42d576d0516b0fd0fc24",
              "sha256": "5c810f3faf3d0eaf82159872216775e51382b39436bd42d576d0516b0fd0fc24"
            }
          }
        }
      },
      "go": {
        "version": "1.18.3",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/go/blobs/sha256:f9bfa7562421ece3c7bebe5eb2ea733286b33c009a2f24b932b82978b3e97446",
              "sha256": "f9bfa7562421ece3c7bebe5eb2ea733286b33c009a2f24b932b82978b3e97446"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/go/blobs/sha256:7b405fbace1164c8e28f98f4b005a5b853f033ff08b0da43a7f2e31c203a1d53",
              "sha256": "7b405fbace1164c8e28f98f4b005a5b853f033ff08b0da43a7f2e31c203a1d53"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/go/blobs/sha256:d99358b9ca6dadc9298ef1164d69fadd31ccbadd6fa21f2ddd71018164813395",
              "sha256": "d99358b9ca6dadc9298ef1164d69fadd31ccbadd6fa21f2ddd71018164813395"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/go/blobs/sha256:687d07f5cf904d7cdb83a9290e646677717a39c28e52de427d14518ab027339d",
              "sha256": "687d07f5cf904d7cdb83a9290e646677717a39c28e52de427d14518ab027339d"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/go/blobs/sha256:60038eabf8a61afc20dc9031124287b5faf99600613318645850db4b6757b5b4",
              "sha256": "60038eabf8a61afc20dc9031124287b5faf99600613318645850db4b6757b5b4"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/go/blobs/sha256:e1a92e8cb4f7fe7bdecaf8ec846b02915af1f0ba3329d1c7a4bf7d0981319fb5",
              "sha256": "e1a92e8cb4f7fe7bdecaf8ec846b02915af1f0ba3329d1c7a4bf7d0981319fb5"
            }
          }
        }
      },
      "ffmpeg": {
        "version": "5.0.1_3",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:6aa7fa8dbc5fb950f1ef81c31e5c3af52d92c616ea9a4b46e58b42c51a0ba7d7",
              "sha256": "6aa7fa8dbc5fb950f1ef81c31e5c3af52d92c616ea9a4b46e58b42c51a0ba7d7"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:a494fef2d5a93ecdadfce8530964af6ddcdb8662795bb7aa35ef8f8d8f659a01",
              "sha256": "a494fef2d5a93ecdadfce8530964af6ddcdb8662795bb7aa35ef8f8d8f659a01"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:b835b65ef6d4b85e36b7a315133fd9310a4ab6184caef6e8c99174d4aeec7bbb",
              "sha256": "b835b65ef6d4b85e36b7a315133fd9310a4ab6184caef6e8c99174d4aeec7bbb"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:a65289290fb40e981887568f2711357402f2e9e7e42f57e2c4d3984f11b36f7a",
              "sha256": "a65289290fb40e981887568f2711357402f2e9e7e42f57e2c4d3984f11b36f7a"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:d35f1a769b57ff7180076d53af7c1602ff7e3d3f29f81d6e5a6cb1a90cbc6a3a",
              "sha256": "d35f1a769b57ff7180076d53af7c1602ff7e3d3f29f81d6e5a6cb1a90cbc6a3a"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:d020ef50ab876425fa9d9555473b3925da14fe80365a7dc39f53e98e5b7960de",
              "sha256": "d020ef50ab876425fa9d9555473b3925da14fe80365a7dc39f53e98e5b7960de"
            }
          }
        }
      },
      "tektoncd/tools/tektoncd-cli": null,
      "istioctl": {
        "version": "1.14.1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/istioctl/blobs/sha256:bd6ad6cff5b01db19f2190995e1e2b34167b23908de2c1380107702d2a524e11",
              "sha256": "bd6ad6cff5b01db19f2190995e1e2b34167b23908de2c1380107702d2a524e11"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/istioctl/blobs/sha256:bd6ad6cff5b01db19f2190995e1e2b34167b23908de2c1380107702d2a524e11",
              "sha256": "bd6ad6cff5b01db19f2190995e1e2b34167b23908de2c1380107702d2a524e11"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/istioctl/blobs/sha256:ac46c14577dbcce6c0b378f78e8a8813ba0ac7ffcc01e1bb1c90e7c5fe0442ed",
              "sha256": "ac46c14577dbcce6c0b378f78e8a8813ba0ac7ffcc01e1bb1c90e7c5fe0442ed"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/istioctl/blobs/sha256:ac46c14577dbcce6c0b378f78e8a8813ba0ac7ffcc01e1bb1c90e7c5fe0442ed",
              "sha256": "ac46c14577dbcce6c0b378f78e8a8813ba0ac7ffcc01e1bb1c90e7c5fe0442ed"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/istioctl/blobs/sha256:ac46c14577dbcce6c0b378f78e8a8813ba0ac7ffcc01e1bb1c90e7c5fe0442ed",
              "sha256": "ac46c14577dbcce6c0b378f78e8a8813ba0ac7ffcc01e1bb1c90e7c5fe0442ed"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/istioctl/blobs/sha256:f1c40fb94cdb8b8076d8f1c54a4db0be6c3d0a7f5a6d30601e699178d2bc79a5",
              "sha256": "f1c40fb94cdb8b8076d8f1c54a4db0be6c3d0a7f5a6d30601e699178d2bc79a5"
            }
          }
        }
      },
      "aws-iam-authenticator": {
        "version": "0.5.9",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:12efc857905e148e434b541cc76801956f186ca92fb43ea88884303a1c36c175",
              "sha256": "12efc857905e148e434b541cc76801956f186ca92fb43ea88884303a1c36c175"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:ba09e1a04810d7fc4fe0156a231d6a28c507a39cd7579d2f8705c204d1611cde",
              "sha256": "ba09e1a04810d7fc4fe0156a231d6a28c507a39cd7579d2f8705c204d1611cde"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:091e33fd80229c5db17574795d5e44f9a54951e3fc2df24336c2cd449cd6e839",
              "sha256": "091e33fd80229c5db17574795d5e44f9a54951e3fc2df24336c2cd449cd6e839"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:bd2327738f22d7c95ee22b15915cad3ab850cc439f8684680ffe14c07c221d7f",
              "sha256": "bd2327738f22d7c95ee22b15915cad3ab850cc439f8684680ffe14c07c221d7f"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:0207f549dce4741625e3a93cad4ddcce8886a18eeb13ddbdf7d27530056877c0",
              "sha256": "0207f549dce4741625e3a93cad4ddcce8886a18eeb13ddbdf7d27530056877c0"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:c0b736f1703281ec4d24052cc3758ea3db9304a2099f272bd6dba12668f771f3",
              "sha256": "c0b736f1703281ec4d24052cc3758ea3db9304a2099f272bd6dba12668f771f3"
            }
          }
        }
      },
      "cloc": {
        "version": "1.94",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/cloc/blobs/sha256:775e39398333238ecc87c8ac33aaedf624015f0df21f20927b3cac4c5774724f",
              "sha256": "775e39398333238ecc87c8ac33aaedf624015f0df21f20927b3cac4c5774724f"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/cloc/blobs/sha256:8852c91261cd84c264fa2b9b0790cc17b330f34a005455dac5ff6566e2ffee9a",
              "sha256": "8852c91261cd84c264fa2b9b0790cc17b330f34a005455dac5ff6566e2ffee9a"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/cloc/blobs/sha256:a2db66239933ccb04153b6f08eeb99adb1685cdba4dde2facd1dc79a21d0355b",
              "sha256": "a2db66239933ccb04153b6f08eeb99adb1685cdba4dde2facd1dc79a21d0355b"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/cloc/blobs/sha256:23bc48be8f921dd9d56ad3ed978036c7b1e9234d048370c78c8b90a9dcf930c9",
              "sha256": "23bc48be8f921dd9d56ad3ed978036c7b1e9234d048370c78c8b90a9dcf930c9"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/cloc/blobs/sha256:20ed206034300efcd3f689ab32aff996e550305a5cf4182763214c9bbc1e618b",
              "sha256": "20ed206034300efcd3f689ab32aff996e550305a5cf4182763214c9bbc1e618b"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/cloc/blobs/sha256:e1b4c754ea79bc50d46a0ab59c69b11148ce2a4ba02f41f8f85953fec90ac905",
              "sha256": "e1b4c754ea79bc50d46a0ab59c69b11148ce2a4ba02f41f8f85953fec90ac905"
            }
          }
        }
      },
      "sonar-scanner": {
        "version": "4.7.0.2747",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "all": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/sonar-scanner/blobs/sha256:a1de3bfacf212710b3308cddc9ba286b2a80b7553fbc26340add77caa8335906",
              "sha256": "a1de3bfacf212710b3308cddc9ba286b2a80b7553fbc26340add77caa8335906"
            }
          }
        }
      },
      "yq": {
        "version": "4.25.3",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/yq/blobs/sha256:9a51f984484b886579eaa31e14ff0a67ab2c9b101d1f36b8abb382747e714616",
              "sha256": "9a51f984484b886579eaa31e14ff0a67ab2c9b101d1f36b8abb382747e714616"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/yq/blobs/sha256:4067010ce00450e8587c43c01a3d679f0d6bd73a9e8cf951bbdaf6cc883659a0",
              "sha256": "4067010ce00450e8587c43c01a3d679f0d6bd73a9e8cf951bbdaf6cc883659a0"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/yq/blobs/sha256:fa12ba91c1b54a0d8270a8bd8e4e36440bd8af32c44792ce8472c3812ba218f8",
              "sha256": "fa12ba91c1b54a0d8270a8bd8e4e36440bd8af32c44792ce8472c3812ba218f8"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/yq/blobs/sha256:afc311123a9b65fd521206344aaf73d479e67e0f5dfeeaa9ff891416218f2133",
              "sha256": "afc311123a9b65fd521206344aaf73d479e67e0f5dfeeaa9ff891416218f2133"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/yq/blobs/sha256:8ff4c3f2ee18f86707970f0f3afbf6c787733b11ffdf6a78aae927d387262030",
              "sha256": "8ff4c3f2ee18f86707970f0f3afbf6c787733b11ffdf6a78aae927d387262030"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/yq/blobs/sha256:46bd4282c6b951043a2c40cf38188b2af78f5fb8ce94fa2f916c0071f9eb5dfb",
              "sha256": "46bd4282c6b951043a2c40cf38188b2af78f5fb8ce94fa2f916c0071f9eb5dfb"
            }
          }
        }
      },
      "jenkins-x/jx/jx": null,
      "rustup-init": {
        "version": "1.24.3",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:f3e0c708bf0bc403fb5591b9f6991d709c68800ee230793cd587286c76c3711a",
              "sha256": "f3e0c708bf0bc403fb5591b9f6991d709c68800ee230793cd587286c76c3711a"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:d7de5aa4538303b308d1f136c475fdc83f8fa3b418da46a66cf8146a6f0d6ff2",
              "sha256": "d7de5aa4538303b308d1f136c475fdc83f8fa3b418da46a66cf8146a6f0d6ff2"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:588a4b849136c5a63094e24c348af1bc4c1d13f2a36d6b6e4d7287d49ed87385",
              "sha256": "588a4b849136c5a63094e24c348af1bc4c1d13f2a36d6b6e4d7287d49ed87385"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:d2bae6f97776cee5d796444ceb7c54f46e9dd56e51f9a1f439bbe7c842015572",
              "sha256": "d2bae6f97776cee5d796444ceb7c54f46e9dd56e51f9a1f439bbe7c842015572"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:7807b533709be5c92d7db4bd4189ae81ecf9f881544673591c7acb340d081b68",
              "sha256": "7807b533709be5c92d7db4bd4189ae81ecf9f881544673591c7acb340d081b68"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:681169de63d0e8a0dddbbe88388a64c4c15963e9c5b0dbf4029e1f2e75778667",
              "sha256": "681169de63d0e8a0dddbbe88388a64c4c15963e9c5b0dbf4029e1f2e75778667"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:5057bb4cf8c5c4e314358aad6790c1df9917a096baa010cf9f1de1eeb940f6ef",
              "sha256": "5057bb4cf8c5c4e314358aad6790c1df9917a096baa010cf9f1de1eeb940f6ef"
            }
          }
        }
      },
      "minikube": {
        "version": "1.26.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/minikube/blobs/sha256:89a6057043442a40fb27fcad58155ec715e58f99bf95d24f93f3277b1af0a839",
              "sha256": "89a6057043442a40fb27fcad58155ec715e58f99bf95d24f93f3277b1af0a839"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/minikube/blobs/sha256:c7520f937609fa3992b9ba52586becb84e3e5cade7fb756fed465543de989252",
              "sha256": "c7520f937609fa3992b9ba52586becb84e3e5cade7fb756fed465543de989252"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/minikube/blobs/sha256:56fb5f23b5eb1274ca16735577f1fcdbcaccc0dfd74b9dcdf1fe5f8e2f652fc3",
              "sha256": "56fb5f23b5eb1274ca16735577f1fcdbcaccc0dfd74b9dcdf1fe5f8e2f652fc3"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/minikube/blobs/sha256:b66300657406c63a025093a509f6b0aeb318d02508004ae3b4fc7faa6d0546b5",
              "sha256": "b66300657406c63a025093a509f6b0aeb318d02508004ae3b4fc7faa6d0546b5"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/minikube/blobs/sha256:21bf510d51d70b66c5d9b9fd94a99523bfc3c1cbf8c951c5ca6a75b10c008613",
              "sha256": "21bf510d51d70b66c5d9b9fd94a99523bfc3c1cbf8c951c5ca6a75b10c008613"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/minikube/blobs/sha256:a87c2b709bc4c74177f6f4e1afad72c8d4c0115b7a86a5cee13d480c14bc7f03",
              "sha256": "a87c2b709bc4c74177f6f4e1afad72c8d4c0115b7a86a5cee13d480c14bc7f03"
            }
          }
        }
      },
      "lsusb": {
        "version": "1.0",
        "bottle": {
          "rebuild": 1,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "all": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/lsusb/blobs/sha256:03895259bbcb43d072aacd4d000cb28807f5bff928bc8585663320beed5a7409",
              "sha256": "03895259bbcb43d072aacd4d000cb28807f5bff928bc8585663320beed5a7409"
            }
          }
        }
      },
      "mosquitto": {
        "version": "2.0.14",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mosquitto/blobs/sha256:92a59ffbdb47053e77f36675ef075449345dcea7bdc254526405aa31ed2d7a21",
              "sha256": "92a59ffbdb47053e77f36675ef075449345dcea7bdc254526405aa31ed2d7a21"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mosquitto/blobs/sha256:c40d4a17c9f8a52f326ecef721466e750aa81f273e2e5d98fa6c363de658a0fd",
              "sha256": "c40d4a17c9f8a52f326ecef721466e750aa81f273e2e5d98fa6c363de658a0fd"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mosquitto/blobs/sha256:0e314cf5f5a8740ea67a35d6ca060720b4f6d071fdf1343f797a0319ee88cbb2",
              "sha256": "0e314cf5f5a8740ea67a35d6ca060720b4f6d071fdf1343f797a0319ee88cbb2"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mosquitto/blobs/sha256:c77536fa79291ed18b741733ea4847883e60d53a651a89c034190f066d0eb377",
              "sha256": "c77536fa79291ed18b741733ea4847883e60d53a651a89c034190f066d0eb377"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mosquitto/blobs/sha256:164d07eb54f034a6dbd23d5ad347ead5154cb97741ac3c2e164f3f1d266837c0",
              "sha256": "164d07eb54f034a6dbd23d5ad347ead5154cb97741ac3c2e164f3f1d266837c0"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mosquitto/blobs/sha256:4c2327faf63358dcd1b16d6b759b3c5c8be40a704f3a3532c7d3dfde9991032d",
              "sha256": "4c2327faf63358dcd1b16d6b759b3c5c8be40a704f3a3532c7d3dfde9991032d"
            }
          }
        }
      },
      "rg": {
        "version": "13.0.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:ea67bdf39c1727b2b6b5b5f5110d1736b42b3eb0ec2068aa99903b670545b015",
              "sha256": "ea67bdf39c1727b2b6b5b5f5110d1736b42b3eb0ec2068aa99903b670545b015"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:d3e0ae859dc1e66ebecbc66a8ad1ec2abac59bc707d2305dde66212e71406d36",
              "sha256": "d3e0ae859dc1e66ebecbc66a8ad1ec2abac59bc707d2305dde66212e71406d36"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:db0260c6be9656c54575a4d82c720fb24141be38a17350d6cddba7be14f104e6",
              "sha256": "db0260c6be9656c54575a4d82c720fb24141be38a17350d6cddba7be14f104e6"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:a8f2bd6586de9f7aa36eaaefd36777309f9b5d57f01bf33bf022d715fd3dbb89",
              "sha256": "a8f2bd6586de9f7aa36eaaefd36777309f9b5d57f01bf33bf022d715fd3dbb89"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:0edcffa1251002e2747020d62a16ae077bd7aa5fb289d351622e0065c9686c40",
              "sha256": "0edcffa1251002e2747020d62a16ae077bd7aa5fb289d351622e0065c9686c40"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:b57024c0d221249a1f5eaef1069ac90d44e54afdadb146acd117ae23b7de98c6",
              "sha256": "b57024c0d221249a1f5eaef1069ac90d44e54afdadb146acd117ae23b7de98c6"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:34e3140b55f0fb5efb8db70e0709afe091632efaa84465e4c1c9ca3c8afa1bf2",
              "sha256": "34e3140b55f0fb5efb8db70e0709afe091632efaa84465e4c1c9ca3c8afa1bf2"
            }
          }
        }
      },
      "dfu-util": {
        "version": "0.11",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:7d09c40c797df76fdea2862b205111fa9c14d44b09c27a0b00e083fcc827bee9",
              "sha256": "7d09c40c797df76fdea2862b205111fa9c14d44b09c27a0b00e083fcc827bee9"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:c7dd53f422003b99c57f565aad8371e8cef1aa3de825f36cd927cd61ed64249d",
              "sha256": "c7dd53f422003b99c57f565aad8371e8cef1aa3de825f36cd927cd61ed64249d"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:5daf11ce553e067f293fc615889d22c74abb9ea9da21f57699c81d65ee9fa089",
              "sha256": "5daf11ce553e067f293fc615889d22c74abb9ea9da21f57699c81d65ee9fa089"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:b970a649e90f3e080af2143e8479e0616959e35650defea16b96288c4af011dc",
              "sha256": "b970a649e90f3e080af2143e8479e0616959e35650defea16b96288c4af011dc"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:5a5d86794a00b9559ffc819715c297da4f477296d20a92c804aefc426795d0b0",
              "sha256": "5a5d86794a00b9559ffc819715c297da4f477296d20a92c804aefc426795d0b0"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:1ded847895f4d2a86a4a7754fa711014d09c334044ccc03aa97d89059ae58604",
              "sha256": "1ded847895f4d2a86a4a7754fa711014d09c334044ccc03aa97d89059ae58604"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:13c26d1ebc67dd60446845d51e3ff92bcded0ae223852dc104e897c8c3423f71",
              "sha256": "13c26d1ebc67dd60446845d51e3ff92bcded0ae223852dc104e897c8c3423f71"
            }
          }
        }
      },
      "stlink": {
        "version": "1.7.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:2ea4763e208c5566d0ec1848a6d91c440fe745287aa7a5617af635fea7707af0",
              "sha256": "2ea4763e208c5566d0ec1848a6d91c440fe745287aa7a5617af635fea7707af0"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:79683924dac821a1744cf32a96c3296eecd1668b5f2f64dbdcf570f32480459f",
              "sha256": "79683924dac821a1744cf32a96c3296eecd1668b5f2f64dbdcf570f32480459f"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:32411be4437ac85b5b9feb0fc38306af2dfc1f895ad4661c2187eb70a8420b0f",
              "sha256": "32411be4437ac85b5b9feb0fc38306af2dfc1f895ad4661c2187eb70a8420b0f"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:9ea7be4ae1c0b91ceeb40c6df9d07ad6a5660be80043895bcf29acc47988d10d",
              "sha256": "9ea7be4ae1c0b91ceeb40c6df9d07ad6a5660be80043895bcf29acc47988d10d"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:e162fb37d4a7e2a0e006c5cb9beae3b86784d6a0b3d371fc33d7ed9ba2140083",
              "sha256": "e162fb37d4a7e2a0e006c5cb9beae3b86784d6a0b3d371fc33d7ed9ba2140083"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:f112f45203b8c460da03ae840529d4564a677d0621ac0a9576bac510258a9ef5",
              "sha256": "f112f45203b8c460da03ae840529d4564a677d0621ac0a9576bac510258a9ef5"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:141e0873ed4745b1224f6996f5dac5461f27a87e17d36a9f56a080f27a922f23",
              "sha256": "141e0873ed4745b1224f6996f5dac5461f27a87e17d36a9f56a080f27a922f23"
            }
          }
        }
      },
      "ansible@2.9": {
        "version": "2.9.21",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/2.9/blobs/sha256:3198997b5e28c55a3316ee33d37c3fee7598a95438323e266f3725efa33cc071",
              "sha256": "3198997b5e28c55a3316ee33d37c3fee7598a95438323e266f3725efa33cc071"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/2.9/blobs/sha256:eb288d9cf23fdaf1959854b07f677fd58965521a5da05e788521047bec8442a3",
              "sha256": "eb288d9cf23fdaf1959854b07f677fd58965521a5da05e788521047bec8442a3"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/2.9/blobs/sha256:32c4d5c641bb8df8cb1fc8ba922511ba0ab2f0d0ce1fdb13ca1b221879bae001",
              "sha256": "32c4d5c641bb8df8cb1fc8ba922511ba0ab2f0d0ce1fdb13ca1b221879bae001"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/2.9/blobs/sha256:30701024ebd7cdcafe5b95fe47cdc6f2d5e3250c6797c18120a16804b69f86bc",
              "sha256": "30701024ebd7cdcafe5b95fe47cdc6f2d5e3250c6797c18120a16804b69f86bc"
            }
          }
        }
      },
      "goreleaser": {
        "version": "1.10.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/goreleaser/blobs/sha256:cea8d3ef6558a44e6636310a41fab852a6ca178705eee5c47417a2853f305115",
              "sha256": "cea8d3ef6558a44e6636310a41fab852a6ca178705eee5c47417a2853f305115"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/goreleaser/blobs/sha256:6fde47077d5bdcf1625101b0219dab59ca4cdbcb7e7c610f970fd59df983415b",
              "sha256": "6fde47077d5bdcf1625101b0219dab59ca4cdbcb7e7c610f970fd59df983415b"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/goreleaser/blobs/sha256:37542f02b46dc779cc34c8e42a6c0c92563c260cf8e228661ffb9a07b66e2526",
              "sha256": "37542f02b46dc779cc34c8e42a6c0c92563c260cf8e228661ffb9a07b66e2526"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/goreleaser/blobs/sha256:e45920925805d6fd4801fd0b744c0afb81cdda5c06159e3e4b4c2f96c879b875",
              "sha256": "e45920925805d6fd4801fd0b744c0afb81cdda5c06159e3e4b4c2f96c879b875"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/goreleaser/blobs/sha256:a8a4a6adc1659c9c4839036bb04ff11e6795ca1d29a3f490eb67579077a192f3",
              "sha256": "a8a4a6adc1659c9c4839036bb04ff11e6795ca1d29a3f490eb67579077a192f3"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/goreleaser/blobs/sha256:d854d222806ba3c1df82c7423614a8bc66ffd8416eafc699f47cc554979a19f2",
              "sha256": "d854d222806ba3c1df82c7423614a8bc66ffd8416eafc699f47cc554979a19f2"
            }
          }
        }
      },
      "saml2aws": {
        "version": "2.27.1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/saml2aws/blobs/sha256:bc0d07e8e562ed01867d7aa6b45ce8e649ed57e8f52901b07a484522dd0907a5",
              "sha256": "bc0d07e8e562ed01867d7aa6b45ce8e649ed57e8f52901b07a484522dd0907a5"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/saml2aws/blobs/sha256:e125377435cd04be0bb899dfac6eba0dabf81f9db56616d470edef13b8aee827",
              "sha256": "e125377435cd04be0bb899dfac6eba0dabf81f9db56616d470edef13b8aee827"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/saml2aws/blobs/sha256:64f7ee72cb928b92eb60e40f9b69edc8a512952d78bd2032aa2ca836ca068338",
              "sha256": "64f7ee72cb928b92eb60e40f9b69edc8a512952d78bd2032aa2ca836ca068338"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/saml2aws/blobs/sha256:3735e63468969541e96471826840199e3d8ba1cca111f60b46f2af6740264a40",
              "sha256": "3735e63468969541e96471826840199e3d8ba1cca111f60b46f2af6740264a40"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/saml2aws/blobs/sha256:b4447086e1ee2004ae04ebec7617803607bc432233cabc4c969d674acc232a11",
              "sha256": "b4447086e1ee2004ae04ebec7617803607bc432233cabc4c969d674acc232a11"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/saml2aws/blobs/sha256:190d240745c077bf22c83c8b53019f85f02f6387995d1f5b7db98397303a1c59",
              "sha256": "190d240745c077bf22c83c8b53019f85f02f6387995d1f5b7db98397303a1c59"
            }
          }
        }
      },
      "terminal-notifier": {
        "version": "2.0.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:c9862b6cf8d3b299ef67dcfb6e31d3040670bdfe58110d04797b117b3702de42",
              "sha256": "c9862b6cf8d3b299ef67dcfb6e31d3040670bdfe58110d04797b117b3702de42"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:d1268e236f13f5bb4cd5fead9cf54cfb54ceefb98e34861bd39cf3c7e6ef34cf",
              "sha256": "d1268e236f13f5bb4cd5fead9cf54cfb54ceefb98e34861bd39cf3c7e6ef34cf"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:6513db788b33570b1b89d2b0215e3176d629814b3233c993e995ec9806ad32df",
              "sha256": "6513db788b33570b1b89d2b0215e3176d629814b3233c993e995ec9806ad32df"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:91f14694ebce08887492aa75138753cd9ff74977868927b15b52559728280055",
              "sha256": "91f14694ebce08887492aa75138753cd9ff74977868927b15b52559728280055"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:78eff95b7436480521ee68a8581ff2df0c615adefccd279486f2491f1b1c0a4b",
              "sha256": "78eff95b7436480521ee68a8581ff2df0c615adefccd279486f2491f1b1c0a4b"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:9671c602326357b7397248bfb0cf062bc47f19add15b615e512f58545c387c31",
              "sha256": "9671c602326357b7397248bfb0cf062bc47f19add15b615e512f58545c387c31"
            },
            "high_sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:f112656234f4100d23cc1a41b96f92a09974360a822c2ec0fb6f9970862c1a22",
              "sha256": "f112656234f4100d23cc1a41b96f92a09974360a822c2ec0fb6f9970862c1a22"
            },
            "sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:210cd525fad70bbaef40f092bc3478b1519f68f73c034990230d8b1cc61a8a7c",
              "sha256": "210cd525fad70bbaef40f092bc3478b1519f68f73c034990230d8b1cc61a8a7c"
            },
            "el_capitan": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:75ce68fd95fb502e20ccb25be72f7db12112ac1a4bdf5a70c140cd174ecbacf5",
              "sha256": "75ce68fd95fb502e20ccb25be72f7db12112ac1a4bdf5a70c140cd174ecbacf5"
            }
          }
        }
      },
      "trash": {
        "version": "0.9.2",
        "bottle": {
          "rebuild": 1,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:541af91d1cb128aa743460a529a3dcab5bac63b61ccde0a60d73aee23ab7d5c0",
              "sha256": "541af91d1cb128aa743460a529a3dcab5bac63b61ccde0a60d73aee23ab7d5c0"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:11c0c85ec692ea6d4a125070f0a6ca576aff991608a6c9632b984cbf983e2481",
              "sha256": "11c0c85ec692ea6d4a125070f0a6ca576aff991608a6c9632b984cbf983e2481"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:09b8ac7ade28ca59bd578b90680ece838a507b90b35e44d06a16f4d8ab9ae6e6",
              "sha256": "09b8ac7ade28ca59bd578b90680ece838a507b90b35e44d06a16f4d8ab9ae6e6"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:403ba52ce97d38535e1d127ca227afd4ea2d0e0c8b414118dbc5376c9ed8f094",
              "sha256": "403ba52ce97d38535e1d127ca227afd4ea2d0e0c8b414118dbc5376c9ed8f094"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:b452d67cdeeb52db0aaadd258bc3e214a5ea5ed37da698b45017b01457115ea6",
              "sha256": "b452d67cdeeb52db0aaadd258bc3e214a5ea5ed37da698b45017b01457115ea6"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:d8ad5460b24a51a4a12b31ebf1a2887e9e86e029d061f6994c3c1caea7bf0551",
              "sha256": "d8ad5460b24a51a4a12b31ebf1a2887e9e86e029d061f6994c3c1caea7bf0551"
            },
            "high_sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:0ef5ea924ba8d01398686657a839ad270796f3f10eee86d6522980d32038df9a",
              "sha256": "0ef5ea924ba8d01398686657a839ad270796f3f10eee86d6522980d32038df9a"
            }
          }
        }
      },
      "dos2unix": {
        "version": "7.4.3",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:99e6489bf197a6708e23fe54c6a3dd01c9faf91807aad90a21a4a19ba0b7a7fb",
              "sha256": "99e6489bf197a6708e23fe54c6a3dd01c9faf91807aad90a21a4a19ba0b7a7fb"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:5422ac9cfe1635baa4032ff17a4bc1d8e1e991f988164376e0a706851c6c5b99",
              "sha256": "5422ac9cfe1635baa4032ff17a4bc1d8e1e991f988164376e0a706851c6c5b99"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:7eb1a12fcb8ba89fcdaae8fe3b82cd9cb068d7edf7b966fabf80f0428476c329",
              "sha256": "7eb1a12fcb8ba89fcdaae8fe3b82cd9cb068d7edf7b966fabf80f0428476c329"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:ecb0a8cfd9b346462640ab20b4f07aa8d2e8f10ce55c9f0539b0039d4979cb54",
              "sha256": "ecb0a8cfd9b346462640ab20b4f07aa8d2e8f10ce55c9f0539b0039d4979cb54"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:c1b511a509a5779a767a864b6d9ae26bbe9528dc2271726cc0e000071028a700",
              "sha256": "c1b511a509a5779a767a864b6d9ae26bbe9528dc2271726cc0e000071028a700"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:a6536d3129b4d80da09c431a0ccafb48cfde1acb9896a78b11daca84a8b296b5",
              "sha256": "a6536d3129b4d80da09c431a0ccafb48cfde1acb9896a78b11daca84a8b296b5"
            }
          }
        }
      },
      "gh": {
        "version": "2.13.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:e74682023de43e8cbd2a6497968fbbceff7a52f948e379a775d63ee6b2ab134a",
              "sha256": "e74682023de43e8cbd2a6497968fbbceff7a52f948e379a775d63ee6b2ab134a"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:97d16ce248d6b36bd03b9c6e95b8258806de92e8d710a7ab19a03fd920a03bdf",
              "sha256": "97d16ce248d6b36bd03b9c6e95b8258806de92e8d710a7ab19a03fd920a03bdf"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:c274d927b2358909c696468880ecfa6e6e16cb556f40180560cc376e3d8e28e6",
              "sha256": "c274d927b2358909c696468880ecfa6e6e16cb556f40180560cc376e3d8e28e6"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:6678af620c31d59bda08fd11e88560e78fabf118df9bac29be7e8556aa05ad3b",
              "sha256": "6678af620c31d59bda08fd11e88560e78fabf118df9bac29be7e8556aa05ad3b"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:8a79d795e849befa45bdaf5cd227532af5bb77063c15d4dab849feee3b60b544",
              "sha256": "8a79d795e849befa45bdaf5cd227532af5bb77063c15d4dab849feee3b60b544"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:fd4a9ed8086815a5f6a0f80f51dde3f084fba83bc93743859469b1280d37d29c",
              "sha256": "fd4a9ed8086815a5f6a0f80f51dde3f084fba83bc93743859469b1280d37d29c"
            }
          }
        }
      },
      "krb5": {
        "version": "1.20",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:ad559a03cc8661b668d51d71d3dc44b84eb853b35415aa0cc0a75fefc15bfeb6",
              "sha256": "ad559a03cc8661b668d51d71d3dc44b84eb853b35415aa0cc0a75fefc15bfeb6"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:8f6f51da9bf8693e7976954aee19d444d483070cf33ad6453219f032b1bcd1ec",
              "sha256": "8f6f51da9bf8693e7976954aee19d444d483070cf33ad6453219f032b1bcd1ec"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:99e8f567b0f70cc50309acf37f5e4b792dcd8fbd034e869e58e3e0f38ad73ec9",
              "sha256": "99e8f567b0f70cc50309acf37f5e4b792dcd8fbd034e869e58e3e0f38ad73ec9"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:8e6be25060a0223ec6e8935e575d4b07ff9235f3b5c7e273bd8c79b401a0abfc",
              "sha256": "8e6be25060a0223ec6e8935e575d4b07ff9235f3b5c7e273bd8c79b401a0abfc"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:6e8e5a00dff92c729f276ba9d287689e0222a4293f7c8c502ee2781c2a1d4a2e",
              "sha256": "6e8e5a00dff92c729f276ba9d287689e0222a4293f7c8c502ee2781c2a1d4a2e"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:17c3f6518fc7f836cd1bcc8ae0f2d8a8cc9d8ca063fa78d2faaf67158bf3318d",
              "sha256": "17c3f6518fc7f836cd1bcc8ae0f2d8a8cc9d8ca063fa78d2faaf67158bf3318d"
            }
          }
        }
      },
      "tfswitch": {
        "version": "0.13.1288",
        "bottle": false
      },
      "git-gui": {
        "version": "2.37.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "all": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-gui/blobs/sha256:5f613050d5ef355e821d57bb6762c8f99c95ef48297a7ef66ff97f22bd808a8e",
              "sha256": "5f613050d5ef355e821d57bb6762c8f99c95ef48297a7ef66ff97f22bd808a8e"
            }
          }
        }
      },
      "git-lfs": {
        "version": "3.2.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-lfs/blobs/sha256:a81d5b29d1c0203f592e8af7b25ccb95431489ffa8dc595dbb1c39f1c08cfb46",
              "sha256": "a81d5b29d1c0203f592e8af7b25ccb95431489ffa8dc595dbb1c39f1c08cfb46"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-lfs/blobs/sha256:f10c03ed48c4168d8b80164d053040452e772c978344cc485e386183de7d5c24",
              "sha256": "f10c03ed48c4168d8b80164d053040452e772c978344cc485e386183de7d5c24"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-lfs/blobs/sha256:2ccd239da97286fa2f9702f7c2731202819a6012163906b7e599e8fb218a6c95",
              "sha256": "2ccd239da97286fa2f9702f7c2731202819a6012163906b7e599e8fb218a6c95"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-lfs/blobs/sha256:21c75c877159acff82ada003baa3ea7d65e2774a2636f740e4cfad4ae9d2d7b5",
              "sha256": "21c75c877159acff82ada003baa3ea7d65e2774a2636f740e4cfad4ae9d2d7b5"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-lfs/blobs/sha256:c428d687c3a70defa9178fd0b287cd8766f05bf113eb6ae8ce7bcb7940751b05",
              "sha256": "c428d687c3a70defa9178fd0b287cd8766f05bf113eb6ae8ce7bcb7940751b05"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-lfs/blobs/sha256:43e16ee02644936dbf6d2d504b8c66cd3e0c3dd1313436e9bd253c4c051e437c",
              "sha256": "43e16ee02644936dbf6d2d504b8c66cd3e0c3dd1313436e9bd253c4c051e437c"
            }
          }
        }
      },
      "golangci-lint": {
        "version": "1.46.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/golangci-lint/blobs/sha256:ea0e1168417d037638587997c39961604f5352bea09b6bf126c9f97084176ee7",
              "sha256": "ea0e1168417d037638587997c39961604f5352bea09b6bf126c9f97084176ee7"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/golangci-lint/blobs/sha256:fa8f329176d1ef12ed671861bf73cb2069c5d43438b3a38221f801a626e99357",
              "sha256": "fa8f329176d1ef12ed671861bf73cb2069c5d43438b3a38221f801a626e99357"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/golangci-lint/blobs/sha256:c4b73e64134fe32852f1455759785e7f3391775bcc4ecff5f887de18e1a6fbe2",
              "sha256": "c4b73e64134fe32852f1455759785e7f3391775bcc4ecff5f887de18e1a6fbe2"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/golangci-lint/blobs/sha256:bcbdac8340a0a1d4519ef5303896b748c70a2c3cf086315f5b6e53e79020a23a",
              "sha256": "bcbdac8340a0a1d4519ef5303896b748c70a2c3cf086315f5b6e53e79020a23a"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/golangci-lint/blobs/sha256:39c2acbab5b65ea37fc9a0dee059aac3fef5c9182ec3d1d600f105932ca598ee",
              "sha256": "39c2acbab5b65ea37fc9a0dee059aac3fef5c9182ec3d1d600f105932ca598ee"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/golangci-lint/blobs/sha256:271f4e9d87905e6106a57f277e90ae4048b361ee3c621de55c7d633951043112",
              "sha256": "271f4e9d87905e6106a57f277e90ae4048b361ee3c621de55c7d633951043112"
            }
          }
        }
      },
      "portaudio": {
        "version": "19.7.0",
        "bottle": {
          "rebuild": 1,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:8f390bc5ee1fffa1191df48e2947acafd5063abdc713c595760f3ac6a7a8ebd6",
              "sha256": "8f390bc5ee1fffa1191df48e2947acafd5063abdc713c595760f3ac6a7a8ebd6"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:3daf7c4d5a1b948b2564de026336e3f3496f693ea0743e42b50f78d09ee32469",
              "sha256": "3daf7c4d5a1b948b2564de026336e3f3496f693ea0743e42b50f78d09ee32469"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:69daed6f99f96edb350f06043d5d7121bb0d3eaa88e64ef5bac247f300d552e9",
              "sha256": "69daed6f99f96edb350f06043d5d7121bb0d3eaa88e64ef5bac247f300d552e9"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:f67d3a167142d0afa6ef446260075a7e1c29cf3d1246a95bac2f12732004398a",
              "sha256": "f67d3a167142d0afa6ef446260075a7e1c29cf3d1246a95bac2f12732004398a"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:9b0934f5a868dc0c3874ae6491d685cff6537923cc49d6abea18c1bf59cddaea",
              "sha256": "9b0934f5a868dc0c3874ae6491d685cff6537923cc49d6abea18c1bf59cddaea"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:e69bcb7966fae64dabb4866a9f791437b59ef1991112b2a6fb31ee94a76b9244",
              "sha256": "e69bcb7966fae64dabb4866a9f791437b59ef1991112b2a6fb31ee94a76b9244"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:01048cd3e5c934f5fb7b7cd11430833c69022a621fcc2d868159e07bbef1e3e4",
              "sha256": "01048cd3e5c934f5fb7b7cd11430833c69022a621fcc2d868159e07bbef1e3e4"
            }
          }
        }
      },
      "python@3.8": {
        "version": "3.8.13_1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:3045dc34ad02cc055e9a93de411978c70280555c0db7732955a01a3c903ff068",
              "sha256": "3045dc34ad02cc055e9a93de411978c70280555c0db7732955a01a3c903ff068"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:12f56aefd178f9cc59cf6db2756d858bd6e9a6a9a85b04a73dcf8eac8b43fe78",
              "sha256": "12f56aefd178f9cc59cf6db2756d858bd6e9a6a9a85b04a73dcf8eac8b43fe78"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:7644a4ae346bd2acec76dcb1d64e5f6e14cb168385f5cd95006921aa34476203",
              "sha256": "7644a4ae346bd2acec76dcb1d64e5f6e14cb168385f5cd95006921aa34476203"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:da3bf154f2c086b9024bcdd1a45e3039623ab9835cc383fe9773673da04d4d74",
              "sha256": "da3bf154f2c086b9024bcdd1a45e3039623ab9835cc383fe9773673da04d4d74"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:313b54d749b6c28adcf05f2e5088c634d427a4fbf2c83d6d1ff095e786aadf01",
              "sha256": "313b54d749b6c28adcf05f2e5088c634d427a4fbf2c83d6d1ff095e786aadf01"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:c26a5a85a559d74b14c7304bb9772fd2df7751137914f8d3fbc36a6cdd8ddb00",
              "sha256": "c26a5a85a559d74b14c7304bb9772fd2df7751137914f8d3fbc36a6cdd8ddb00"
            }
          }
        }
      },
      "teensy_loader_cli": {
        "version": "2.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:a534e52c0de21164168c188ae60e929a17e183be3eba10ee7f4a1394c6bb94c6",
              "sha256": "a534e52c0de21164168c188ae60e929a17e183be3eba10ee7f4a1394c6bb94c6"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:06529ad4373a483829c4b7ffd9bcb262077e7242be60c4a8645601ccc4aea134",
              "sha256": "06529ad4373a483829c4b7ffd9bcb262077e7242be60c4a8645601ccc4aea134"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:0239cc41b148dea13c918f858930cca2631db5547e5aa17db57c9c5efdcdd2fe",
              "sha256": "0239cc41b148dea13c918f858930cca2631db5547e5aa17db57c9c5efdcdd2fe"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:1077e947102d333896796ada9f702fb11bfc43741b0ffe737292479624249ced",
              "sha256": "1077e947102d333896796ada9f702fb11bfc43741b0ffe737292479624249ced"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:5f622de032367bbd7d3325e1e3d88ee205f941908a111102cbb10d176474e197",
              "sha256": "5f622de032367bbd7d3325e1e3d88ee205f941908a111102cbb10d176474e197"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:a3e61b76878c12cea8fbce6abbfcd7c2e26afbf79785fda38135009ae1d08f1f",
              "sha256": "a3e61b76878c12cea8fbce6abbfcd7c2e26afbf79785fda38135009ae1d08f1f"
            }
          }
        }
      },
      "autoconf": {
        "version": "2.71",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:a3d366c98b0da7a0a4f352eef49af9d612ac7aea4ffe420d49ff12bd90007415",
              "sha256": "a3d366c98b0da7a0a4f352eef49af9d612ac7aea4ffe420d49ff12bd90007415"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:6279cc6294da77a87b2e08783f39a97e8678bde9b3e2899685879cabee6d2945",
              "sha256": "6279cc6294da77a87b2e08783f39a97e8678bde9b3e2899685879cabee6d2945"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:de8f4aa4123d307ad8bb11b1c685538224dc39939085fd00af928c5099c4202d",
              "sha256": "de8f4aa4123d307ad8bb11b1c685538224dc39939085fd00af928c5099c4202d"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:0aa64f171bac19ce6ac0c0ca697f30658db78cf175550dfde3dbda907b7f2500",
              "sha256": "0aa64f171bac19ce6ac0c0ca697f30658db78cf175550dfde3dbda907b7f2500"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:258a94bef23057c52818adf64d682af20bc6e09b46eac135047e2b87fc8206c7",
              "sha256": "258a94bef23057c52818adf64d682af20bc6e09b46eac135047e2b87fc8206c7"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:e94578bf4b4832baef1c9bbb40cb4da5fdbd9c66be5ed8d070f78be5f0cca618",
              "sha256": "e94578bf4b4832baef1c9bbb40cb4da5fdbd9c66be5ed8d070f78be5f0cca618"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:9f9a73292e64f19ec504459ee7f8b7f11f1e472d18252499705a9fc289c43f85",
              "sha256": "9f9a73292e64f19ec504459ee7f8b7f11f1e472d18252499705a9fc289c43f85"
            }
          }
        }
      },
      "automake": {
        "version": "1.16.5",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/automake/blobs/sha256:f68481d06be7fa3f0a0881edb825a336e7f6548191c762d68bd817183b238f5a",
              "sha256": "f68481d06be7fa3f0a0881edb825a336e7f6548191c762d68bd817183b238f5a"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/automake/blobs/sha256:f68481d06be7fa3f0a0881edb825a336e7f6548191c762d68bd817183b238f5a",
              "sha256": "f68481d06be7fa3f0a0881edb825a336e7f6548191c762d68bd817183b238f5a"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/automake/blobs/sha256:ae77a247a13ea860236a29b02769f5327395f712413f694d8a8d20cb6c21332d",
              "sha256": "ae77a247a13ea860236a29b02769f5327395f712413f694d8a8d20cb6c21332d"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/automake/blobs/sha256:ae77a247a13ea860236a29b02769f5327395f712413f694d8a8d20cb6c21332d",
              "sha256": "ae77a247a13ea860236a29b02769f5327395f712413f694d8a8d20cb6c21332d"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/automake/blobs/sha256:ae77a247a13ea860236a29b02769f5327395f712413f694d8a8d20cb6c21332d",
              "sha256": "ae77a247a13ea860236a29b02769f5327395f712413f694d8a8d20cb6c21332d"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/automake/blobs/sha256:ae77a247a13ea860236a29b02769f5327395f712413f694d8a8d20cb6c21332d",
              "sha256": "ae77a247a13ea860236a29b02769f5327395f712413f694d8a8d20cb6c21332d"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/automake/blobs/sha256:59808c20f7dc565f106b432941b43c52f3d7f46a8d562ab27a4aabd424783158",
              "sha256": "59808c20f7dc565f106b432941b43c52f3d7f46a8d562ab27a4aabd424783158"
            }
          }
        }
      },
      "bash": {
        "version": "5.1.16",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/bash/blobs/sha256:1b8834e7c9d1cd89f0cb4514e53ce905f6385c9455fd507298f73b3aa3e55087",
              "sha256": "1b8834e7c9d1cd89f0cb4514e53ce905f6385c9455fd507298f73b3aa3e55087"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/bash/blobs/sha256:6954457b4e588e24fb339b407839a9b6c651738175a84adc75bbc525db032ece",
              "sha256": "6954457b4e588e24fb339b407839a9b6c651738175a84adc75bbc525db032ece"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/bash/blobs/sha256:2823a6b24dc60b14b692cfc0544753e7d01a5c1f94eb1bdd590f9cb490eb1729",
              "sha256": "2823a6b24dc60b14b692cfc0544753e7d01a5c1f94eb1bdd590f9cb490eb1729"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/bash/blobs/sha256:4f387cc0993f868f31cd76483051a58420f80f57cf4626afc4b881d2a98959bb",
              "sha256": "4f387cc0993f868f31cd76483051a58420f80f57cf4626afc4b881d2a98959bb"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/bash/blobs/sha256:85ac02733b659f4a7884395ed2cfd7dbdf59999a0d8a434a0c1a75085009ce2a",
              "sha256": "85ac02733b659f4a7884395ed2cfd7dbdf59999a0d8a434a0c1a75085009ce2a"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/bash/blobs/sha256:41849dc2ac9388255aaed32879cb32f977b9730220981eeca32bffca0b3bfb5f",
              "sha256": "41849dc2ac9388255aaed32879cb32f977b9730220981eeca32bffca0b3bfb5f"
            }
          }
        }
      },
      "crosstool-ng": {
        "version": "1.25.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/crosstool-ng/blobs/sha256:3ed8b07aa9c0250edf408d7fd4dc79c02b7cd40a847730f4bd9eb152779d6385",
              "sha256": "3ed8b07aa9c0250edf408d7fd4dc79c02b7cd40a847730f4bd9eb152779d6385"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/crosstool-ng/blobs/sha256:652c574f396d1be709de7ac74bc39943d173a9a69992004e0c1f84c0694a4347",
              "sha256": "652c574f396d1be709de7ac74bc39943d173a9a69992004e0c1f84c0694a4347"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/crosstool-ng/blobs/sha256:fc72ddfe1f31d0de37248f49686ddc6ef4caef94c0574367c0fae00cf65189f0",
              "sha256": "fc72ddfe1f31d0de37248f49686ddc6ef4caef94c0574367c0fae00cf65189f0"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/crosstool-ng/blobs/sha256:be3beb87b1beabdf57468e41cb7604fd22b3623c27e2d027af02a68dc1a78b7f",
              "sha256": "be3beb87b1beabdf57468e41cb7604fd22b3623c27e2d027af02a68dc1a78b7f"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/crosstool-ng/blobs/sha256:4b0bb05c4f7770ebe17085b4e34c45125989daa01e734ef6fc1d9269e0e6eb38",
              "sha256": "4b0bb05c4f7770ebe17085b4e34c45125989daa01e734ef6fc1d9269e0e6eb38"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/crosstool-ng/blobs/sha256:625bd9d390262a14b5c2b3c0fd316d9832ac2b6f910f06a22a69dd90e131b1f3",
              "sha256": "625bd9d390262a14b5c2b3c0fd316d9832ac2b6f910f06a22a69dd90e131b1f3"
            }
          }
        }
      },
      "llvm": {
        "version": "14.0.6",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/llvm/blobs/sha256:6a48ea04dd8570053cc414e50e3c1da550209deef820d948fe62e01dd8583bbc",
              "sha256": "6a48ea04dd8570053cc414e50e3c1da550209deef820d948fe62e01dd8583bbc"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/llvm/blobs/sha256:4a9976dbfe8cacad5f82705811d174236c1090ca3ecf3b9b84abdb25143e03be",
              "sha256": "4a9976dbfe8cacad5f82705811d174236c1090ca3ecf3b9b84abdb25143e03be"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/llvm/blobs/sha256:9ea4a05144ec94712cda520f0daa47610b350e43e0185aa7027dc1f1ad690d0b",
              "sha256": "9ea4a05144ec94712cda520f0daa47610b350e43e0185aa7027dc1f1ad690d0b"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/llvm/blobs/sha256:b0341e32eda6ad5f8a5434d3ea7521a763ac143b8673172a69516d090a7144d7",
              "sha256": "b0341e32eda6ad5f8a5434d3ea7521a763ac143b8673172a69516d090a7144d7"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/llvm/blobs/sha256:ef6eebff967ed2801f67244f37b1c9408ba60e66d6f579d0af9b463c7ca2629b",
              "sha256": "ef6eebff967ed2801f67244f37b1c9408ba60e66d6f579d0af9b463c7ca2629b"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/llvm/blobs/sha256:890fe7ec6b307a57cf08ffe6577b44682b9859f853227505c2f2496ee18bf301",
              "sha256": "890fe7ec6b307a57cf08ffe6577b44682b9859f853227505c2f2496ee18bf301"
            }
          }
        }
      },
      "m4": {
        "version": "1.4.19",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/m4/blobs/sha256:8e9fa0d7d946f7c38e1a6f596aab3169d2440fccd34ec321b9a032d903ec951c",
              "sha256": "8e9fa0d7d946f7c38e1a6f596aab3169d2440fccd34ec321b9a032d903ec951c"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/m4/blobs/sha256:ea1be04e51645f9e31c8d2cab6d144bb7f47efb1f35214b9f1014e27db5a3bc1",
              "sha256": "ea1be04e51645f9e31c8d2cab6d144bb7f47efb1f35214b9f1014e27db5a3bc1"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/m4/blobs/sha256:8a17c921e5135206c382fc67ae53ba8835684dac5bfe7eb2bcdfa79df4d2731d",
              "sha256": "8a17c921e5135206c382fc67ae53ba8835684dac5bfe7eb2bcdfa79df4d2731d"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/m4/blobs/sha256:b22472f659112cf12163bba770d891618b3ada5aaf5baa01516d80fef6214617",
              "sha256": "b22472f659112cf12163bba770d891618b3ada5aaf5baa01516d80fef6214617"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/m4/blobs/sha256:e0fec6a49fd80cc7279c71f319d70d01ed49e894b53cd91e39f170288232fa93",
              "sha256": "e0fec6a49fd80cc7279c71f319d70d01ed49e894b53cd91e39f170288232fa93"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/m4/blobs/sha256:0cf53207764a2311db75b19628e2395ac6655ea1f7fdac97a33a0de34f315018",
              "sha256": "0cf53207764a2311db75b19628e2395ac6655ea1f7fdac97a33a0de34f315018"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/m4/blobs/sha256:f6d1087a51e0ff2e582b3043a25a51b67971b2246cf65167ef3abf1230160f04",
              "sha256": "f6d1087a51e0ff2e582b3043a25a51b67971b2246cf65167ef3abf1230160f04"
            }
          }
        }
      },
      "act": {
        "version": "HEAD-9499612",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/act/blobs/sha256:93df973291a43931e5daf45c3af27d53041ab083825f37f8ff843a527b03789b",
              "sha256": "93df973291a43931e5daf45c3af27d53041ab083825f37f8ff843a527b03789b"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/act/blobs/sha256:0c0956174f1bd2ea40c05026b794e9a69b3cc31a46d42fd2128e30216c6427fe",
              "sha256": "0c0956174f1bd2ea40c05026b794e9a69b3cc31a46d42fd2128e30216c6427fe"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/act/blobs/sha256:5215af5563695f5d0c11f4762c309c3bdf8a80ed3798e7a15ae49665d63c864c",
              "sha256": "5215af5563695f5d0c11f4762c309c3bdf8a80ed3798e7a15ae49665d63c864c"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/act/blobs/sha256:68e14ba5fb0453147f9fe090d8daee4af8d3bf7f5c3c02a0c917a3b4f715f711",
              "sha256": "68e14ba5fb0453147f9fe090d8daee4af8d3bf7f5c3c02a0c917a3b4f715f711"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/act/blobs/sha256:368b9522f56066dc5737970e1e698304d0040aa4c5575cf1510c690a8f954571",
              "sha256": "368b9522f56066dc5737970e1e698304d0040aa4c5575cf1510c690a8f954571"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/act/blobs/sha256:1fa51c27af6b9618ba9614210141fd4897b27d8175c533bb406da7a9f29bb1d9",
              "sha256": "1fa51c27af6b9618ba9614210141fd4897b27d8175c533bb406da7a9f29bb1d9"
            }
          }
        },
        "options": {
          "args": [
            "HEAD"
          ]
        }
      },
      "aws-sam-cli": {
        "version": "1.53.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://github.com/aws/aws-sam-cli/releases/download/v1.53.0/",
          "files": {
            "sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://github.com/aws/aws-sam-cli/releases/download/v1.53.0//aws-sam-cli-1.53.0.sierra.bottle.tar.gz",
              "sha256": "b6d0284a1053879dd8e76fc1fada29492882e3433457872bb55f960164955495"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://github.com/aws/aws-sam-cli/releases/download/v1.53.0//aws-sam-cli-1.53.0.x86_64_linux.bottle.tar.gz",
              "sha256": "b89fb378d3070c29af941184cc17eeee4c73c2bada7d5d0228a3d42a3c826357"
            }
          }
        }
      },
      "ghostscript": {
        "version": "9.56.1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghostscript/blobs/sha256:29539f2c18615fb82e82e4dab331005fcde1a2310332d7edf1227d77784ef1e6",
              "sha256": "29539f2c18615fb82e82e4dab331005fcde1a2310332d7edf1227d77784ef1e6"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghostscript/blobs/sha256:9909bbaac3747aac9815d27837e8c9d6e1e092dfaeaeec60834ad851dc576271",
              "sha256": "9909bbaac3747aac9815d27837e8c9d6e1e092dfaeaeec60834ad851dc576271"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghostscript/blobs/sha256:3ac4eb5ecab09d810f5a866d6752d18a5cb6bb9ea4ffc2592f4cc77105633fe5",
              "sha256": "3ac4eb5ecab09d810f5a866d6752d18a5cb6bb9ea4ffc2592f4cc77105633fe5"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghostscript/blobs/sha256:2602d48b7b9c23249cf8791c4526988301de44910645d5f4ebab068d3bf40f6c",
              "sha256": "2602d48b7b9c23249cf8791c4526988301de44910645d5f4ebab068d3bf40f6c"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghostscript/blobs/sha256:5b2e9e395d05d52805e3e22082207425b9ac85613cb02918e336de1809ed26e0",
              "sha256": "5b2e9e395d05d52805e3e22082207425b9ac85613cb02918e336de1809ed26e0"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghostscript/blobs/sha256:c0bb4afef0ba69db933901e280a820e93a02c239a2eddde6b736820de8eb17a3",
              "sha256": "c0bb4afef0ba69db933901e280a820e93a02c239a2eddde6b736820de8eb17a3"
            }
          }
        }
      },
      "imagemagick": {
        "version": "7.1.0-41",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/imagemagick/blobs/sha256:0947fb0633d16e29e735b19350831735730000839b8b008e88e1c84c718daf86",
              "sha256": "0947fb0633d16e29e735b19350831735730000839b8b008e88e1c84c718daf86"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/imagemagick/blobs/sha256:b42166c66464ac573194b5b4d19f05fc01f997d4bb16af63848c603552c12f6a",
              "sha256": "b42166c66464ac573194b5b4d19f05fc01f997d4bb16af63848c603552c12f6a"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/imagemagick/blobs/sha256:1167173b6c31cffd4a621aba5c1f72c4a67d35aa895e7eb558186fbb7e475d27",
              "sha256": "1167173b6c31cffd4a621aba5c1f72c4a67d35aa895e7eb558186fbb7e475d27"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/imagemagick/blobs/sha256:05548b724ee307314630054cfca50599fa0ecdbfb7aaffc43d713667ec8cce60",
              "sha256": "05548b724ee307314630054cfca50599fa0ecdbfb7aaffc43d713667ec8cce60"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/imagemagick/blobs/sha256:f744dbcab5d785701be4f3a31ff0d9dc175fc11abb4c08749b8b1fbc3e91555b",
              "sha256": "f744dbcab5d785701be4f3a31ff0d9dc175fc11abb4c08749b8b1fbc3e91555b"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/imagemagick/blobs/sha256:9d9753887256ff1346ca7bd16fc707afaa6ce9ebe46b05b78742b2ef052ef608",
              "sha256": "9d9753887256ff1346ca7bd16fc707afaa6ce9ebe46b05b78742b2ef052ef608"
            }
          }
        }
      },
      "k2tf": {
        "version": "0.7.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/k2tf/blobs/sha256:fae4ecfeba2b2a0a70b8029856a07b91af0cc54534ae0eb526dcd0eb7ef03b38",
              "sha256": "fae4ecfeba2b2a0a70b8029856a07b91af0cc54534ae0eb526dcd0eb7ef03b38"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/k2tf/blobs/sha256:a4d8b67c6c889d4e309bc92f387ca32539460de38df6b7d37d46dbc020d24c6d",
              "sha256": "a4d8b67c6c889d4e309bc92f387ca32539460de38df6b7d37d46dbc020d24c6d"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/k2tf/blobs/sha256:0be13024e37cde90792989744d82eec44558f34f1a8537874a36031c13bf6656",
              "sha256": "0be13024e37cde90792989744d82eec44558f34f1a8537874a36031c13bf6656"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/k2tf/blobs/sha256:7031f0ba068d3425128ed2b23ae8ac6cdd7578a335fd7375abecb3f5537984c4",
              "sha256": "7031f0ba068d3425128ed2b23ae8ac6cdd7578a335fd7375abecb3f5537984c4"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/k2tf/blobs/sha256:ccaa5b31b3fa878f8917ff1d6f9c16246894f0c9130f1ed9c4072b94dffa08bf",
              "sha256": "ccaa5b31b3fa878f8917ff1d6f9c16246894f0c9130f1ed9c4072b94dffa08bf"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/k2tf/blobs/sha256:c70e4d8b7f97a28091a7c07ba2e3411dc040a5ab56bf2d12b13bcbb6bfa53ca8",
              "sha256": "c70e4d8b7f97a28091a7c07ba2e3411dc040a5ab56bf2d12b13bcbb6bfa53ca8"
            }
          }
        }
      },
      "kubectl-rolesum": {
        "version": "1.5.1",
        "bottle": false
      },
      "netpbm": {
        "version": "10.86.33",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/netpbm/blobs/sha256:4d6847069d5fe7cfa083af5504968be345c51b89654554c0c69af4f851199ba0",
              "sha256": "4d6847069d5fe7cfa083af5504968be345c51b89654554c0c69af4f851199ba0"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/netpbm/blobs/sha256:13b35ba56a0f7d881b5a3d252736b4916b8e003ae97d49b23e8a97f1d1096558",
              "sha256": "13b35ba56a0f7d881b5a3d252736b4916b8e003ae97d49b23e8a97f1d1096558"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/netpbm/blobs/sha256:2aaa219cee191125fb32b144ef99263f94848fdf1a29f59969d1b051b84183e6",
              "sha256": "2aaa219cee191125fb32b144ef99263f94848fdf1a29f59969d1b051b84183e6"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/netpbm/blobs/sha256:18d6a720f0dcdf843f8d636203cea658a73dc4a22ff324169d529c49e94b4d8e",
              "sha256": "18d6a720f0dcdf843f8d636203cea658a73dc4a22ff324169d529c49e94b4d8e"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/netpbm/blobs/sha256:7c47fda00829312d18b25d50fe5067e4444bdf2a42b7825bbe5f62762912de6d",
              "sha256": "7c47fda00829312d18b25d50fe5067e4444bdf2a42b7825bbe5f62762912de6d"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/netpbm/blobs/sha256:9ab2fffdc4eebc47be06d97c5eb5849d55df9ce27a22d7de445d48a0061ef77c",
              "sha256": "9ab2fffdc4eebc47be06d97c5eb5849d55df9ce27a22d7de445d48a0061ef77c"
            }
          }
        }
      },
      "redis": {
        "version": "7.0.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/redis/blobs/sha256:526deec472da0768a5fe8d2f0617495f3c43befee02ae57ca723c01dae30be31",
              "sha256": "526deec472da0768a5fe8d2f0617495f3c43befee02ae57ca723c01dae30be31"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/redis/blobs/sha256:8e46ce2ed889f499c7c49823cb9b97a949047c4e2ee7876eb6404415221d0390",
              "sha256": "8e46ce2ed889f499c7c49823cb9b97a949047c4e2ee7876eb6404415221d0390"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/redis/blobs/sha256:ae3e94acbf74e76afbf42a7627bc91864191f8530e0a04b6b11c187b0340bb4a",
              "sha256": "ae3e94acbf74e76afbf42a7627bc91864191f8530e0a04b6b11c187b0340bb4a"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/redis/blobs/sha256:d477311ecd22f1cb31ce1207daf6ec22a6bd995bed85d65ffe0fad1077dbf275",
              "sha256": "d477311ecd22f1cb31ce1207daf6ec22a6bd995bed85d65ffe0fad1077dbf275"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/redis/blobs/sha256:ed3cd661095c0cf85988ce93d2f32123b984c6b523708065808a6d2fc6f615a1",
              "sha256": "ed3cd661095c0cf85988ce93d2f32123b984c6b523708065808a6d2fc6f615a1"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/redis/blobs/sha256:9a60623e87e59fa76b87a32f036430e1379a5c19fe4c48151b42a2d5aa3c0032",
              "sha256": "9a60623e87e59fa76b87a32f036430e1379a5c19fe4c48151b42a2d5aa3c0032"
            }
          }
        }
      },
      "ruby@2.7": {
        "version": "2.7.6",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.7/blobs/sha256:dd1b6e48e53b15f5289982740cae16bffe3858403925b96aacf81f3409d619d7",
              "sha256": "dd1b6e48e53b15f5289982740cae16bffe3858403925b96aacf81f3409d619d7"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.7/blobs/sha256:9a31d186dd090205258a81dce7d55ef8f306de06870822845f588d2b57671ae9",
              "sha256": "9a31d186dd090205258a81dce7d55ef8f306de06870822845f588d2b57671ae9"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.7/blobs/sha256:f6da8704b27e227870c09959ed9671740697f64c933418ad3a4d8372641bd04a",
              "sha256": "f6da8704b27e227870c09959ed9671740697f64c933418ad3a4d8372641bd04a"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.7/blobs/sha256:38d8fa9838362ad6b950fee49505f7db604ea2b6b569242cb14084c9b7ee6349",
              "sha256": "38d8fa9838362ad6b950fee49505f7db604ea2b6b569242cb14084c9b7ee6349"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.7/blobs/sha256:14e836b74e3c655d89fd9d78ac3b10d6bfe22c753c4ceb0eca5fe04ae6c60bc3",
              "sha256": "14e836b74e3c655d89fd9d78ac3b10d6bfe22c753c4ceb0eca5fe04ae6c60bc3"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.7/blobs/sha256:626d9402dd7bb8803240ffa793d037005a0b3e85c40a3d4356b249af39616f93",
              "sha256": "626d9402dd7bb8803240ffa793d037005a0b3e85c40a3d4356b249af39616f93"
            }
          }
        },
        "options": {
          "link": true,
          "conflicts_with": [
            "ruby"
          ]
        }
      },
      "unpaper": {
        "version": "7.0.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/unpaper/blobs/sha256:74997b9a9738930333b8c4cb000a055d2bc9dd42510be3e9d6d2f96a80908eba",
              "sha256": "74997b9a9738930333b8c4cb000a055d2bc9dd42510be3e9d6d2f96a80908eba"
            },
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/unpaper/blobs/sha256:d0b6c4e384cc73092163b88989eed3a87a5d489e693ecafcebfa5770f4e3d6d3",
              "sha256": "d0b6c4e384cc73092163b88989eed3a87a5d489e693ecafcebfa5770f4e3d6d3"
            },
            "monterey": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/unpaper/blobs/sha256:1dad125fcaf9aa24d1b347a575d286dbad91c7e5e475813314f3084ee1dd3947",
              "sha256": "1dad125fcaf9aa24d1b347a575d286dbad91c7e5e475813314f3084ee1dd3947"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/unpaper/blobs/sha256:3e23cbc93bf46fce64ebd7277e23207090c1275b067294f360d3437778cf9c03",
              "sha256": "3e23cbc93bf46fce64ebd7277e23207090c1275b067294f360d3437778cf9c03"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/unpaper/blobs/sha256:58134afe9017002e684e0ff392e77ee1eca707fa8e323ee7283858054be811eb",
              "sha256": "58134afe9017002e684e0ff392e77ee1eca707fa8e323ee7283858054be811eb"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/unpaper/blobs/sha256:abeb5bcc20a8037dd4629cb662d1eaf71ebcf901474e508b13e911d65dce1317",
              "sha256": "abeb5bcc20a8037dd4629cb662d1eaf71ebcf901474e508b13e911d65dce1317"
            }
          }
        }
      },
      "xmlstarlet": {
        "version": "1.6.1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/xmlstarlet/blobs/sha256:86e4e8bd44e5a7c143dd2a4395c535ddcac9c08bb6e910688ab0138ad3151d1e",
              "sha256": "86e4e8bd44e5a7c143dd2a4395c535ddcac9c08bb6e910688ab0138ad3151d1e"
            },
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/xmlstarlet/blobs/sha256:d654b90521d07ffc1304253fd2b927f9813effa5a65c3f6c43b67838077c009d",
              "sha256": "d654b90521d07ffc1304253fd2b927f9813effa5a65c3f6c43b67838077c009d"
            },
            "monterey": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/xmlstarlet/blobs/sha256:5af39f6a67faf86069e1bf504a000ed321b18ad5d2cf5fe90978dc00fb32c1dd",
              "sha256": "5af39f6a67faf86069e1bf504a000ed321b18ad5d2cf5fe90978dc00fb32c1dd"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/xmlstarlet/blobs/sha256:bc3baa847a617f3d67000ff14e96126f9bbdf54e916b6c693a2c8bf633ca0bfa",
              "sha256": "bc3baa847a617f3d67000ff14e96126f9bbdf54e916b6c693a2c8bf633ca0bfa"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/xmlstarlet/blobs/sha256:2a679570811f553e345748516fa37c2d4b529a75533bdb73316077aaed5ab8f6",
              "sha256": "2a679570811f553e345748516fa37c2d4b529a75533bdb73316077aaed5ab8f6"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/xmlstarlet/blobs/sha256:6e5d11ee1419a61a9f043663c1236d064ee692fd187ae15bf2114b42d8f0889e",
              "sha256": "6e5d11ee1419a61a9f043663c1236d064ee692fd187ae15bf2114b42d8f0889e"
            },
            "high_sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/xmlstarlet/blobs/sha256:56ce0e3190080e6e1111ebb31aa06aea53f16cde50359a356c24ff86a4df72b3",
              "sha256": "56ce0e3190080e6e1111ebb31aa06aea53f16cde50359a356c24ff86a4df72b3"
            },
            "sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/xmlstarlet/blobs/sha256:4958bf868beefb9a2b391c0fe05f5289b67a4cded708d71c4cc5fced130bac55",
              "sha256": "4958bf868beefb9a2b391c0fe05f5289b67a4cded708d71c4cc5fced130bac55"
            },
            "el_capitan": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/xmlstarlet/blobs/sha256:2d9a9b5f875b91c78378e7f3df12595528d8e4b9ec9e321131b7f9f78f30acd8",
              "sha256": "2d9a9b5f875b91c78378e7f3df12595528d8e4b9ec9e321131b7f9f78f30acd8"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/xmlstarlet/blobs/sha256:6c682deca05e96d3b8d42c2ab783a36cf06f6a6e3733cc4830395f9db26d51b3",
              "sha256": "6c682deca05e96d3b8d42c2ab783a36cf06f6a6e3733cc4830395f9db26d51b3"
            }
          }
        }
      },
      "qemu": {
        "version": "7.0.0_1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_monterey": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/qemu/blobs/sha256:d0640f2fa4be667c881a9364a5eabe40626b5cc887a6ade53d0b5701aaae3054",
              "sha256": "d0640f2fa4be667c881a9364a5eabe40626b5cc887a6ade53d0b5701aaae3054"
            },
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/qemu/blobs/sha256:cd0ea798d387018e571253f99084d8f976e73c4c696830af57c365426638f054",
              "sha256": "cd0ea798d387018e571253f99084d8f976e73c4c696830af57c365426638f054"
            },
            "monterey": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/qemu/blobs/sha256:545187ab2b386fc4ce48735ab4247c17783bd420a56ddb4800565c4868da141a",
              "sha256": "545187ab2b386fc4ce48735ab4247c17783bd420a56ddb4800565c4868da141a"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/qemu/blobs/sha256:68cedd112c5442d88767b8ebf1da68f0915ba4a7b2441d54453c098889b87d5a",
              "sha256": "68cedd112c5442d88767b8ebf1da68f0915ba4a7b2441d54453c098889b87d5a"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/qemu/blobs/sha256:50d9981998568aa2c724aa41b9c7c1be34af187667f53235469938a5cad464c1",
              "sha256": "50d9981998568aa2c724aa41b9c7c1be34af187667f53235469938a5cad464c1"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/qemu/blobs/sha256:7e606b9abfc143d599f567ae3391ece34da5929fc9304ce6ffd4b558d9c3bbd6",
              "sha256": "7e606b9abfc143d599f567ae3391ece34da5929fc9304ce6ffd4b558d9c3bbd6"
            }
          }
        }
      }
    }
  },
  "system": {
    "macos": {
      "catalina": {
        "HOMEBREW_VERSION": "2.5.2",
        "HOMEBREW_PREFIX": "/usr/local",
        "Homebrew/homebrew-core": "6453cefc91e56634e1f55ef7bb2bbdc1a2a8ded9",
        "CLT": "1103.0.32.62",
        "Xcode": "11.5",
        "macOS": "10.15.6"
      },
      "mojave": {
        "HOMEBREW_VERSION": "2.2.5",
        "HOMEBREW_PREFIX": "/usr/local",
        "Homebrew/homebrew-core": "2da0dc898a663118daf535515a9d8eb4052e160f",
        "CLT": "10.3.0.0.1.1562985497",
        "Xcode": "11.3.1",
        "macOS": "10.14.6"
      },
      "big_sur": {
        "HOMEBREW_VERSION": "3.3.2",
        "HOMEBREW_PREFIX": "/usr/local",
        "Homebrew/homebrew-core": "f9e6f04bfd243148541cc872d8f225e27ec50ef6",
        "CLT": "12.5.0.22.9",
        "Xcode": "12.5.1",
        "macOS": "11.6.1"
      },
      "monterey": {
        "HOMEBREW_VERSION": "3.5.4",
        "HOMEBREW_PREFIX": "/usr/local",
        "Homebrew/homebrew-core": "1da63443ca5c540b12cde7e1f12f5b107409ce75",
        "CLT": "13.4.0.0.1.1651278267",
        "Xcode": "13.4",
        "macOS": "12.4"
      }
    }
  }
}
