{
  "entries": {
    "tap": {
      "homebrew/core": {
        "revision": "017c694c1606a8638c7208a19d4a16cac7938074"
      },
      "homebrew/bundle": {
        "revision": "244bfa18b23948404fc2ee4253eb232053034212"
      },
      "homebrew/cask": {
        "revision": "2a21325961d165cfbddb2b33ccd27d15beae3710"
      },
      "adoptopenjdk/openjdk": {
        "revision": "f6e8c971c98f5ba48aedf2a5d218ebc914ee2304"
      },
      "johanhaleby/kubetail": {
        "revision": "76674415e2eabb0588ba3052c74ae29aa637bcd9"
      },
      "ladicle/kubectl-bindrole": {
        "revision": "75713ea9de013240796d154aa746ff3b84e68d9c"
      },
      "tektoncd/tools": {
        "revision": "f62f5a4d172632eeb29d656a7b7ef3efd1cdad47"
      },
      "jenkins-x/jx": {
        "revision": "9a76ebeecfde7c6bf75a5791b0126dcd0e0fa875"
      },
      "versent/taps": {
        "revision": "f3a4c99105e3ad517e9eef966b6b41321157bcaa"
      },
      "goreleaser/tap": {
        "revision": "6886d1270ec8d825d806999169697bfa2aad6d34"
      },
      "warrensbox/tap": {
        "revision": "74f9c4820bffacf759e6a898071632ce55e4d054"
      }
    },
    "cask": {
      "sublime-text": {
        "version": "4.113",
        "options": {
          "full_name": "sublime-text"
        }
      },
      "xquartz": {
        "version": "2.8.1",
        "options": {
          "full_name": "xquartz"
        }
      },
      "adoptopenjdk8": {
        "version": "8,292:b10",
        "options": {
          "full_name": "adoptopenjdk8"
        }
      },
      "aws-vault": {
        "version": "6.3.1",
        "options": {
          "full_name": "aws-vault"
        }
      },
      "docker": {
        "version": "4.0.0,67817",
        "options": {
          "full_name": "docker"
        }
      },
      "iterm2": {
        "version": "3.4.9",
        "options": {
          "full_name": "iterm2"
        }
      },
      "licecap": {
        "version": "1.31",
        "options": {
          "full_name": "licecap"
        }
      },
      "minikube": {
        "version": "1.4.0",
        "options": {
          "full_name": "minikube"
        }
      },
      "rubymine": {
        "version": "2021.2.1,212.5080.58",
        "options": {
          "full_name": "rubymine"
        }
      },
      "typora": {
        "version": "0.11.5",
        "options": {
          "full_name": "typora"
        }
      },
      "tunnelblick": {
        "version": "3.8.6a,5711",
        "options": {
          "full_name": "tunnelblick"
        }
      },
      "vagrant": {
        "version": "2.2.18",
        "options": {
          "full_name": "vagrant"
        }
      },
      "virtualbox": {
        "version": "6.1.26,145957",
        "options": {
          "full_name": "virtualbox"
        }
      },
      "virtualbox-extension-pack": {
        "version": "6.1.26",
        "options": {
          "full_name": "virtualbox-extension-pack"
        }
      },
      "zoomus": {
        "version": "5.0.24030.0508",
        "options": {
          "full_name": "zoomus"
        }
      },
      "keybase": {
        "version": "5.7.0,20210622193735:e3826b703a",
        "options": {
          "full_name": "keybase"
        }
      },
      "gpg-suite-no-mail": {
        "version": "2021.1,105",
        "options": {
          "full_name": "gpg-suite-no-mail"
        }
      },
      "whatsapp": {
        "version": "2.2134.10",
        "options": {
          "full_name": "whatsapp"
        }
      },
      "session-manager-plugin": {
        "version": "1.2.245.0",
        "options": {
          "full_name": "session-manager-plugin"
        }
      },
      "fritzing": {
        "version": "0.9.4,a1ffcea08814801903b1a9515b18cf97067968ae:498",
        "options": {
          "full_name": "fritzing"
        }
      },
      "gcc-arm-embedded": {
        "version": "10-2020-q4-major",
        "options": {
          "full_name": "gcc-arm-embedded"
        }
      },
      "macspice": {
        "version": "3.1.24,341",
        "options": {
          "full_name": "macspice"
        }
      },
      "google-cloud-sdk": {
        "version": "latest",
        "options": {
          "full_name": "google-cloud-sdk"
        }
      },
      "zoom": {
        "version": "5.7.6.1320",
        "options": {
          "full_name": "zoom"
        }
      },
      "ultimaker-cura": {
        "version": "4.10.0",
        "options": {
          "full_name": "ultimaker-cura"
        }
      },
      "openscad": {
        "version": "2021.01",
        "options": {
          "full_name": "openscad"
        }
      },
      "blackhole-2ch": {
        "version": "0.2.10",
        "options": {
          "full_name": "blackhole-2ch"
        }
      }
    },
    "brew": {
      "ansible": {
        "version": "4.5.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:ab7e0997ea8d4dc93fb868370dbe612ee06bece2041c0f5d8fefa8807414127d",
              "sha256": "ab7e0997ea8d4dc93fb868370dbe612ee06bece2041c0f5d8fefa8807414127d"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:1a1069566f9223e531a4dd5250cb0945cde0e2874a46619ef46ce5f6044b7478",
              "sha256": "1a1069566f9223e531a4dd5250cb0945cde0e2874a46619ef46ce5f6044b7478"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:4aeabaadc22a3d1f6270059e6a3c30353ded13c705856b978cfbe354f98b802e",
              "sha256": "4aeabaadc22a3d1f6270059e6a3c30353ded13c705856b978cfbe354f98b802e"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:2116b2e592eca6ce5b3703bb1da6d91b2b917ff7e17a039ce34557eedd63e380",
              "sha256": "2116b2e592eca6ce5b3703bb1da6d91b2b917ff7e17a039ce34557eedd63e380"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/blobs/sha256:fdc8a16069a0fc466b7802d6ebebd1db94a80d8d2969d481a440b13697a36945",
              "sha256": "fdc8a16069a0fc466b7802d6ebebd1db94a80d8d2969d481a440b13697a36945"
            }
          }
        }
      },
      "awscli": {
        "version": "2.2.35",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:4304842100c2657baf2b51cbdf62c8b79005a861b6451ded566a38557b3538f7",
              "sha256": "4304842100c2657baf2b51cbdf62c8b79005a861b6451ded566a38557b3538f7"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:1d442958ef2f448c352516e3ff519c25ddc50c334850abfdda19d64c10afddeb",
              "sha256": "1d442958ef2f448c352516e3ff519c25ddc50c334850abfdda19d64c10afddeb"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:46a2c5fbbda12db5bdc592dc00fb5b1e8301162ce6ab2a9373ef8407b95b2c64",
              "sha256": "46a2c5fbbda12db5bdc592dc00fb5b1e8301162ce6ab2a9373ef8407b95b2c64"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:2329a11743cb4c25d54560bcd99af439648db129b3fda32f9dec606bbace463d",
              "sha256": "2329a11743cb4c25d54560bcd99af439648db129b3fda32f9dec606bbace463d"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:a1448c55fce576fceb0edb24ad37532a7fb29914d7b981e067e8a2177a37f1ed",
              "sha256": "a1448c55fce576fceb0edb24ad37532a7fb29914d7b981e067e8a2177a37f1ed"
            }
          }
        }
      },
      "coreutils": {
        "version": "8.32",
        "bottle": {
          "rebuild": 2,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:e7d88d2b7a91a57dfd37c2ea14752d1bb116f25694eab1161d6e8088f7db5921",
              "sha256": "e7d88d2b7a91a57dfd37c2ea14752d1bb116f25694eab1161d6e8088f7db5921"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:371ec57703b3646e0113331308b6e03617c2a7f91e15e113380b605455daba20",
              "sha256": "371ec57703b3646e0113331308b6e03617c2a7f91e15e113380b605455daba20"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:7a97ad96dfbe6abbb5c94424518a077e040af8a77d1946ca960a5f33cd237551",
              "sha256": "7a97ad96dfbe6abbb5c94424518a077e040af8a77d1946ca960a5f33cd237551"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:10fbad2e35846c7e835cb979b5beb9edf07f3a9742ddcc3c28d9abd5fe9ccb1b",
              "sha256": "10fbad2e35846c7e835cb979b5beb9edf07f3a9742ddcc3c28d9abd5fe9ccb1b"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:6d0ddc3ead1b8259a9a97b7bc9cc891cbc5a236a82afd51f224de16affea0b54",
              "sha256": "6d0ddc3ead1b8259a9a97b7bc9cc891cbc5a236a82afd51f224de16affea0b54"
            }
          }
        }
      },
      "direnv": {
        "version": "2.28.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/direnv/blobs/sha256:8fabe33920273c377ace461d6f2ff02a78569b230b7625402086ea4ebeffff38",
              "sha256": "8fabe33920273c377ace461d6f2ff02a78569b230b7625402086ea4ebeffff38"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/direnv/blobs/sha256:64680c7245384e3cd59c4e0b9a1f32e5f0a26f5591b77c3736ed9160191571c3",
              "sha256": "64680c7245384e3cd59c4e0b9a1f32e5f0a26f5591b77c3736ed9160191571c3"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/direnv/blobs/sha256:c10f6a3b721b2c5c12b8bb3604bba9af3946edcada447327afa074b6c39e6996",
              "sha256": "c10f6a3b721b2c5c12b8bb3604bba9af3946edcada447327afa074b6c39e6996"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/direnv/blobs/sha256:8f1a615929f583478efb0c6853754dba806f94d95ed67c43f36062d95e50c636",
              "sha256": "8f1a615929f583478efb0c6853754dba806f94d95ed67c43f36062d95e50c636"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/direnv/blobs/sha256:4825370bfed48a27d68702df57dc7026d72d6329d14cd7f3722f09ad07021a1c",
              "sha256": "4825370bfed48a27d68702df57dc7026d72d6329d14cd7f3722f09ad07021a1c"
            }
          }
        }
      },
      "git": {
        "version": "2.33.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/git/blobs/sha256:06e9cc3e274380b2494451ed2e3c6acf1e091facdf2ce02da57921fbc6a3115a",
              "sha256": "06e9cc3e274380b2494451ed2e3c6acf1e091facdf2ce02da57921fbc6a3115a"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/git/blobs/sha256:1b89ec39f7a4b865b3c671f9b2495ec85992595112b74a5dc3ac78beae33ff0d",
              "sha256": "1b89ec39f7a4b865b3c671f9b2495ec85992595112b74a5dc3ac78beae33ff0d"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/git/blobs/sha256:4aaced15f34f02a7a965f9cee42b78ef471034e4d9cf3bbbe8bf2ab8f4f72678",
              "sha256": "4aaced15f34f02a7a965f9cee42b78ef471034e4d9cf3bbbe8bf2ab8f4f72678"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/git/blobs/sha256:5e85e4d8c9aaa398420993cb9c2561db79d3a71a12b79b8631ee0de5b0d86c67",
              "sha256": "5e85e4d8c9aaa398420993cb9c2561db79d3a71a12b79b8631ee0de5b0d86c67"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/git/blobs/sha256:06340f727c9e234bbe7fb940307c7ec2545b8186ed1bfbb9c20cf9763cb2d22c",
              "sha256": "06340f727c9e234bbe7fb940307c7ec2545b8186ed1bfbb9c20cf9763cb2d22c"
            }
          }
        }
      },
      "git-extras": {
        "version": "6.2.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-extras/blobs/sha256:ea543c26cfa1e6c3c76a1f3f83090dbdbcebbea42a163909f3b6f5e9d4d3d8bd",
              "sha256": "ea543c26cfa1e6c3c76a1f3f83090dbdbcebbea42a163909f3b6f5e9d4d3d8bd"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-extras/blobs/sha256:9c71ac1ab00be885a134f3cc634e89a412f61ba79f0c2da89fab10d1b16710e4",
              "sha256": "9c71ac1ab00be885a134f3cc634e89a412f61ba79f0c2da89fab10d1b16710e4"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-extras/blobs/sha256:937098a922e8b3149329d93079d35cd8bfa551296c3798d9a84bccf275d05770",
              "sha256": "937098a922e8b3149329d93079d35cd8bfa551296c3798d9a84bccf275d05770"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-extras/blobs/sha256:55b4518da5dc0d3f07725c86d64a844b8a98cbcdb28f2a8bd99791c444d1838f",
              "sha256": "55b4518da5dc0d3f07725c86d64a844b8a98cbcdb28f2a8bd99791c444d1838f"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-extras/blobs/sha256:fa97d3e160b30e65bd02a138aa64737e2849a04b8e1977ac76ef0dd5f2e96b60",
              "sha256": "fa97d3e160b30e65bd02a138aa64737e2849a04b8e1977ac76ef0dd5f2e96b60"
            }
          }
        }
      },
      "git-flow": {
        "version": "0.4.1",
        "bottle": {
          "cellar": ":any_skip_relocation",
          "prefix": "/usr/local",
          "files": {
            "catalina": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.catalina.bottle.tar.gz",
              "sha256": "8ea12cd7e2666fb6fdfaffaeb3a0437037a40cde559a835fc9de038f36a424dc"
            },
            "mojave": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.mojave.bottle.tar.gz",
              "sha256": "ab455769b6b8122e1d345f56d799fe43445bbbeba6265892715167388c737af9"
            },
            "high_sierra": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.high_sierra.bottle.tar.gz",
              "sha256": "ce4b64f4d13f4a5a8e05c9087627b42cd328c8accc8349c4ca256238d1d3fecc"
            },
            "sierra": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.sierra.bottle.tar.gz",
              "sha256": "acb9a2690fa86925600fa6e67e38731ef05f7f5d6ccfceb9c5175286c1081fe0"
            },
            "el_capitan": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.el_capitan.bottle.tar.gz",
              "sha256": "56826b30d91ffb54829f4792f88c673b1c3e748aa662bef5806e4a6f5d0ee015"
            },
            "yosemite": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.yosemite.bottle.tar.gz",
              "sha256": "a5e97d4d5c082194b36c18e7b051c43b2d5b37366b2ac56c5ea9407f6315685b"
            },
            "mavericks": {
              "url": "https://homebrew.bintray.com/bottles/git-flow-0.4.1.mavericks.bottle.tar.gz",
              "sha256": "8e931605a0d12cffa282db7244e0041cc14f8a7692e184a6bc1975800be2dac0"
            }
          }
        }
      },
      "iperf3": {
        "version": "3.10.1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/iperf3/blobs/sha256:7acd6b3fedf49e5614f825f928d24b035e93db311c25797d94b8ef880b78afe0",
              "sha256": "7acd6b3fedf49e5614f825f928d24b035e93db311c25797d94b8ef880b78afe0"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/iperf3/blobs/sha256:3c7b4daa79c385333b89c08740c477c633d45eba240610f7d43f26a3397555b3",
              "sha256": "3c7b4daa79c385333b89c08740c477c633d45eba240610f7d43f26a3397555b3"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/iperf3/blobs/sha256:a3d90dab71e047c3c585dc6dfbb63b240b3842e02af8fdaee665bb13b3d71c82",
              "sha256": "a3d90dab71e047c3c585dc6dfbb63b240b3842e02af8fdaee665bb13b3d71c82"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/iperf3/blobs/sha256:dea44691e2528c58d8f30d5b0b60d2407bb3ba17db5c3d0327fc29442f911847",
              "sha256": "dea44691e2528c58d8f30d5b0b60d2407bb3ba17db5c3d0327fc29442f911847"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/iperf3/blobs/sha256:6d078e2b5840746763092d35eede028ccf1b0db86274597ce064c14e5652cae7",
              "sha256": "6d078e2b5840746763092d35eede028ccf1b0db86274597ce064c14e5652cae7"
            }
          }
        }
      },
      "libtool": {
        "version": "2.4.6_4",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:a41a4872cdfaa34bb4723e728b73dd8c7a05725501a262bb41ad9af4e2fcd1d6",
              "sha256": "a41a4872cdfaa34bb4723e728b73dd8c7a05725501a262bb41ad9af4e2fcd1d6"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:dfb94265706b7204b346e3e5d48e149d7c7870063740f0c4ab2d6ec971260517",
              "sha256": "dfb94265706b7204b346e3e5d48e149d7c7870063740f0c4ab2d6ec971260517"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:ad541ac37b9a8042f998fb3640fe60f70d38483fa6a0784953d880190e9cc762",
              "sha256": "ad541ac37b9a8042f998fb3640fe60f70d38483fa6a0784953d880190e9cc762"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:35c8d3e024a2507d7d3244bcebdb0ccc61c25ae292e6df6025f78c7342a9799d",
              "sha256": "35c8d3e024a2507d7d3244bcebdb0ccc61c25ae292e6df6025f78c7342a9799d"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:6e91d7c9a8eac6eccecea681d94cec3acfd1a13056e36f4cd2a623ddaeacd49a",
              "sha256": "6e91d7c9a8eac6eccecea681d94cec3acfd1a13056e36f4cd2a623ddaeacd49a"
            }
          }
        }
      },
      "helm": {
        "version": "3.6.3",
        "bottle": {
          "rebuild": 1,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/blobs/sha256:981dd0b115b8c58c445f44a2960b79b7f9709639161d8e911014da09a1b2404a",
              "sha256": "981dd0b115b8c58c445f44a2960b79b7f9709639161d8e911014da09a1b2404a"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/blobs/sha256:45fd0dfb23a1d0873a605c114151e4737fbbf097aec401fe03d5b0045bd2201d",
              "sha256": "45fd0dfb23a1d0873a605c114151e4737fbbf097aec401fe03d5b0045bd2201d"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/blobs/sha256:c875589d2f82757fc1c9f3d08035deb1845f4d7e5587eaecbbce368c0156ebba",
              "sha256": "c875589d2f82757fc1c9f3d08035deb1845f4d7e5587eaecbbce368c0156ebba"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/blobs/sha256:731bd2ab02448ff37f0bd0ef285ef330c78ad47114ede11c90444c0411933247",
              "sha256": "731bd2ab02448ff37f0bd0ef285ef330c78ad47114ede11c90444c0411933247"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/blobs/sha256:5e592f9b5de73fdc1956d4714adc3ab05e05ad76077d233f474133fa4893fcdf",
              "sha256": "5e592f9b5de73fdc1956d4714adc3ab05e05ad76077d233f474133fa4893fcdf"
            }
          }
        }
      },
      "jenv": {
        "version": "0.5.4",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "all": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/jenv/blobs/sha256:521a1ad6e28b90f1e37893d279950e35957a0580464d639ec74c398f8da6d466",
              "sha256": "521a1ad6e28b90f1e37893d279950e35957a0580464d639ec74c398f8da6d466"
            }
          }
        }
      },
      "jq": {
        "version": "1.6",
        "bottle": {
          "rebuild": 1,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:674b3ae41c399f1e8e44c271b0e6909babff9fcd2e04a2127d25e2407ea4dd33",
              "sha256": "674b3ae41c399f1e8e44c271b0e6909babff9fcd2e04a2127d25e2407ea4dd33"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:bf0f8577632af7b878b6425476f5b1ab9c3bf66d65affb0c455048a173a0b6bf",
              "sha256": "bf0f8577632af7b878b6425476f5b1ab9c3bf66d65affb0c455048a173a0b6bf"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:820a3c85fcbb63088b160c7edf125d7e55fc2c5c1d51569304499c9cc4b89ce8",
              "sha256": "820a3c85fcbb63088b160c7edf125d7e55fc2c5c1d51569304499c9cc4b89ce8"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:71f0e76c5b22e5088426c971d5e795fe67abee7af6c2c4ae0cf4c0eb98ed21ff",
              "sha256": "71f0e76c5b22e5088426c971d5e795fe67abee7af6c2c4ae0cf4c0eb98ed21ff"
            },
            "high_sierra": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:dffcffa4ea13e8f0f2b45c5121e529077e135ae9a47254c32182231662ee9b72",
              "sha256": "dffcffa4ea13e8f0f2b45c5121e529077e135ae9a47254c32182231662ee9b72"
            },
            "sierra": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:bb4d19dc026c2d72c53eed78eaa0ab982e9fcad2cd2acc6d13e7a12ff658e877",
              "sha256": "bb4d19dc026c2d72c53eed78eaa0ab982e9fcad2cd2acc6d13e7a12ff658e877"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:2beea2c2c372ccf1081e9a5233fc3020470803254284aeecc071249d76b62338",
              "sha256": "2beea2c2c372ccf1081e9a5233fc3020470803254284aeecc071249d76b62338"
            }
          }
        }
      },
      "krew": {
        "version": "0.4.1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/krew/blobs/sha256:93bec04317c26ad77d8351150a7d7f6775218e3149bae190ac58db96ed83b3bb",
              "sha256": "93bec04317c26ad77d8351150a7d7f6775218e3149bae190ac58db96ed83b3bb"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/krew/blobs/sha256:72ec667db2da34fc298d32f376ae8a8a5769858a418185c5b581bec29458e394",
              "sha256": "72ec667db2da34fc298d32f376ae8a8a5769858a418185c5b581bec29458e394"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/krew/blobs/sha256:59131bf3f0e3264dd96a4f788cbe44bef4d4c21056dc583d912c3788cd429670",
              "sha256": "59131bf3f0e3264dd96a4f788cbe44bef4d4c21056dc583d912c3788cd429670"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/krew/blobs/sha256:677db3b345035e81dbd8ae57ef4c27e3693dcc0fafd279a508f20485a59d005c",
              "sha256": "677db3b345035e81dbd8ae57ef4c27e3693dcc0fafd279a508f20485a59d005c"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/krew/blobs/sha256:d8a57b4ff8bc90137b981cbd5baeccfc88573dca08a335e4af822c7a22079264",
              "sha256": "d8a57b4ff8bc90137b981cbd5baeccfc88573dca08a335e4af822c7a22079264"
            }
          }
        }
      },
      "kubernetes-cli": {
        "version": "1.22.1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:0a1898699bc316f6c691e7c1be98d0ce69f79e634c81770341dddc23f8e3a01f",
              "sha256": "0a1898699bc316f6c691e7c1be98d0ce69f79e634c81770341dddc23f8e3a01f"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:c4badce549b55e752e354d564d1886741c40a839fbce55b4e552bd7bc40e3bce",
              "sha256": "c4badce549b55e752e354d564d1886741c40a839fbce55b4e552bd7bc40e3bce"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:1c7f8280868fc960791f6123bf72886240c186e92ff161d76c173d69a7b39972",
              "sha256": "1c7f8280868fc960791f6123bf72886240c186e92ff161d76c173d69a7b39972"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:9812e84fde020d360255e42a64db2d788767ef81c9baac8ee7fd7af016ae6efb",
              "sha256": "9812e84fde020d360255e42a64db2d788767ef81c9baac8ee7fd7af016ae6efb"
            }
          }
        }
      },
      "kubectx": {
        "version": "0.9.4",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "all": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/kubectx/blobs/sha256:56fca18baee3ff65f4e6ca1491b515f46bcb61c3d184bc68c77c1b06e2e32cfb",
              "sha256": "56fca18baee3ff65f4e6ca1491b515f46bcb61c3d184bc68c77c1b06e2e32cfb"
            }
          }
        }
      },
      "kubetail": {
        "version": "1.6.13",
        "bottle": false
      },
      "maven": {
        "version": "3.8.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/maven/blobs/sha256:8bffe25b9b0a9bffdca2da60da2c5773970b33a04035a7826557ddb3f14f64e4",
              "sha256": "8bffe25b9b0a9bffdca2da60da2c5773970b33a04035a7826557ddb3f14f64e4"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/maven/blobs/sha256:73ad9de723ec4f67465e4fc84070f01b198be6a101392b90002673d8c4c444c3",
              "sha256": "73ad9de723ec4f67465e4fc84070f01b198be6a101392b90002673d8c4c444c3"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/maven/blobs/sha256:73ad9de723ec4f67465e4fc84070f01b198be6a101392b90002673d8c4c444c3",
              "sha256": "73ad9de723ec4f67465e4fc84070f01b198be6a101392b90002673d8c4c444c3"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/maven/blobs/sha256:73ad9de723ec4f67465e4fc84070f01b198be6a101392b90002673d8c4c444c3",
              "sha256": "73ad9de723ec4f67465e4fc84070f01b198be6a101392b90002673d8c4c444c3"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/maven/blobs/sha256:91d12d057fd0b0ebecf270e4779d0a9f06d53c73c26e442b4cc5accf728c2890",
              "sha256": "91d12d057fd0b0ebecf270e4779d0a9f06d53c73c26e442b4cc5accf728c2890"
            }
          }
        }
      },
      "mysql": {
        "version": "8.0.26",
        "bottle": {
          "rebuild": 1,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:824108be85caecc0b1101647c0f267fa5db8db084e865c5783fbdea111e93edf",
              "sha256": "824108be85caecc0b1101647c0f267fa5db8db084e865c5783fbdea111e93edf"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:5ad5be7141887ef52146e9d8950efdbcf3fbb99ca2dd1f3e3e05291b11eba498",
              "sha256": "5ad5be7141887ef52146e9d8950efdbcf3fbb99ca2dd1f3e3e05291b11eba498"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:1cec65a2f5f219793c2f67c95108e2eedd524aaabc55c632a08b592655ea5a53",
              "sha256": "1cec65a2f5f219793c2f67c95108e2eedd524aaabc55c632a08b592655ea5a53"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:375ae3a6ff585065e72dcf4d865ef8c9bdb1dccdc8c1f8b116f39425fbbc45ba",
              "sha256": "375ae3a6ff585065e72dcf4d865ef8c9bdb1dccdc8c1f8b116f39425fbbc45ba"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:ab4db157f1b69a07cb1d9e3f9b4eb1ad7cf1ba4d837328bc82235c661b22ff1c",
              "sha256": "ab4db157f1b69a07cb1d9e3f9b4eb1ad7cf1ba4d837328bc82235c661b22ff1c"
            }
          }
        }
      },
      "node": {
        "version": "16.8.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/node/blobs/sha256:cb89acec7de3b968e6e5f1aac5c0817f7bb8a6cad9feeaa3b47fe816fd47e706",
              "sha256": "cb89acec7de3b968e6e5f1aac5c0817f7bb8a6cad9feeaa3b47fe816fd47e706"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/node/blobs/sha256:4a7246c67afb628d1ffedfe72adb16b48705dc0eb77baae605a8f3a95ae05670",
              "sha256": "4a7246c67afb628d1ffedfe72adb16b48705dc0eb77baae605a8f3a95ae05670"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/node/blobs/sha256:9999cf2060a78494d700b63cc031d1cfcea4b3df788fc3ddc09ddcad874e4754",
              "sha256": "9999cf2060a78494d700b63cc031d1cfcea4b3df788fc3ddc09ddcad874e4754"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/node/blobs/sha256:e2268c9b0a451432310876508920c02680b2ce0e6b2e789c5d793b9912939f55",
              "sha256": "e2268c9b0a451432310876508920c02680b2ce0e6b2e789c5d793b9912939f55"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/node/blobs/sha256:05311b00fb7ab3c135bd29709b564e8c50d8dc2781a91acf82c9d75e62c75375",
              "sha256": "05311b00fb7ab3c135bd29709b564e8c50d8dc2781a91acf82c9d75e62c75375"
            }
          }
        }
      },
      "p7zip": {
        "version": "17.04",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:d1e2497a5256b9211572534456bb7271c9d04d10fc2e12599b95e0ddf4f1991b",
              "sha256": "d1e2497a5256b9211572534456bb7271c9d04d10fc2e12599b95e0ddf4f1991b"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:c4d62f05f0cba984aa6b5712debc4f7d3b2c3bece0c503633a588cb209c911c2",
              "sha256": "c4d62f05f0cba984aa6b5712debc4f7d3b2c3bece0c503633a588cb209c911c2"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:bea86999db7dee5f0cb78d3a72d875d822ec73ebb2a6e7d46cf27ae66243c645",
              "sha256": "bea86999db7dee5f0cb78d3a72d875d822ec73ebb2a6e7d46cf27ae66243c645"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:1484f0f3a0a4812dccb5f388c6671a7e524b001872b0df6d7cabc160c2f03989",
              "sha256": "1484f0f3a0a4812dccb5f388c6671a7e524b001872b0df6d7cabc160c2f03989"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/p7zip/blobs/sha256:d996780ca46e35a641f5f37284d19490cb5e0a990c9369045e92ba463d99430a",
              "sha256": "d996780ca46e35a641f5f37284d19490cb5e0a990c9369045e92ba463d99430a"
            }
          }
        }
      },
      "packer": {
        "version": "1.7.4",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:5857e3b4d569263e92c0215bfbbe0da92396d12573916efb2d8c214afd2c8a14",
              "sha256": "5857e3b4d569263e92c0215bfbbe0da92396d12573916efb2d8c214afd2c8a14"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:a3904f2fbc7fa390464436188302479a0612ed9ec80a771542d7c6dc54b797c0",
              "sha256": "a3904f2fbc7fa390464436188302479a0612ed9ec80a771542d7c6dc54b797c0"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:b0a55acb7d294f529db1cb83533d837154ac8d3c174d2ca089233a3bf27be06e",
              "sha256": "b0a55acb7d294f529db1cb83533d837154ac8d3c174d2ca089233a3bf27be06e"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:9bdf0e9d68b8cace130ebd58e88821da155954f575893f2dbe9b97bec7e38562",
              "sha256": "9bdf0e9d68b8cace130ebd58e88821da155954f575893f2dbe9b97bec7e38562"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/packer/blobs/sha256:28427704a6de254be710445deff553349ba3300416758559ecf8e74c065353e1",
              "sha256": "28427704a6de254be710445deff553349ba3300416758559ecf8e74c065353e1"
            }
          }
        }
      },
      "pandoc": {
        "version": "2.14.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:817369a3214c250c65b9d6fd6bd206520c333ea55832e1e74b8d7b49002a7bed",
              "sha256": "817369a3214c250c65b9d6fd6bd206520c333ea55832e1e74b8d7b49002a7bed"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:2b5eb56d4c06ff7350259d7b8dfc67291a389913b935c7cbfa0cd34b735fa728",
              "sha256": "2b5eb56d4c06ff7350259d7b8dfc67291a389913b935c7cbfa0cd34b735fa728"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:86246ec052a743cec4b83cb339fbfbe8016a13b22c8f69a7dfe2d5d12341ecbe",
              "sha256": "86246ec052a743cec4b83cb339fbfbe8016a13b22c8f69a7dfe2d5d12341ecbe"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:0bda1c5a703f8cc92861fde63cfb6d54f8d6bb363f4d3d096f95237147b38d54",
              "sha256": "0bda1c5a703f8cc92861fde63cfb6d54f8d6bb363f4d3d096f95237147b38d54"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:3c09c9b6af88a867dc7a67d5f81e711ec4250c12c53b868758c4b5857f35d81c",
              "sha256": "3c09c9b6af88a867dc7a67d5f81e711ec4250c12c53b868758c4b5857f35d81c"
            }
          }
        }
      },
      "pipenv": {
        "version": "2021.5.29",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pipenv/blobs/sha256:f3f66ceb9d6dc8b9f2d3a721de4118c49cb6e276f2fc610b3d567dcc3e412a80",
              "sha256": "f3f66ceb9d6dc8b9f2d3a721de4118c49cb6e276f2fc610b3d567dcc3e412a80"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pipenv/blobs/sha256:3e01446c114bb70d72f7455b19417e9e3190a95dcd565dc4ce994988b1b49f54",
              "sha256": "3e01446c114bb70d72f7455b19417e9e3190a95dcd565dc4ce994988b1b49f54"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pipenv/blobs/sha256:59356350c5fce175f14d525b10991f180fe557a01563c88b66d7771e733aa095",
              "sha256": "59356350c5fce175f14d525b10991f180fe557a01563c88b66d7771e733aa095"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pipenv/blobs/sha256:c29cf7117b5b8de37eadbaa43ad1a17daebead776b8767f2f6bc3884ed42f370",
              "sha256": "c29cf7117b5b8de37eadbaa43ad1a17daebead776b8767f2f6bc3884ed42f370"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/pipenv/blobs/sha256:f3fe5562f1d9e0237030b7171007e1e1bb224d8cdb88dc195964e22cfce94279",
              "sha256": "f3fe5562f1d9e0237030b7171007e1e1bb224d8cdb88dc195964e22cfce94279"
            }
          }
        }
      },
      "python": {
        "version": "3.9.6",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:36bdb8151cdc242487b9d3e6d6f305057b5699b4f6ac6905fc875e11b4ac2f3b",
              "sha256": "36bdb8151cdc242487b9d3e6d6f305057b5699b4f6ac6905fc875e11b4ac2f3b"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:1397f8fbb9c5858aa02b0177787cb74b8eb0dfede69fc37b64e2787d76baf2fe",
              "sha256": "1397f8fbb9c5858aa02b0177787cb74b8eb0dfede69fc37b64e2787d76baf2fe"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:38994e7cfb047bd6f1ab052b2de44d658575a373380934d594ba050a55abfbbd",
              "sha256": "38994e7cfb047bd6f1ab052b2de44d658575a373380934d594ba050a55abfbbd"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:e31002bb253e8a7daf292234fcca8a60df34dd124a44ba87bc53cabb086287e9",
              "sha256": "e31002bb253e8a7daf292234fcca8a60df34dd124a44ba87bc53cabb086287e9"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:2d6ec1b666b9eec7f2fd3a8b7cebedb5a013981cf52f80ac7c00e6eec25ff53f",
              "sha256": "2d6ec1b666b9eec7f2fd3a8b7cebedb5a013981cf52f80ac7c00e6eec25ff53f"
            }
          }
        }
      },
      "ruby@2.5": {
        "version": "2.5.9",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:deb2ee5e006f4fc7b3829dfcdb377300f3dc5f339562a6a1c1b4dec48ed21ae6",
              "sha256": "deb2ee5e006f4fc7b3829dfcdb377300f3dc5f339562a6a1c1b4dec48ed21ae6"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:fb6b696623fc988abecbf9fb9f5298219c62c69851123b9d9d69c3f127b0ec3c",
              "sha256": "fb6b696623fc988abecbf9fb9f5298219c62c69851123b9d9d69c3f127b0ec3c"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:8fab1468c593b5907e027c175dc19e3273b08cc8b344822ce593dcab645e857d",
              "sha256": "8fab1468c593b5907e027c175dc19e3273b08cc8b344822ce593dcab645e857d"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:ef4974800a4417e6251fb548486150157c2f0ff62275170431381480bac1c3ed",
              "sha256": "ef4974800a4417e6251fb548486150157c2f0ff62275170431381480bac1c3ed"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ruby/2.5/blobs/sha256:8b85cf06b1f139109bae913ade71190a65fb71f7848d846428cf95dbd0658e05",
              "sha256": "8b85cf06b1f139109bae913ade71190a65fb71f7848d846428cf95dbd0658e05"
            }
          }
        },
        "options": {
          "link": true,
          "conflicts_with": [
            "ruby"
          ]
        }
      },
      "terraform": {
        "version": "0.15.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terraform/blobs/sha256:0f7869b857c16b69c8a763f3a3dde378ce354445df03e6b965f60a80763eab2d",
              "sha256": "0f7869b857c16b69c8a763f3a3dde378ce354445df03e6b965f60a80763eab2d"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terraform/blobs/sha256:59046fe843b88927c89b6e1d0008b536fe19bbfb411be98507b8d11e9dc066f0",
              "sha256": "59046fe843b88927c89b6e1d0008b536fe19bbfb411be98507b8d11e9dc066f0"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terraform/blobs/sha256:8fdb8b4cd622bdf4f8503a5f1e53fb3ea3eddb5af5d94b9bb5df716133cda17a",
              "sha256": "8fdb8b4cd622bdf4f8503a5f1e53fb3ea3eddb5af5d94b9bb5df716133cda17a"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terraform/blobs/sha256:46079e3b1ff04a34902d604dcbdb4cf3f37c6679ca2e4b4b756a053a9628b063",
              "sha256": "46079e3b1ff04a34902d604dcbdb4cf3f37c6679ca2e4b4b756a053a9628b063"
            }
          }
        }
      },
      "unrar": {
        "version": "5.9.4",
        "bottle": false
      },
      "vault": {
        "version": "1.8.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/vault/blobs/sha256:9f9773d4e2c15dccb20f2a3aa8e0cd9edaa0756ffc8187e08dd8e300de04602a",
              "sha256": "9f9773d4e2c15dccb20f2a3aa8e0cd9edaa0756ffc8187e08dd8e300de04602a"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/vault/blobs/sha256:32cf10246fa1edee79817ed8c41e6136c24dd8562c466fac5af54c94daa44285",
              "sha256": "32cf10246fa1edee79817ed8c41e6136c24dd8562c466fac5af54c94daa44285"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/vault/blobs/sha256:f91a9a76aca031c55b39cd7d733bbfc9f6ff2cc608e9de2754c70d2197e71be9",
              "sha256": "f91a9a76aca031c55b39cd7d733bbfc9f6ff2cc608e9de2754c70d2197e71be9"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/vault/blobs/sha256:49002fcd38ec710569cb7272ae9e5ed5088e2dbca3bfea26f8126ce3f9d90113",
              "sha256": "49002fcd38ec710569cb7272ae9e5ed5088e2dbca3bfea26f8126ce3f9d90113"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/vault/blobs/sha256:354b86d78204aadc0c8c5d05b6deca0e758c31dfb50875cac52633ffe625b318",
              "sha256": "354b86d78204aadc0c8c5d05b6deca0e758c31dfb50875cac52633ffe625b318"
            }
          }
        }
      },
      "watch": {
        "version": "3.3.17",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/watch/blobs/sha256:45b90fbbda918d2c87ef6ccc29f1d931cbd0a490f2b1d599444591aae04a3cb0",
              "sha256": "45b90fbbda918d2c87ef6ccc29f1d931cbd0a490f2b1d599444591aae04a3cb0"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/watch/blobs/sha256:251b920890874ad798cf01c4c52564c720f785ce8184ae41181654b8f65e592b",
              "sha256": "251b920890874ad798cf01c4c52564c720f785ce8184ae41181654b8f65e592b"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/watch/blobs/sha256:05698a04a502ac32c97e0de0d9f00ac7c7450afd5d42b85d8ce1cd55d010fff3",
              "sha256": "05698a04a502ac32c97e0de0d9f00ac7c7450afd5d42b85d8ce1cd55d010fff3"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/watch/blobs/sha256:d2ce790ff9e073d04615051cd94dce4e06d37993de21894a64d4a23b7dfe5ea5",
              "sha256": "d2ce790ff9e073d04615051cd94dce4e06d37993de21894a64d4a23b7dfe5ea5"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/watch/blobs/sha256:2ae42218ef9ec54573be5a7f207c5057f326a62e11c8f158974aff56e1762284",
              "sha256": "2ae42218ef9ec54573be5a7f207c5057f326a62e11c8f158974aff56e1762284"
            }
          }
        }
      },
      "wget": {
        "version": "1.21.1_1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:bedb0887083a2d3ebcfbc03a1fed9919b726810dbbc2cd0efae923ef9d6bd5f4",
              "sha256": "bedb0887083a2d3ebcfbc03a1fed9919b726810dbbc2cd0efae923ef9d6bd5f4"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:307217b813330eda365570d7540aa2da69c678b6c4b78000d24048614902eea8",
              "sha256": "307217b813330eda365570d7540aa2da69c678b6c4b78000d24048614902eea8"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:e9efaae60b98da6832072ff1aa2336d0d12e2ab34df3b9acbc35c81a485ef505",
              "sha256": "e9efaae60b98da6832072ff1aa2336d0d12e2ab34df3b9acbc35c81a485ef505"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:c1709dfb1273aa522226ab34fc9ce73caae56d3536ebae2403017febef9fc256",
              "sha256": "c1709dfb1273aa522226ab34fc9ce73caae56d3536ebae2403017febef9fc256"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/wget/blobs/sha256:0b90bc93557882763d632e443e82ae05a0c2933a5e22d6fb1d0597a3f7833098",
              "sha256": "0b90bc93557882763d632e443e82ae05a0c2933a5e22d6fb1d0597a3f7833098"
            }
          }
        }
      },
      "youtube-dl": {
        "version": "2021.6.6",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:c8488b8408d6382b7bce6359cc18f7e14ab5f250152f18f69d250fbc6dd4f081",
              "sha256": "c8488b8408d6382b7bce6359cc18f7e14ab5f250152f18f69d250fbc6dd4f081"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:f4c3781a6c30a1da5319e581cac99be7fd533295fa8780ef66c3bf696f755e5f",
              "sha256": "f4c3781a6c30a1da5319e581cac99be7fd533295fa8780ef66c3bf696f755e5f"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:f4c3781a6c30a1da5319e581cac99be7fd533295fa8780ef66c3bf696f755e5f",
              "sha256": "f4c3781a6c30a1da5319e581cac99be7fd533295fa8780ef66c3bf696f755e5f"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:f4c3781a6c30a1da5319e581cac99be7fd533295fa8780ef66c3bf696f755e5f",
              "sha256": "f4c3781a6c30a1da5319e581cac99be7fd533295fa8780ef66c3bf696f755e5f"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:8cf1a12113ca9116896c792441ac44197a47df59a347eb09685dd6476fdb3ef3",
              "sha256": "8cf1a12113ca9116896c792441ac44197a47df59a347eb09685dd6476fdb3ef3"
            }
          }
        }
      },
      "azure-cli": {
        "version": "2.27.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/azure-cli/blobs/sha256:037c438217bfb4cdf4e530c2ab39c05a5a3910ed92dacfb44c580a923e99c9cd",
              "sha256": "037c438217bfb4cdf4e530c2ab39c05a5a3910ed92dacfb44c580a923e99c9cd"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/azure-cli/blobs/sha256:1c7f1a53eb16acf46940fe589d625a502c0aaf03860ac3c4f04d766a15ae3505",
              "sha256": "1c7f1a53eb16acf46940fe589d625a502c0aaf03860ac3c4f04d766a15ae3505"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/azure-cli/blobs/sha256:5ef32e5bf4b227f4cc405550c74ab53629bdcfe01d4759357e378700e3f369ac",
              "sha256": "5ef32e5bf4b227f4cc405550c74ab53629bdcfe01d4759357e378700e3f369ac"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/azure-cli/blobs/sha256:aca7b391640242729b8e5578b7420f16b2310790ecdd9fc70e83cd37983d3e36",
              "sha256": "aca7b391640242729b8e5578b7420f16b2310790ecdd9fc70e83cd37983d3e36"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/azure-cli/blobs/sha256:d8dc174dc36418f22586b985c02ea815c584d845bb5bd50bd5edc7993f5e9c32",
              "sha256": "d8dc174dc36418f22586b985c02ea815c584d845bb5bd50bd5edc7993f5e9c32"
            }
          }
        }
      },
      "git-flow-avh": {
        "version": "1.12.3",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:a3b1f734a2df3a919e1f62e8bbcf6a1f3c2a188cfeebce09c7e4f62fdca4242f",
              "sha256": "a3b1f734a2df3a919e1f62e8bbcf6a1f3c2a188cfeebce09c7e4f62fdca4242f"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:908021867768ca0b772288052b4518aeec2e682d2141b6b912c539176a069fce",
              "sha256": "908021867768ca0b772288052b4518aeec2e682d2141b6b912c539176a069fce"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:d9d8011ee6b4167e321077e44c0e99485a80f8bc1f294390495231c392d1bbba",
              "sha256": "d9d8011ee6b4167e321077e44c0e99485a80f8bc1f294390495231c392d1bbba"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:945e9ba05a169b32c86f5bd347542e803625791cf9a4b50a4a42fafb5e0b9c85",
              "sha256": "945e9ba05a169b32c86f5bd347542e803625791cf9a4b50a4a42fafb5e0b9c85"
            },
            "high_sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:945e9ba05a169b32c86f5bd347542e803625791cf9a4b50a4a42fafb5e0b9c85",
              "sha256": "945e9ba05a169b32c86f5bd347542e803625791cf9a4b50a4a42fafb5e0b9c85"
            },
            "sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:0e68b196dd24d9d41f9b0c5545d115c9ca8327dd799facbed2e619f8ceea221b",
              "sha256": "0e68b196dd24d9d41f9b0c5545d115c9ca8327dd799facbed2e619f8ceea221b"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-flow-avh/blobs/sha256:75416cf7069631b648859caefd1efd85ebfec2e4781acfeb4215889460439a69",
              "sha256": "75416cf7069631b648859caefd1efd85ebfec2e4781acfeb4215889460439a69"
            }
          }
        }
      },
      "gnu-getopt": {
        "version": "2.37.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gnu-getopt/blobs/sha256:0accef38c1961b29622380bc5d3dc0a58b22158b510f6f39b72485da5cdfa7ae",
              "sha256": "0accef38c1961b29622380bc5d3dc0a58b22158b510f6f39b72485da5cdfa7ae"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gnu-getopt/blobs/sha256:71316eadcf6481acbbe020d23d51fbd0b004ed51b680c97b82a08fc11668d3d9",
              "sha256": "71316eadcf6481acbbe020d23d51fbd0b004ed51b680c97b82a08fc11668d3d9"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gnu-getopt/blobs/sha256:f6fa9b03686181c83f17936c1e9c5d5fa396ea8ca0b80ff82b1eb9ff64e224e2",
              "sha256": "f6fa9b03686181c83f17936c1e9c5d5fa396ea8ca0b80ff82b1eb9ff64e224e2"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gnu-getopt/blobs/sha256:75a567d2d0b9d1e4e8c7a385eb2205073918ef1b68fdea848e406be04c732580",
              "sha256": "75a567d2d0b9d1e4e8c7a385eb2205073918ef1b68fdea848e406be04c732580"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gnu-getopt/blobs/sha256:fcc3de837a5b93ff5c8ba2c5af599df827f2e00a0eab532c256f5fd346ed3b7a",
              "sha256": "fcc3de837a5b93ff5c8ba2c5af599df827f2e00a0eab532c256f5fd346ed3b7a"
            }
          }
        }
      },
      "helm@2": {
        "version": "2.17.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:7372a593968befdd89f52a079360d4096be38df500199cec1de53b9d9a047502",
              "sha256": "7372a593968befdd89f52a079360d4096be38df500199cec1de53b9d9a047502"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:432e81bffefbb026bd50058e920a424b1805b84efc634d78c93dfedb9fec3d5a",
              "sha256": "432e81bffefbb026bd50058e920a424b1805b84efc634d78c93dfedb9fec3d5a"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:831c4f5b7cf7fc1ab53364eeb2eeb6eff8babdbc51817b406b65a948ac6258c2",
              "sha256": "831c4f5b7cf7fc1ab53364eeb2eeb6eff8babdbc51817b406b65a948ac6258c2"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:ab7ef44ce55c8b3597a2cb6dfe0ef93b74b389e6a4d6ab09c9a1ebe8dce5e594",
              "sha256": "ab7ef44ce55c8b3597a2cb6dfe0ef93b74b389e6a4d6ab09c9a1ebe8dce5e594"
            },
            "high_sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:a1c5cb86cce4fe2941c94309c8c75cd00ed9fae2e6edc6ea67aacadcf2f13c9e",
              "sha256": "a1c5cb86cce4fe2941c94309c8c75cd00ed9fae2e6edc6ea67aacadcf2f13c9e"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helm/2/blobs/sha256:718dfe0a0929ae4e4566954651c646ba6bab37dfd0a6ffac64740d0423461922",
              "sha256": "718dfe0a0929ae4e4566954651c646ba6bab37dfd0a6ffac64740d0423461922"
            }
          }
        }
      },
      "kubectl-bindrole": {
        "version": "1.5.1",
        "bottle": false
      },
      "ghc": {
        "version": "8.10.7",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ghc/blobs/sha256:dc95f7ac96f96622d0ba846d38355f944e16a4c06304a12f5549dde9de422c3d",
              "sha256": "dc95f7ac96f96622d0ba846d38355f944e16a4c06304a12f5549dde9de422c3d"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghc/blobs/sha256:c008431d9fdd2d56c97cd22134c776c9e2c3f322a4e8ebb9bb5808750c7ce1c2",
              "sha256": "c008431d9fdd2d56c97cd22134c776c9e2c3f322a4e8ebb9bb5808750c7ce1c2"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghc/blobs/sha256:9d7309d7f86d20b3c1d7c3ec74f7c77b060910b52d3550c2f6f17312da0d0d47",
              "sha256": "9d7309d7f86d20b3c1d7c3ec74f7c77b060910b52d3550c2f6f17312da0d0d47"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ghc/blobs/sha256:6f23a42bf1ad6b4ef103c29c09033117e27dbd85f752cdcdc33220cfd505c445",
              "sha256": "6f23a42bf1ad6b4ef103c29c09033117e27dbd85f752cdcdc33220cfd505c445"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/ghc/blobs/sha256:5ea70cb015d4f7d1c7aa25cca023b93dd254173964f6497ead92dda3602b961c",
              "sha256": "5ea70cb015d4f7d1c7aa25cca023b93dd254173964f6497ead92dda3602b961c"
            }
          }
        }
      },
      "helmfile": {
        "version": "0.140.0_1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helmfile/blobs/sha256:41f4bb88d498475f1db28c144e207c58b8d917b1f4d97a96d291f1cbc9bc295e",
              "sha256": "41f4bb88d498475f1db28c144e207c58b8d917b1f4d97a96d291f1cbc9bc295e"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helmfile/blobs/sha256:a6860d31efbb65af27d821acd5e7c4c54e166f921707eb3f0623ce7770895ae4",
              "sha256": "a6860d31efbb65af27d821acd5e7c4c54e166f921707eb3f0623ce7770895ae4"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helmfile/blobs/sha256:f112f7f0489e7214e12dbd6ec74fa325370e992eca10c5c79d5dd48a1476fc95",
              "sha256": "f112f7f0489e7214e12dbd6ec74fa325370e992eca10c5c79d5dd48a1476fc95"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helmfile/blobs/sha256:aabc9618eba3037f49830c0f09638791248e28df9de7c6de4fcec141f0421910",
              "sha256": "aabc9618eba3037f49830c0f09638791248e28df9de7c6de4fcec141f0421910"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/helmfile/blobs/sha256:870306f9af887397e8362f25750f515ebf4b2930d0a173235302ac49d562f1be",
              "sha256": "870306f9af887397e8362f25750f515ebf4b2930d0a173235302ac49d562f1be"
            }
          }
        }
      },
      "go": {
        "version": "1.17",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/go/blobs/sha256:9f5a37bfbe05c5a65eae3ec3f98664cfffe1643348877c8d988633614694899f",
              "sha256": "9f5a37bfbe05c5a65eae3ec3f98664cfffe1643348877c8d988633614694899f"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/go/blobs/sha256:16df4eed5e579c6ea8e75b35cdd4e351297be05911f2c768bb97588df6c816e2",
              "sha256": "16df4eed5e579c6ea8e75b35cdd4e351297be05911f2c768bb97588df6c816e2"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/go/blobs/sha256:89479b19d41e72c3cd615f92a2c1f408662b7a07a30253feac846bed7e553d3c",
              "sha256": "89479b19d41e72c3cd615f92a2c1f408662b7a07a30253feac846bed7e553d3c"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/go/blobs/sha256:31a55e8c57f194a5f6d44b9968582a5f4e65ccd3b533d1c323b6d2a7c46828dc",
              "sha256": "31a55e8c57f194a5f6d44b9968582a5f4e65ccd3b533d1c323b6d2a7c46828dc"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/go/blobs/sha256:34f67172a3c5afa67755508aa36decd2d4055e7c6f9cf481ea7b5fda2ff34578",
              "sha256": "34f67172a3c5afa67755508aa36decd2d4055e7c6f9cf481ea7b5fda2ff34578"
            }
          }
        }
      },
      "ffmpeg": {
        "version": "4.4_2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:d603441a90e72b165e70ef1787b2045c6e969f077dcadd1529d04162fbd18ab3",
              "sha256": "d603441a90e72b165e70ef1787b2045c6e969f077dcadd1529d04162fbd18ab3"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:9da28933b9f1abc3b1cf92382d1a8ea051c98f9dd0f4ef47e8d37d2aa9a4769a",
              "sha256": "9da28933b9f1abc3b1cf92382d1a8ea051c98f9dd0f4ef47e8d37d2aa9a4769a"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:3fcc129951906c60f6e2130131fde64e449bc562a605f64be74fc950cac930ea",
              "sha256": "3fcc129951906c60f6e2130131fde64e449bc562a605f64be74fc950cac930ea"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:8becf08fae7806a6365b489c3dcde8f6f0ddb49a64e96386c2c190a15604a486",
              "sha256": "8becf08fae7806a6365b489c3dcde8f6f0ddb49a64e96386c2c190a15604a486"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:303961f673338cc304e8a13daa7899cb807b6433be9a7bf78ceaed3fd48d5822",
              "sha256": "303961f673338cc304e8a13daa7899cb807b6433be9a7bf78ceaed3fd48d5822"
            }
          }
        }
      },
      "tektoncd/tools/tektoncd-cli": null,
      "istioctl": {
        "version": "1.11.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/istioctl/blobs/sha256:d5126a75578ed19cedc6e67ec10febd083cf4e8667a91e60a64c4edde35b7a6d",
              "sha256": "d5126a75578ed19cedc6e67ec10febd083cf4e8667a91e60a64c4edde35b7a6d"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/istioctl/blobs/sha256:822f03e4a1143b90dd99c42298f70678c255b31e0c35a301c101952e669e7972",
              "sha256": "822f03e4a1143b90dd99c42298f70678c255b31e0c35a301c101952e669e7972"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/istioctl/blobs/sha256:822f03e4a1143b90dd99c42298f70678c255b31e0c35a301c101952e669e7972",
              "sha256": "822f03e4a1143b90dd99c42298f70678c255b31e0c35a301c101952e669e7972"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/istioctl/blobs/sha256:822f03e4a1143b90dd99c42298f70678c255b31e0c35a301c101952e669e7972",
              "sha256": "822f03e4a1143b90dd99c42298f70678c255b31e0c35a301c101952e669e7972"
            }
          }
        }
      },
      "aws-iam-authenticator": {
        "version": "0.5.3",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:30639bda3ecb72388aeabc0f3e6587f58bc9867dc6b3a9f3046e9d0ef659f122",
              "sha256": "30639bda3ecb72388aeabc0f3e6587f58bc9867dc6b3a9f3046e9d0ef659f122"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:a161d4ea3ef00ab85c8f0cea198e0dafde39cd3a76359b75ea22521c35eac7d6",
              "sha256": "a161d4ea3ef00ab85c8f0cea198e0dafde39cd3a76359b75ea22521c35eac7d6"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:192ace97a0c76ed0aceda060290db6abcde5af8ad7dfc30faaf5f4ed4ae92b6a",
              "sha256": "192ace97a0c76ed0aceda060290db6abcde5af8ad7dfc30faaf5f4ed4ae92b6a"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:c7f23ccd6bdd852a7c1928df437381204aa9da22a2f41eb3a5776864838f39db",
              "sha256": "c7f23ccd6bdd852a7c1928df437381204aa9da22a2f41eb3a5776864838f39db"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:d6d0c278ef6d1d19a160035e5ff0039a16121be7107acce9bfa55ab59054c2f4",
              "sha256": "d6d0c278ef6d1d19a160035e5ff0039a16121be7107acce9bfa55ab59054c2f4"
            }
          }
        }
      },
      "cloc": {
        "version": "1.90",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/cloc/blobs/sha256:83f761b258052b7cc8ef375d5b7affa4d17afc372833b09b20695a9168ac6b9f",
              "sha256": "83f761b258052b7cc8ef375d5b7affa4d17afc372833b09b20695a9168ac6b9f"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/cloc/blobs/sha256:bcc059446f6a3c112e4eecf2d5da94531124ca7572cd953138bd9bb636dbd760",
              "sha256": "bcc059446f6a3c112e4eecf2d5da94531124ca7572cd953138bd9bb636dbd760"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/cloc/blobs/sha256:62e4eba4fd24d200fea078702f429acd303edfd8211a534362081c9d32283272",
              "sha256": "62e4eba4fd24d200fea078702f429acd303edfd8211a534362081c9d32283272"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/cloc/blobs/sha256:31d38191d5377740453d8eee73aaf287df8026bae490297179126a4016665d31",
              "sha256": "31d38191d5377740453d8eee73aaf287df8026bae490297179126a4016665d31"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/cloc/blobs/sha256:0d229ef534159ffc17ed62d294abcb7a4b68702bfceaf17c0f4fd2504afeecf5",
              "sha256": "0d229ef534159ffc17ed62d294abcb7a4b68702bfceaf17c0f4fd2504afeecf5"
            }
          }
        }
      },
      "sonar-scanner": {
        "version": "4.6.2.2472_1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "all": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/sonar-scanner/blobs/sha256:4f39cced5ca59962499fcd43aae7cc4f6a23357dec24fb2ac629e748b317dec6",
              "sha256": "4f39cced5ca59962499fcd43aae7cc4f6a23357dec24fb2ac629e748b317dec6"
            }
          }
        }
      },
      "yq": {
        "version": "4.12.1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/yq/blobs/sha256:8468f69c015c4eb4f13a92744ec6dcdd1819cd3e949e6762aa4280ca89a76b2a",
              "sha256": "8468f69c015c4eb4f13a92744ec6dcdd1819cd3e949e6762aa4280ca89a76b2a"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/yq/blobs/sha256:70ea92935a9c404b8612fae0e353c328b760231c6e6f5802281787583de225e5",
              "sha256": "70ea92935a9c404b8612fae0e353c328b760231c6e6f5802281787583de225e5"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/yq/blobs/sha256:7cd9103a69899546b59b57a84c5c8907b626f4b14c74eaf1d1be82a258c63f72",
              "sha256": "7cd9103a69899546b59b57a84c5c8907b626f4b14c74eaf1d1be82a258c63f72"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/yq/blobs/sha256:36565ec4e5408d3881a51674d96d336f95ce66ab1985bdf2fb6866dabf903b08",
              "sha256": "36565ec4e5408d3881a51674d96d336f95ce66ab1985bdf2fb6866dabf903b08"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/yq/blobs/sha256:3f7e9d015949986e0a3d39c0182de4d2cecc50e1fecc164ad7e0da67b4c5dc5a",
              "sha256": "3f7e9d015949986e0a3d39c0182de4d2cecc50e1fecc164ad7e0da67b4c5dc5a"
            }
          }
        }
      },
      "jenkins-x/jx/jx": null,
      "rustup-init": {
        "version": "1.24.3",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:d7de5aa4538303b308d1f136c475fdc83f8fa3b418da46a66cf8146a6f0d6ff2",
              "sha256": "d7de5aa4538303b308d1f136c475fdc83f8fa3b418da46a66cf8146a6f0d6ff2"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:d2bae6f97776cee5d796444ceb7c54f46e9dd56e51f9a1f439bbe7c842015572",
              "sha256": "d2bae6f97776cee5d796444ceb7c54f46e9dd56e51f9a1f439bbe7c842015572"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:7807b533709be5c92d7db4bd4189ae81ecf9f881544673591c7acb340d081b68",
              "sha256": "7807b533709be5c92d7db4bd4189ae81ecf9f881544673591c7acb340d081b68"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:681169de63d0e8a0dddbbe88388a64c4c15963e9c5b0dbf4029e1f2e75778667",
              "sha256": "681169de63d0e8a0dddbbe88388a64c4c15963e9c5b0dbf4029e1f2e75778667"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/rustup-init/blobs/sha256:5057bb4cf8c5c4e314358aad6790c1df9917a096baa010cf9f1de1eeb940f6ef",
              "sha256": "5057bb4cf8c5c4e314358aad6790c1df9917a096baa010cf9f1de1eeb940f6ef"
            }
          }
        }
      },
      "minikube": {
        "version": "1.22.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/minikube/blobs/sha256:d1ea963733dda06b43df6c1b34b87c4365ee055ce01cca8eb8bf90f2a7904468",
              "sha256": "d1ea963733dda06b43df6c1b34b87c4365ee055ce01cca8eb8bf90f2a7904468"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/minikube/blobs/sha256:476bb6663d4bd767e914c24b8c72cdbf3c12641aab6ac8fa59adb6b56cbe91f7",
              "sha256": "476bb6663d4bd767e914c24b8c72cdbf3c12641aab6ac8fa59adb6b56cbe91f7"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/minikube/blobs/sha256:5d3c3706be8d9f71cb9505fb10abb239a8dc491b68ef803030a83d431f1b1113",
              "sha256": "5d3c3706be8d9f71cb9505fb10abb239a8dc491b68ef803030a83d431f1b1113"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/minikube/blobs/sha256:b56e75f3f8c29eef6457c7c0d01eceb6623c5630f63f5fd2d3277cf40e08a016",
              "sha256": "b56e75f3f8c29eef6457c7c0d01eceb6623c5630f63f5fd2d3277cf40e08a016"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/minikube/blobs/sha256:8b2596238b1a4b9e7219ea490436075cb2b80f2ba2b855e3875a38496beb5574",
              "sha256": "8b2596238b1a4b9e7219ea490436075cb2b80f2ba2b855e3875a38496beb5574"
            }
          }
        }
      },
      "lsusb": {
        "version": "1.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/lsusb/blobs/sha256:3ad2f30f538b1ec0122a492b6e5f07ee70b2d7f2bb9e1cd267b8879b7534dc7d",
              "sha256": "3ad2f30f538b1ec0122a492b6e5f07ee70b2d7f2bb9e1cd267b8879b7534dc7d"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/lsusb/blobs/sha256:a1b7ef763a83e68074528407469fae8fd265269981332d139ab0acca67ea4376",
              "sha256": "a1b7ef763a83e68074528407469fae8fd265269981332d139ab0acca67ea4376"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/lsusb/blobs/sha256:7ab2cb027f186840ea1c96e47b4d48a8dfc42d91847d79bdd3faa6677ef603ca",
              "sha256": "7ab2cb027f186840ea1c96e47b4d48a8dfc42d91847d79bdd3faa6677ef603ca"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/lsusb/blobs/sha256:4f2f4f45cb6df2d5262bb823e02f750e7e5b4f117dca8a41fc6956435a277cb9",
              "sha256": "4f2f4f45cb6df2d5262bb823e02f750e7e5b4f117dca8a41fc6956435a277cb9"
            },
            "high_sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/lsusb/blobs/sha256:e696db36d09169064b3e97852d07464125e5bc6e400cb2a4cc186e6aa606574a",
              "sha256": "e696db36d09169064b3e97852d07464125e5bc6e400cb2a4cc186e6aa606574a"
            },
            "sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/lsusb/blobs/sha256:e696db36d09169064b3e97852d07464125e5bc6e400cb2a4cc186e6aa606574a",
              "sha256": "e696db36d09169064b3e97852d07464125e5bc6e400cb2a4cc186e6aa606574a"
            },
            "el_capitan": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/lsusb/blobs/sha256:e696db36d09169064b3e97852d07464125e5bc6e400cb2a4cc186e6aa606574a",
              "sha256": "e696db36d09169064b3e97852d07464125e5bc6e400cb2a4cc186e6aa606574a"
            }
          }
        }
      },
      "mosquitto": {
        "version": "2.0.10_1",
        "bottle": {
          "rebuild": 1,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mosquitto/blobs/sha256:1b42d8e6682597d9f1fcafd98865073266ed116d753f6c6dfc7ec0734b98dcab",
              "sha256": "1b42d8e6682597d9f1fcafd98865073266ed116d753f6c6dfc7ec0734b98dcab"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mosquitto/blobs/sha256:41ddee2a82f929b1754686d38f0e67570b1728eee8000ab4d4f68f52b052d152",
              "sha256": "41ddee2a82f929b1754686d38f0e67570b1728eee8000ab4d4f68f52b052d152"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mosquitto/blobs/sha256:1459490520f73a2a331487b1fef6163957ed7e4b91868d4bb830ed8448cf7a4b",
              "sha256": "1459490520f73a2a331487b1fef6163957ed7e4b91868d4bb830ed8448cf7a4b"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mosquitto/blobs/sha256:1c2764711220dba026af2d78c32d3f077da354252be4177059f5816faf610153",
              "sha256": "1c2764711220dba026af2d78c32d3f077da354252be4177059f5816faf610153"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/mosquitto/blobs/sha256:cd02e8539023e928475cf757b1865be0c65961bc55ce16c0006490e521dfb0b8",
              "sha256": "cd02e8539023e928475cf757b1865be0c65961bc55ce16c0006490e521dfb0b8"
            }
          }
        }
      },
      "rg": {
        "version": "13.0.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:d3e0ae859dc1e66ebecbc66a8ad1ec2abac59bc707d2305dde66212e71406d36",
              "sha256": "d3e0ae859dc1e66ebecbc66a8ad1ec2abac59bc707d2305dde66212e71406d36"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:a8f2bd6586de9f7aa36eaaefd36777309f9b5d57f01bf33bf022d715fd3dbb89",
              "sha256": "a8f2bd6586de9f7aa36eaaefd36777309f9b5d57f01bf33bf022d715fd3dbb89"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:0edcffa1251002e2747020d62a16ae077bd7aa5fb289d351622e0065c9686c40",
              "sha256": "0edcffa1251002e2747020d62a16ae077bd7aa5fb289d351622e0065c9686c40"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:b57024c0d221249a1f5eaef1069ac90d44e54afdadb146acd117ae23b7de98c6",
              "sha256": "b57024c0d221249a1f5eaef1069ac90d44e54afdadb146acd117ae23b7de98c6"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/ripgrep/blobs/sha256:34e3140b55f0fb5efb8db70e0709afe091632efaa84465e4c1c9ca3c8afa1bf2",
              "sha256": "34e3140b55f0fb5efb8db70e0709afe091632efaa84465e4c1c9ca3c8afa1bf2"
            }
          }
        }
      },
      "dfu-util": {
        "version": "0.10",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:387d614558287e0b5b7f6911d30f0f362d37771f21e7ee11f678859c0447ecea",
              "sha256": "387d614558287e0b5b7f6911d30f0f362d37771f21e7ee11f678859c0447ecea"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:1e960a2b57fd6fa0fbfe5a9bb7aa0e35e24664ee65d686eb8fbef724152bc0d0",
              "sha256": "1e960a2b57fd6fa0fbfe5a9bb7aa0e35e24664ee65d686eb8fbef724152bc0d0"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:3baa1c97498ad73a60b12c1d1ffa192a9b57946be6ced7ab826f3e1135113a74",
              "sha256": "3baa1c97498ad73a60b12c1d1ffa192a9b57946be6ced7ab826f3e1135113a74"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:6bc199867512701a02e09aeea49adfefb5d38f413e8401b35025a827fbcc4036",
              "sha256": "6bc199867512701a02e09aeea49adfefb5d38f413e8401b35025a827fbcc4036"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dfu-util/blobs/sha256:8e47e33db3f1809197dd05093a5477779fde7d1da2e7c5f83a132d2f742d1b54",
              "sha256": "8e47e33db3f1809197dd05093a5477779fde7d1da2e7c5f83a132d2f742d1b54"
            }
          }
        }
      },
      "stlink": {
        "version": "1.7.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:79683924dac821a1744cf32a96c3296eecd1668b5f2f64dbdcf570f32480459f",
              "sha256": "79683924dac821a1744cf32a96c3296eecd1668b5f2f64dbdcf570f32480459f"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:9ea7be4ae1c0b91ceeb40c6df9d07ad6a5660be80043895bcf29acc47988d10d",
              "sha256": "9ea7be4ae1c0b91ceeb40c6df9d07ad6a5660be80043895bcf29acc47988d10d"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:e162fb37d4a7e2a0e006c5cb9beae3b86784d6a0b3d371fc33d7ed9ba2140083",
              "sha256": "e162fb37d4a7e2a0e006c5cb9beae3b86784d6a0b3d371fc33d7ed9ba2140083"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:f112f45203b8c460da03ae840529d4564a677d0621ac0a9576bac510258a9ef5",
              "sha256": "f112f45203b8c460da03ae840529d4564a677d0621ac0a9576bac510258a9ef5"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/stlink/blobs/sha256:141e0873ed4745b1224f6996f5dac5461f27a87e17d36a9f56a080f27a922f23",
              "sha256": "141e0873ed4745b1224f6996f5dac5461f27a87e17d36a9f56a080f27a922f23"
            }
          }
        }
      },
      "ansible@2.9": {
        "version": "2.9.21",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/2.9/blobs/sha256:3198997b5e28c55a3316ee33d37c3fee7598a95438323e266f3725efa33cc071",
              "sha256": "3198997b5e28c55a3316ee33d37c3fee7598a95438323e266f3725efa33cc071"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/2.9/blobs/sha256:eb288d9cf23fdaf1959854b07f677fd58965521a5da05e788521047bec8442a3",
              "sha256": "eb288d9cf23fdaf1959854b07f677fd58965521a5da05e788521047bec8442a3"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/2.9/blobs/sha256:32c4d5c641bb8df8cb1fc8ba922511ba0ab2f0d0ce1fdb13ca1b221879bae001",
              "sha256": "32c4d5c641bb8df8cb1fc8ba922511ba0ab2f0d0ce1fdb13ca1b221879bae001"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/ansible/2.9/blobs/sha256:30701024ebd7cdcafe5b95fe47cdc6f2d5e3250c6797c18120a16804b69f86bc",
              "sha256": "30701024ebd7cdcafe5b95fe47cdc6f2d5e3250c6797c18120a16804b69f86bc"
            }
          }
        }
      },
      "goreleaser": {
        "version": "0.177.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/goreleaser/blobs/sha256:3ecbe442e8754f53a24f7a35ecd23cf7c9e2dee00f10f8302402b64f24c8cae4",
              "sha256": "3ecbe442e8754f53a24f7a35ecd23cf7c9e2dee00f10f8302402b64f24c8cae4"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/goreleaser/blobs/sha256:fd829155862fd4594b5263baac8bad780ed60fa69b82f2fe4fd19cb191fed142",
              "sha256": "fd829155862fd4594b5263baac8bad780ed60fa69b82f2fe4fd19cb191fed142"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/goreleaser/blobs/sha256:bc090cd941ea4237c34e495588afe3c62ef9383abc65a52458d8f74e5b343555",
              "sha256": "bc090cd941ea4237c34e495588afe3c62ef9383abc65a52458d8f74e5b343555"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/goreleaser/blobs/sha256:465b604acf9e78497c37876bd68dcc3c7bbfead82f6f0cc91f21c22abb6e8363",
              "sha256": "465b604acf9e78497c37876bd68dcc3c7bbfead82f6f0cc91f21c22abb6e8363"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/goreleaser/blobs/sha256:9af4aada1c16e157b08f3bb06706be00dc80ac3a2bd5b29be43555ee8a692ea3",
              "sha256": "9af4aada1c16e157b08f3bb06706be00dc80ac3a2bd5b29be43555ee8a692ea3"
            }
          }
        }
      },
      "saml2aws": {
        "version": "2.27.1",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/saml2aws/blobs/sha256:6f194e0c4cd520dc13c2ea2b622ba3e005dd32606b34ebb64ffc0de32566d226",
              "sha256": "6f194e0c4cd520dc13c2ea2b622ba3e005dd32606b34ebb64ffc0de32566d226"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/saml2aws/blobs/sha256:f8400874432bf2363cf66a350d823b003d8168e0619768fe762cc5a2c3b5dddb",
              "sha256": "f8400874432bf2363cf66a350d823b003d8168e0619768fe762cc5a2c3b5dddb"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/saml2aws/blobs/sha256:b18ff9fd260e6f234d7e1bfe16baef4ef64a6987a8b04831afc13f83a7bcfcd6",
              "sha256": "b18ff9fd260e6f234d7e1bfe16baef4ef64a6987a8b04831afc13f83a7bcfcd6"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/saml2aws/blobs/sha256:cf22563c79eb2e6bd479124ba520b40dac75f93ce97e3128e7fd16629f450c57",
              "sha256": "cf22563c79eb2e6bd479124ba520b40dac75f93ce97e3128e7fd16629f450c57"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/saml2aws/blobs/sha256:8f53fdfb2e42fe89d580f3c137c0a3cf610240ad658866c41c2ed8778b415d59",
              "sha256": "8f53fdfb2e42fe89d580f3c137c0a3cf610240ad658866c41c2ed8778b415d59"
            }
          }
        }
      },
      "terminal-notifier": {
        "version": "2.0.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:d1268e236f13f5bb4cd5fead9cf54cfb54ceefb98e34861bd39cf3c7e6ef34cf",
              "sha256": "d1268e236f13f5bb4cd5fead9cf54cfb54ceefb98e34861bd39cf3c7e6ef34cf"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:91f14694ebce08887492aa75138753cd9ff74977868927b15b52559728280055",
              "sha256": "91f14694ebce08887492aa75138753cd9ff74977868927b15b52559728280055"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:78eff95b7436480521ee68a8581ff2df0c615adefccd279486f2491f1b1c0a4b",
              "sha256": "78eff95b7436480521ee68a8581ff2df0c615adefccd279486f2491f1b1c0a4b"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:9671c602326357b7397248bfb0cf062bc47f19add15b615e512f58545c387c31",
              "sha256": "9671c602326357b7397248bfb0cf062bc47f19add15b615e512f58545c387c31"
            },
            "high_sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:f112656234f4100d23cc1a41b96f92a09974360a822c2ec0fb6f9970862c1a22",
              "sha256": "f112656234f4100d23cc1a41b96f92a09974360a822c2ec0fb6f9970862c1a22"
            },
            "sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:210cd525fad70bbaef40f092bc3478b1519f68f73c034990230d8b1cc61a8a7c",
              "sha256": "210cd525fad70bbaef40f092bc3478b1519f68f73c034990230d8b1cc61a8a7c"
            },
            "el_capitan": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/terminal-notifier/blobs/sha256:75ce68fd95fb502e20ccb25be72f7db12112ac1a4bdf5a70c140cd174ecbacf5",
              "sha256": "75ce68fd95fb502e20ccb25be72f7db12112ac1a4bdf5a70c140cd174ecbacf5"
            }
          }
        }
      },
      "trash": {
        "version": "0.9.2",
        "bottle": {
          "rebuild": 1,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:11c0c85ec692ea6d4a125070f0a6ca576aff991608a6c9632b984cbf983e2481",
              "sha256": "11c0c85ec692ea6d4a125070f0a6ca576aff991608a6c9632b984cbf983e2481"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:403ba52ce97d38535e1d127ca227afd4ea2d0e0c8b414118dbc5376c9ed8f094",
              "sha256": "403ba52ce97d38535e1d127ca227afd4ea2d0e0c8b414118dbc5376c9ed8f094"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:b452d67cdeeb52db0aaadd258bc3e214a5ea5ed37da698b45017b01457115ea6",
              "sha256": "b452d67cdeeb52db0aaadd258bc3e214a5ea5ed37da698b45017b01457115ea6"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:d8ad5460b24a51a4a12b31ebf1a2887e9e86e029d061f6994c3c1caea7bf0551",
              "sha256": "d8ad5460b24a51a4a12b31ebf1a2887e9e86e029d061f6994c3c1caea7bf0551"
            },
            "high_sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/trash/blobs/sha256:0ef5ea924ba8d01398686657a839ad270796f3f10eee86d6522980d32038df9a",
              "sha256": "0ef5ea924ba8d01398686657a839ad270796f3f10eee86d6522980d32038df9a"
            }
          }
        }
      },
      "dos2unix": {
        "version": "7.4.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:54cb2c42f9f016e03ccf712d0927963fc629d8419de3bfdf324dc51088f87157",
              "sha256": "54cb2c42f9f016e03ccf712d0927963fc629d8419de3bfdf324dc51088f87157"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:7a4b0e40724b8721ff76a36cb74fd6c9816ce0e9b518c3abf0e2ec5bab5b0cce",
              "sha256": "7a4b0e40724b8721ff76a36cb74fd6c9816ce0e9b518c3abf0e2ec5bab5b0cce"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:eb14b6db2fbf8fa0f52b69aa33101e1eb04bf3d4ef5dae7234754046e4cd54a6",
              "sha256": "eb14b6db2fbf8fa0f52b69aa33101e1eb04bf3d4ef5dae7234754046e4cd54a6"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:7a23d283d81cad13690d788c61117cbfe091282503077ad56bde83f026dd5097",
              "sha256": "7a23d283d81cad13690d788c61117cbfe091282503077ad56bde83f026dd5097"
            },
            "high_sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:98858938fe95e2453056d80c03c35396913a5c6902b2df00b618c884a4b51521",
              "sha256": "98858938fe95e2453056d80c03c35396913a5c6902b2df00b618c884a4b51521"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/dos2unix/blobs/sha256:331d745aab1034b696b0f873ccdb1431266ed813215669a5446e7c2285984a2b",
              "sha256": "331d745aab1034b696b0f873ccdb1431266ed813215669a5446e7c2285984a2b"
            }
          }
        }
      },
      "gh": {
        "version": "2.0.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:3a768ea1d1c3efbd3d987084d22be74a986fb012bcca9e217ef2eeef2a8899d1",
              "sha256": "3a768ea1d1c3efbd3d987084d22be74a986fb012bcca9e217ef2eeef2a8899d1"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:9058e6c649fe788b0fe681ea48219393467e1d495a4121c6741d235ea857ae19",
              "sha256": "9058e6c649fe788b0fe681ea48219393467e1d495a4121c6741d235ea857ae19"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:8e5805801192978681917fcaea12edaf1ff099998825b0fb8dc5b43cb08075c3",
              "sha256": "8e5805801192978681917fcaea12edaf1ff099998825b0fb8dc5b43cb08075c3"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:24f44d9b4ed8a750dcfacc0897036420942833f58bd4f8c413614cfc8dfff58e",
              "sha256": "24f44d9b4ed8a750dcfacc0897036420942833f58bd4f8c413614cfc8dfff58e"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:ac34664fe701dc2917ae0845f2e2f445f6aacbba2648a4f917b25acd87ca6dfa",
              "sha256": "ac34664fe701dc2917ae0845f2e2f445f6aacbba2648a4f917b25acd87ca6dfa"
            }
          }
        }
      },
      "krb5": {
        "version": "1.19.2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:62a2882f4193d6871d9c8116b897a8d33d6a4fedb954646a0eefdc4bfe623110",
              "sha256": "62a2882f4193d6871d9c8116b897a8d33d6a4fedb954646a0eefdc4bfe623110"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:6ae8cffb08f9cba4842a21fc92618e22403a474fbd6d05820c3755401d55688d",
              "sha256": "6ae8cffb08f9cba4842a21fc92618e22403a474fbd6d05820c3755401d55688d"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:5d0157ff13610f06bc262350978ef1f754e2b7ed0721ba27c431cfd5b5b16639",
              "sha256": "5d0157ff13610f06bc262350978ef1f754e2b7ed0721ba27c431cfd5b5b16639"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:9dd6fca906e634be1c1b05a99fa8f28735a969e3eb4d939048e89f322c3a4278",
              "sha256": "9dd6fca906e634be1c1b05a99fa8f28735a969e3eb4d939048e89f322c3a4278"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:2626ed3b8a8e5448aabeac56f6fe91b199fe896a5fd84394d5475213fde1a139",
              "sha256": "2626ed3b8a8e5448aabeac56f6fe91b199fe896a5fd84394d5475213fde1a139"
            }
          }
        }
      },
      "tfswitch": {
        "version": "0.12.1168",
        "bottle": false
      },
      "git-gui": {
        "version": "2.33.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "all": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-gui/blobs/sha256:d3db42727bd2bbbbe7df773c5a58a20cd41b77b4d1aa59612ca6db7bde58bd51",
              "sha256": "d3db42727bd2bbbbe7df773c5a58a20cd41b77b4d1aa59612ca6db7bde58bd51"
            }
          }
        }
      },
      "git-lfs": {
        "version": "2.13.3",
        "bottle": {
          "rebuild": 1,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-lfs/blobs/sha256:def0547e1e83bda58b68b6880f3eb5a0a803df0addfb6e4915b6b76852735195",
              "sha256": "def0547e1e83bda58b68b6880f3eb5a0a803df0addfb6e4915b6b76852735195"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-lfs/blobs/sha256:db355632f3236b7042d2900b7883edfe476d9fb467e62124bb5864ab2be88415",
              "sha256": "db355632f3236b7042d2900b7883edfe476d9fb467e62124bb5864ab2be88415"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-lfs/blobs/sha256:b4c1b5d14562c7a1e0fbe210dc5e58888dff8437586ffc49425099c546a988b0",
              "sha256": "b4c1b5d14562c7a1e0fbe210dc5e58888dff8437586ffc49425099c546a988b0"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-lfs/blobs/sha256:0aaead90f98027ec8774eb318a58c6f5bef167342a52b115207ecb878f63e7f5",
              "sha256": "0aaead90f98027ec8774eb318a58c6f5bef167342a52b115207ecb878f63e7f5"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/git-lfs/blobs/sha256:918e279cead08a4d34efccd29eb656849b727c46b4431287b326e8f0fe92f40b",
              "sha256": "918e279cead08a4d34efccd29eb656849b727c46b4431287b326e8f0fe92f40b"
            }
          }
        }
      },
      "golangci-lint": {
        "version": "1.42.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/golangci-lint/blobs/sha256:7b821d10ce40aa92927daa2774bcad2c832b57e21d4ccb41a742526157301a9d",
              "sha256": "7b821d10ce40aa92927daa2774bcad2c832b57e21d4ccb41a742526157301a9d"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/golangci-lint/blobs/sha256:fe608365f6c4b8e82fb807129e78bd099ce076baf54d0ab01dbd7e800bc77999",
              "sha256": "fe608365f6c4b8e82fb807129e78bd099ce076baf54d0ab01dbd7e800bc77999"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/golangci-lint/blobs/sha256:1f46a78a68b21ad7dc3f65d06635bf29b135a01910c1f8f754801f63babd534a",
              "sha256": "1f46a78a68b21ad7dc3f65d06635bf29b135a01910c1f8f754801f63babd534a"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/golangci-lint/blobs/sha256:c2b0ee0542931311a66fd820344d3196ee61d7f518a500cb9809d7b38fabc046",
              "sha256": "c2b0ee0542931311a66fd820344d3196ee61d7f518a500cb9809d7b38fabc046"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/golangci-lint/blobs/sha256:0851e11ff1033346cfe649c70789c9f7d74ceac793f7a90227efdb6b1b7002d6",
              "sha256": "0851e11ff1033346cfe649c70789c9f7d74ceac793f7a90227efdb6b1b7002d6"
            }
          }
        }
      },
      "portaudio": {
        "version": "19.7.0",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:50a45425f5c6026788791370b1ba30b0dcc82b6cedacd2240168f57f9abe6484",
              "sha256": "50a45425f5c6026788791370b1ba30b0dcc82b6cedacd2240168f57f9abe6484"
            },
            "big_sur": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:f9ae97164b4101048870c761b15998e46f40da666c3f0e20c33cf6ce2f7319d0",
              "sha256": "f9ae97164b4101048870c761b15998e46f40da666c3f0e20c33cf6ce2f7319d0"
            },
            "catalina": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:8b87696f44cf2220cff66b9bcfa105f6a58dfec4eb2a881409e37773494c84b4",
              "sha256": "8b87696f44cf2220cff66b9bcfa105f6a58dfec4eb2a881409e37773494c84b4"
            },
            "mojave": {
              "cellar": ":any",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:a2cab0bc4fee9757af7269408eb91df07ddeddfa6dd35c9740aae93816622b0b",
              "sha256": "a2cab0bc4fee9757af7269408eb91df07ddeddfa6dd35c9740aae93816622b0b"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/portaudio/blobs/sha256:db0f24a3a3f52c1bc32fa7a36bab6b1b7ae0e3b936bc857ce973ab8666b2eb6a",
              "sha256": "db0f24a3a3f52c1bc32fa7a36bab6b1b7ae0e3b936bc857ce973ab8666b2eb6a"
            }
          }
        }
      },
      "python@3.8": {
        "version": "3.8.12",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": "/opt/homebrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:cb44445caa00efd70c2b809d0fcca436200304fd798f10b61a5d6f9b96656c52",
              "sha256": "cb44445caa00efd70c2b809d0fcca436200304fd798f10b61a5d6f9b96656c52"
            },
            "big_sur": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:e7850f7c142853b69b3e3849e4a8d83817e2a331f9a6581813b36ef9c63f3add",
              "sha256": "e7850f7c142853b69b3e3849e4a8d83817e2a331f9a6581813b36ef9c63f3add"
            },
            "catalina": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:0ab8f1428b00ff48ea64f9e8108a5a5a48bfc2268b35216585ca73adfb6cd1aa",
              "sha256": "0ab8f1428b00ff48ea64f9e8108a5a5a48bfc2268b35216585ca73adfb6cd1aa"
            },
            "mojave": {
              "cellar": "/usr/local/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:9a493fe975a25ede0d82ee6fcd4e3b2b4db53d14159f0eb8161f912f4c8b0835",
              "sha256": "9a493fe975a25ede0d82ee6fcd4e3b2b4db53d14159f0eb8161f912f4c8b0835"
            },
            "x86_64_linux": {
              "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
              "url": "https://ghcr.io/v2/homebrew/core/python/3.8/blobs/sha256:3f508b82c8fd66a197b4ecf43e21ba7041637ce813b6c5fc4f603dcdb10cb504",
              "sha256": "3f508b82c8fd66a197b4ecf43e21ba7041637ce813b6c5fc4f603dcdb10cb504"
            }
          }
        }
      },
      "teensy_loader_cli": {
        "version": "2.1_2",
        "bottle": {
          "rebuild": 0,
          "root_url": "https://ghcr.io/v2/homebrew/core",
          "files": {
            "arm64_big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:dedc1adc526aa3115e52603b7d69b9177f76fdda51698faf26c1a37d2b648cac",
              "sha256": "dedc1adc526aa3115e52603b7d69b9177f76fdda51698faf26c1a37d2b648cac"
            },
            "big_sur": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:e2b86fdf7b04f907b5dbf5e1c31e1488b6de0f681be91acb8779d5d319fa0bbc",
              "sha256": "e2b86fdf7b04f907b5dbf5e1c31e1488b6de0f681be91acb8779d5d319fa0bbc"
            },
            "catalina": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:05c0f806839f8af46bcf6d95bf58247805a5293d4c704d38c2934799b6aa9f1f",
              "sha256": "05c0f806839f8af46bcf6d95bf58247805a5293d4c704d38c2934799b6aa9f1f"
            },
            "mojave": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:13a4a0fe8cf9b185003da32206bf330c215a9e0ee99bc4c7a901c474f553e7b1",
              "sha256": "13a4a0fe8cf9b185003da32206bf330c215a9e0ee99bc4c7a901c474f553e7b1"
            },
            "high_sierra": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:58f22f026085148841808fb0a9ec9f5f7558c1ef6fbf46a2ec2a0fea8b9f1c18",
              "sha256": "58f22f026085148841808fb0a9ec9f5f7558c1ef6fbf46a2ec2a0fea8b9f1c18"
            },
            "x86_64_linux": {
              "cellar": ":any_skip_relocation",
              "url": "https://ghcr.io/v2/homebrew/core/teensy_loader_cli/blobs/sha256:cc204fbd5fcabd5e53f382c899fd97625b1d1f99958b3abc7d9bcb5db687a6c2",
              "sha256": "cc204fbd5fcabd5e53f382c899fd97625b1d1f99958b3abc7d9bcb5db687a6c2"
            }
          }
        }
      }
    }
  },
  "system": {
    "macos": {
      "catalina": {
        "HOMEBREW_VERSION": "2.5.2",
        "HOMEBREW_PREFIX": "/usr/local",
        "Homebrew/homebrew-core": "6453cefc91e56634e1f55ef7bb2bbdc1a2a8ded9",
        "CLT": "1103.0.32.62",
        "Xcode": "11.5",
        "macOS": "10.15.6"
      },
      "mojave": {
        "HOMEBREW_VERSION": "2.2.5",
        "HOMEBREW_PREFIX": "/usr/local",
        "Homebrew/homebrew-core": "2da0dc898a663118daf535515a9d8eb4052e160f",
        "CLT": "10.3.0.0.1.1562985497",
        "Xcode": "11.3.1",
        "macOS": "10.14.6"
      },
      "big_sur": {
        "HOMEBREW_VERSION": "3.2.10",
        "HOMEBREW_PREFIX": "/usr/local",
        "Homebrew/homebrew-core": "017c694c1606a8638c7208a19d4a16cac7938074",
        "CLT": "12.5.0.22.9",
        "Xcode": "12.5",
        "macOS": "11.5.2"
      }
    }
  }
}
